# Site settings
title: CODE FARM
email: qqbuby@gmail.com
description: All animals are equal but some animals are more equal than others.
baseurl: ""
url: "https://blog.codefarm.me"
twitter_username: qqbuby
github_username: qqbuby
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - jekyll-post.rb
  - LICENSE
  - README.md

# AsciiDoctor
asciidoc:
  processor: asciidoctor
  ext: asciidoc,adoc,ad
  page_attribute_prefix: page
  require_front_matter_header: true
  sectids: ''
asciidoctor:
  attributes:
    idprefix: ''
    #sectids!: ''
    source-highlighter: rouge
    rouge-css: class # class, style
    #rouge-stylesheet: 'css/rouge.css'
    #rouge-style: colorful
    icons: font
    #icons: ''
    #iconsdir: '/images/icons'
    #sectnums@: ''
    #sectnumlevels@: 3
    #toclevels@: 2
    toc-title@: ''

# Plugins
plugins: [] 

# Pagination
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  debug: false
  title: :title
  permalink: "/page/:num/"
  per_page: 16
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 3
    after: 3

excerpt_separator: ""

# Build Command Options
strict_front_matter: true
incremental: true
livereload: true

# Serve Command Options
host: 0.0.0.0
port: 4000

# Permalinks
permalink: /:year/:month/:day/:title/

# Collections
collections:
