# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LESS IS MORE
email: qqbuby@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    一个半瓶子咣当的堆码猿
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qqbuby.github.io" # the base hostname & protocol for your site
twitter_username: qqbuby
github_username: qqbuby
timezone: Asia/Shanghai

# Build settings
markdown: kramdown

# Plugins
gems: [jekyll-paginate]

# Pagination
paginate: 10 

excerpt_separator: ""

# Serve Command Options
host: 0.0.0.0
