# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CODE FARM
email: qqbuby@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    All animals are equal but some animals are more equal than others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codefarm.me" # the base hostname & protocol for your site
twitter_username: qqbuby
github_username: qqbuby
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

# Plugins
plugins: 
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed

# Pagination
paginate: 10 

excerpt_separator: ""

# Build Command Options
# incremental: true
livereload: true

# Serve Command Options
host: 0.0.0.0

# Permalinks
permalink: /:year/:month/:day/:title/

# Collections
collections:
  - kindle_notes

