# Site settings
title: CODE FARM
email: qqbuby@gmail.com
description: All animals are equal but some animals are more equal than others.
baseurl: ""
url: "https://codefarm.me"
twitter_username: qqbuby
github_username: qqbuby
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# AsciiDoctor
asciidoc:
  processor: asciidoctor
  ext: asciidoc,adoc,ad
  page_attribute_prefix: page
  require_front_matter_header: true
  sectids: ''
asciidoctor:
  attributes:
    idprefix: ''
    #sectids!: ''
    source-highlighter: rouge
    rouge-css: class # class, style
    #rouge-stylesheet: 'css/rouge.css'
    #rouge-style: colorful
    icons: font
    #icons: ''
    #iconsdir: '/images/icons'

# Plugins
plugins: [] 
whitelist:
  - jekyll-asciidoc

# Pagination
paginate: 10 

excerpt_separator: ""

# Build Command Options
strict_front_matter: true
# incremental: true
livereload: true

# Serve Command Options
host: 0.0.0.0

# Permalinks
permalink: /:year/:month/:day/:title/

# Collections
collections:
