= Public-key cryptography and X.509
:page-layout: post
:page-categories: ["crypto"]
:page-tags: ["crypto", "x509", "openssl", "certificate"]
:page-date: 2019-01-31 14:31:20 +0800
:page-revdate: 2021-11-09 14:19:21 +08:00 
:sectnums:
:toc:

== Cryptosystem

In cryptography, a *cryptosystem* is a suite of cryptographic algorithms needed to implement a particular security service, most commonly for achieving confidentiality (encryption).

Typically, a cryptosystem consists of three algorithms: one for https://en.wikipedia.org/wiki/Key_generation[key generation], one for encryption, and one for decryption. The term _cipher_ (sometimes _cypher_) is often used to refer to a pair of algorithms, one for encryption and one for decryption. Therefore, the term _cryptosystem_ is most often used when the key generation algorithm is important. For this reason, the term _cryptosystem_ is commonly used to refer to https://en.wikipedia.org/wiki/Public_key_cryptography[public key] techniques; however both "cipher" and "cryptosystem" are used for https://en.wikipedia.org/wiki/Symmetric-key_algorithm[symmetric key] techniques.

=== Public-key cryptography

*Public-key cryptography*, or *asymmetric cryptography*, is a cryptographic system that uses pairs of https://en.wikipedia.org/wiki/Cryptographic_key[keys]: _public keys_ which may be disseminated widely, and _private keys_ which are known only to the owner. The generation of such keys depends on cryptographic algorithms based on mathematical problems to produce one-way functions. Effective security only requires keeping the private key private; the public key can be openly distributed without compromising security.

In such a system, any person can encrypt a message using the receiver's _public key_, but that encrypted message can only be decrypted with the receiver's _private key_.

=== RSA

*RSA (Rivest--Shamir--Adleman)* is one of the first https://en.wikipedia.org/wiki/Public-key_cryptography[public-key cryptosystems] and is widely used for secure data transmission. In such a https://en.wikipedia.org/wiki/Cryptosystem[cryptosystem], the https://en.wikipedia.org/wiki/Encryption_key[encryption key] is public and it is different from the https://en.wikipedia.org/wiki/Decryption_key[decryption key] which is kept secret (private). The acronym RSA is made of the initial letters of the surnames of Ron Rivest, Adi Shamir, and Leonard Adleman, who first publicly described the algorithm in 1978.

RSA is a relatively slow algorithm, and because of this, it is less commonly used to directly encrypt user data. More often, RSA passes encrypted shared keys for https://en.wikipedia.org/wiki/Symmetric-key_algorithm[symmetric key] cryptography which in turn can perform bulk encryption-decryption operations at much higher speed.

=== Symmetric-key algorithm

*Symmetric-key algorithms* are algorithms for cryptography that use the same https://en.wikipedia.org/wiki/Key_(cryptography)[cryptographic keys] for both encryption of https://en.wikipedia.org/wiki/Plaintext[plaintext] and decryption of https://en.wikipedia.org/wiki/Ciphertext[ciphertext]. The keys may be identical or there may be a simple transformation to go between the two keys. The keys, in practice, represent a https://en.wikipedia.org/wiki/Shared_secret[shared secret] between two or more parties that can be used to maintain a private information link. This requirement that both parties have access to the secret key is one of the main drawbacks of symmetric key encryption, in comparison to https://en.wikipedia.org/wiki/Public_key_encryption[public-key encryption] (also known as asymmetric key encryption).

=== Public key certificate

In https://en.wikipedia.org/wiki/Cryptography[cryptography], a *public key certificate*, also known as a *digital certificate* or *identity certificate*, is an electronic document used to prove the ownership of a https://en.wikipedia.org/wiki/Key_authentication[public key]. The certificate includes information about the key, information about the identity of its owner (called the subject), and the https://en.wikipedia.org/wiki/Digital_signature[digital signature] of an entity that has verified the certificate's contents (called the issuer). If the signature is valid, and the software examining the certificate trusts the issuer, then it can use that key to communicate securely with the certificate's subject. In email encryption, code signing, and e-signature systems, a certificate's subject is typically a person or organization. However, in https://en.wikipedia.org/wiki/Transport_Layer_Security[Transport Layer Security (TLS)] a certificate's subject is typically a computer or other device, though TLS certificates may identify organizations or individuals in addition to their core role in identifying devices. TLS, sometimes called by its older name Secure Sockets Layer (SSL), is notable for being a part of https://en.wikipedia.org/wiki/HTTPS[HTTPS], a protocol for securely browsing the web.

In a typical https://en.wikipedia.org/wiki/Public-key_infrastructure[public-key infrastructure] (PKI) scheme, the certificate issuer is a https://en.wikipedia.org/wiki/Certificate_authority[certificate authority] (CA), usually a company that charges customers to issue certificates for them. By contrast, in a web of trust scheme, individuals sign each other's keys directly, in a format that performs a similar function to a public key certificate.

The most common format for public key certificates is defined by X.509. Because X.509 is very general, the format is further constrained by profiles defined for certain use cases, such as https://en.wikipedia.org/wiki/PKIX[Public Key Infrastructure (X.509)] as defined in RFC 5280.

=== X.509

In https://en.wikipedia.org/wiki/Cryptography[cryptography], *X.509* is a standard defining the format of https://en.wikipedia.org/wiki/Public_key_certificate[public key certificates]. X.509 certificates are used in many Internet protocols, including https://en.wikipedia.org/wiki/Transport_Layer_Security[TLS/SSL], which is the basis for HTTPS, the secure protocol for browsing the web. They are also used in offline applications, like https://en.wikipedia.org/wiki/Electronic_signature[electronic signatures]. An X.509 certificate contains a public key and an identity (a hostname, or an organization, or an individual), and is either signed by a https://en.wikipedia.org/wiki/Certificate_authority[certificate authority] or self-signed. When a certificate is signed by a trusted certificate authority, or validated by other means, someone holding that certificate can rely on the public key it contains to establish secure communications with another party, or validate documents https://en.wikipedia.org/wiki/Digital_signature[digitally signed] by the corresponding private key.

==== Certificate filename extensions

There are several commonly used filename extensions for X.509 certificates. Unfortunately, some of these extensions are also used for other data such as private keys.

* `.pem` -- (https://en.wikipedia.org/wiki/Privacy-enhanced_Electronic_Mail[Privacy-enhanced Electronic Mail]) https://en.wikipedia.org/wiki/Base64[Base64] encoded https://en.wikipedia.org/wiki/Distinguished_Encoding_Rules[DER] certificate, enclosed between "[.code]``-----BEGIN CERTIFICATE-----``" and "[.code]``-----END CERTIFICATE-----``"
* `.cer`, `.crt`, `.der` -- usually in binary https://en.wikipedia.org/wiki/Distinguished_Encoding_Rules[DER] form, but Base64-encoded certificates are common too (see `.pem` above)

=== Certificate signing request

In public key infrastructure (PKI) systems, a *certificate signing request* (also *CSR* or *certification request*) is a message sent from an applicant to a https://en.wikipedia.org/wiki/Certificate_authority[certificate authority] in order to apply for a https://en.wikipedia.org/wiki/Public_key_certificate[digital identity certificate]. It usually contains the public key for which the certificate should be issued, identifying information (such as a domain name) and integrity protection (e.g., a digital signature). The most common format for CSRs is the https://en.wikipedia.org/wiki/PKCS[PKCS] #10 specification and another is the Signed Public Key and Challenge SPKAC format generated by some web browsers.

== OpenSSL

*OpenSSL* is a software library for applications that secure communications over computer networks against eavesdropping or need to identify the party at the other end. It is widely used in Internet web servers, serving a majority of all web sites.

OpenSSL contains an open-source implementation of the SSL and TLS protocols. The core library, written in the C programming language, implements basic cryptographic functions and provides various utility functions. Wrappers allowing the use of the OpenSSL library in a variety of computer languages are available.

The OpenSSL Software Foundation (OSF) represents the OpenSSL project in most legal capacities including contributor license agreements, managing donations, and so on. OpenSSL Software Services (OSS) also represents the OpenSSL project, for Support Contracts.

Versions are available for most Unix and Unix-like operating systems (including Solaris, Linux, macOS, QNX, and the various open-source BSD operating systems), OpenVMS and Microsoft Windows.

=== Create a self-signed-certificate

* Generate a self signed root certificate
+
[source,sh]
----
openssl req -x509 \
    -nodes \
    -newkey rsa:2048 -keyout key.pem \
    -days 30 \
    -out req.pem \
    -subj "/C=CN/ST=Shanghai/L=Shanghai/O=Global Security/OU=IT Department/CN=example.com"
    -addext "subjectAltName=DNS:example.com,DNS:*.example.com"
----

* Generate a self signed root certificate from a private key
+
[source,sh]
----
# Generate a 2048 bit RSA key (openssl genrsa -out key.pem 2048)
openssl genpkey \
    -algorithm RSA \
    -pkeyopt rsa_keygen_bits:2048 \
    -out key.pem
# Generate a certificate request from a private key
openssl req -x509 \
    -new \
    -key key.pem \
    -subj "/C=CN/ST=Shanghai/L=Shanghai/O=Global Security/OU=IT Department/CN=example.com" \
    -out req.pem
# Display the subject and fingerprint of the cert req.pem
openssl x509 -in req.pem -subject -fingerprint -noout 
----
+
[source,text]
----
subject=C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = example.com
SHA1 Fingerprint=1A:EB:13:40:38:AD:2E:42:57:A6:8A:BB:09:7A:5B:70:8B:69:C6:20
----

=== Display the contents of a certificate:

[source,console]
----
$ openssl x509 -in req.pem -noout -issuer
issuer=C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = example.com

$ openssl x509 -in req.pem -noout -subject
subject=C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = example.com

$ openssl x509 -in req.pem -noout -fingerprint 
SHA1 Fingerprint=1A:EB:13:40:38:AD:2E:42:57:A6:8A:BB:09:7A:5B:70:8B:69:C6:20

$ openssl x509 -in req.pem -noout -dates 
notBefore=Nov  9 06:46:15 2021 GMT
notAfter=Dec  9 06:46:15 2021 GMT

$ openssl x509 -in cert.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            b6:bd:90:ab:2b:f2:ac:55
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = example.com
        Validity
            Not Before: Jan 31 08:53:20 2019 GMT
            Not After : Mar  2 08:53:20 2019 GMT
        Subject: C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = example.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:aa:1e:d0:44:1f:50:3f:15:87:90:85:f0:64:e8:
                    5a:5b:41:8a:6a:60:29:a8:ad:13:6b:37:a9:fe:28:
                    5b:fb:a5:33:3e:50:ff:aa:af:2f:77:2b:80:18:a7:
                    f1:0e:b5:b8:c8:43:33:ab:e7:fe:c0:22:ef:c1:e0:
                    15:7d:55:5d:90:65:55:29:23:ef:7c:5c:b7:76:dd:
                    08:6a:9d:11:4a:dd:8b:25:b8:64:e2:20:8e:9b:de:
                    d4:0a:53:8e:00:b8:f5:7a:40:35:82:80:fa:3e:23:
                    1d:5b:d0:6d:b2:d4:2d:26:23:4e:52:cf:cd:d8:26:
                    44:bd:60:8b:3c:b6:a7:b0:21:07:08:f0:cc:1e:62:
                    3a:23:6a:96:d8:43:82:65:7a:f2:d6:93:25:bb:af:
                    03:db:30:26:0d:88:b0:1c:80:fe:c4:7e:48:60:4a:
                    77:99:02:18:14:8c:43:b5:f2:5b:12:d3:50:b8:32:
                    04:7f:e8:3b:e0:40:4c:29:a3:57:66:97:0d:ae:d8:
                    b8:d6:77:3f:84:e5:94:0a:ed:5e:2a:4d:c0:77:d0:
                    2d:70:5b:3d:ee:88:17:11:a3:3b:c4:af:5b:78:df:
                    64:c0:1f:76:11:29:2b:66:f4:e2:e0:54:58:6d:72:
                    43:74:51:56:1d:96:b5:ab:fe:12:af:2b:86:a7:eb:
                    97:a3
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                7D:64:0D:68:8D:5A:EA:8D:E3:7D:D1:04:06:8F:63:D0:3E:EB:2C:9F
            X509v3 Authority Key Identifier:
                keyid:7D:64:0D:68:8D:5A:EA:8D:E3:7D:D1:04:06:8F:63:D0:3E:EB:2C:9F

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         7a:f3:91:f2:01:cc:59:f0:62:7d:76:e4:48:05:0e:f2:9d:9e:
         86:2a:27:fa:b6:00:7b:9c:d7:e1:f4:7f:9e:b3:48:5f:d4:32:
         cf:1e:a5:64:ff:95:0a:47:88:e5:1a:5c:32:46:ac:a2:a4:fc:
         a6:ed:fc:15:d0:07:f6:0e:fb:86:35:39:2d:f3:56:c1:a2:4a:
         c5:e5:aa:0d:17:fa:76:d6:42:89:09:a6:b7:9f:7a:da:d3:6f:
         b3:9a:a9:28:7e:2a:15:71:6c:27:82:b9:79:7a:74:3d:40:b9:
         56:5d:b3:61:32:2a:79:e3:d9:15:09:09:72:9e:ad:1d:3f:ab:
         33:dc:99:a3:c9:94:0b:0b:98:f9:d6:d1:29:33:fb:dd:39:ed:
         9a:16:81:85:33:60:40:d1:f8:18:1d:d4:c6:a1:31:9c:f4:aa:
         04:9a:7a:71:e4:8d:78:7d:64:ef:f8:6a:a8:f8:5b:bd:5a:c2:
         3f:39:a5:de:06:ea:55:47:18:fe:b3:67:e7:2e:92:6f:e3:1a:
         18:a0:bb:a9:20:e3:4d:1a:77:26:a9:ca:49:5b:f1:b5:55:aa:
         c3:26:74:f7:09:fb:10:23:16:38:f5:ba:7c:f3:95:92:4b:fd:
         a7:6d:90:d3:6b:4f:26:d7:d4:a8:87:9e:d1:3c:9f:87:e6:3f:
         35:9c:d9:1e
----

=== Sign certificate signing request


* Generate a self signed root certificate
+
[source,sh]
----
openssl req \
    -x509 \
    -nodes \
    -newkey rsa:2048 -keyout ca.key \
    -subj "/C=CN/ST=Shanghai/L=Shanghai/O=Global Security/OU=IT Department/CN=example.com" \
    -out ca.crt
----

* Generate a certificate signing request
+
[source,sh]
----
openssl req -nodes \
    -newkey rsa:2048 -keyout localhost.key \
    -subj "/C=CN/ST=Shanghai/L=Shanghai/O=Global Security/OU=IT Department/CN=localhost" \
    -out localhost.csr
----

* Display the contents of the certificate request
+
[source,sh]
----
openssl req -in localhost.csr -noout -text
----
+
[source,text]
----
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:d8:eb:2e:d7:3c:94:92:a2:e7:35:e3:45:78:40:
                    f6:76:73:dc:70:b9:c6:2f:6f:ea:f6:9b:da:d2:58:
                    fd:ed:5f:e4:c6:76:56:25:35:e4:27:7b:6d:58:2b:
                    06:71:17:ae:a3:8a:8e:bd:f2:f4:bc:24:64:7d:ea:
                    4f:8a:2b:66:9d:36:e7:6a:23:0e:02:5a:92:b2:1d:
                    a8:95:33:a6:f5:23:a4:9d:2b:c5:50:69:de:fc:f0:
                    c9:4c:f4:6f:5b:cf:6f:20:3e:52:05:02:32:5e:ae:
                    81:50:69:13:ac:c8:fb:d8:b9:b7:78:24:e7:1f:ea:
                    52:6b:f6:ca:71:3e:9c:0a:91:e9:97:59:07:e9:1b:
                    af:1b:c5:c4:14:83:c2:c8:e5:80:cf:bc:4e:ac:65:
                    0f:d7:69:24:eb:3c:2e:51:c9:88:91:4c:33:10:5e:
                    e3:3d:76:42:e1:e1:65:5b:ef:1a:8c:b9:55:92:b4:
                    6b:d7:a3:86:78:36:b7:58:6b:e5:d5:38:07:fa:52:
                    bb:87:a1:ae:38:ce:0f:a5:44:1f:c6:41:b3:f2:9a:
                    1c:2e:22:ea:aa:9f:b0:ec:4a:3b:b8:86:49:08:8c:
                    f9:81:7a:cd:1b:77:b2:31:5e:69:e4:51:cc:a1:1f:
                    ca:01:ce:c1:3a:d7:c8:cf:76:21:44:b3:ed:fc:b9:
                    91:91
                Exponent: 65537 (0x10001)
        Attributes:
            a0:00
    Signature Algorithm: sha256WithRSAEncryption
         b9:6a:c8:d1:7b:5b:c9:d4:b4:b3:8f:ed:93:4f:16:00:44:f1:
         3f:0a:5b:64:d4:71:f2:d7:5b:71:6e:1e:0e:be:3b:8b:a1:f5:
         89:45:b0:33:6c:cf:c1:56:36:71:1a:54:78:d1:2e:90:f6:86:
         f4:99:8e:c6:ee:d7:64:58:37:22:09:5e:5e:cf:09:eb:06:94:
         3b:bc:e7:cd:55:98:48:cf:3e:4c:0a:bd:b7:c5:8d:03:0a:08:
         1c:35:10:fb:78:e7:16:6e:8d:c5:f3:87:5a:f8:2b:cd:4a:94:
         ca:0a:e8:a1:ba:59:96:e7:3d:62:78:5a:a9:24:78:a1:36:6a:
         c1:2b:4f:6b:54:df:34:41:68:49:01:01:e6:ed:61:c1:8e:80:
         d4:93:68:7e:8a:68:82:24:c0:62:e7:9b:77:b1:b1:6c:e0:40:
         b8:4b:64:1b:de:47:a5:1e:6a:21:82:fd:c8:27:50:3f:62:5f:
         c6:12:89:89:4d:85:82:b6:b9:0b:5f:9e:2a:19:94:13:05:d9:
         bb:cc:db:0b:1d:58:04:bf:99:2b:8f:3e:ba:29:11:68:b0:4d:
         58:d7:07:ac:c1:73:6c:80:a4:3c:ca:19:82:6e:fc:5d:44:ce:
         4b:c3:12:8d:6a:35:12:c9:b0:a8:64:47:f7:6d:49:04:68:01:
         ca:b6:6c:11
----

* Sign a certificate request using the CA certificate above
+
[source,sh]
----
openssl x509 \
    -req \
    -in localhost.csr \
    -CA ca.crt \
    -CAkey ca.key \
    -CAcreateserial \
    -days 10000 \
    -out localhost.crt
----

* Display the contents of the certificate
+
[source,console]
----
$ openssl x509 -in localhost.crt -subject -issuer -noout 
subject=C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = localhost
issuer=C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = example.com
----

=== Generate certificate with `subjectAltName`

[source,sh,highlight='8']
----
openssl req -x509 \
  -nodes \
  -newkey rsa:4096 \
  -days 3650 \
  -keyout loca.io.ca.key \
  -out local.io.ca.crt \
  -subj "/C=CN/ST=Shanghai/L=Shanghai/O=Global Security/OU=IT Department/CN=*.local.io" \
  -addext "subjectAltName=DNS:local.io,DNS:*.local.io"
----

[source,console,highlight='15-16']
----
$ openssl x509 -in local.io.ca.crt -noout -text 
Certificate:
    Data:
        Version: 3 (0x2)
. . .
        Subject: C = CN, ST = Shanghai, L = Shanghai, O = Global Security, OU = IT Department, CN = *.local.io
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                35:67:D0:64:8B:2D:F6:62:78:65:CA:6D:A5:6C:FB:4B:67:7F:61:80
            X509v3 Authority Key Identifier: 
                keyid:35:67:D0:64:8B:2D:F6:62:78:65:CA:6D:A5:6C:FB:4B:67:7F:61:80

            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Alternative Name: 
                DNS:local.io, DNS:*.local.io
. . .
----

=== Create config file for generating CSR

* Generate a `server.key` with 2048bit
+
[source,sh]
----
openssl genrsa -out server.key 2048
----

* Create a config file (e.g. _csr.conf_) for generating a CSR
+
[source,conf]
----
# csr.conf
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
# C = <country>
C = CN
# ST = <state>
ST = Shanghai
# L = <city>
L = Shanghai
# O = <organization>
# 1.O = <organization>
# 2.O = <organization>
O = IT Department
# OU = <organization unit>
# 1.OU = <organization unit>
# 2.OU = <organization unit>
OU = Developer
# CN = <MASTER_IP>
CN = developer

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
DNS.5 = kubernetes.default.svc.cluster.local
#IP.1 = <MASTER_IP>
IP.1 = 127.0.0.1
#IP.2 = <MASTER_CLUSTER_IP>
IP.2 = 192.168.91.128

[ v3_ext ]
authorityKeyIdentifier=keyid,issuer:always
basicConstraints=CA:FALSE
keyUsage=keyEncipherment,dataEncipherment
extendedKeyUsage=serverAuth,clientAuth
subjectAltName=@alt_names
----

* Generate the certificate signing request based on the config file
+
[source,sh]
----
openssl req -new -key server.key -out server.csr -config csr.conf
----

* Generate the server certificate using the ca.key, ca.crt and server.csr
+
[source,sh]
----
openssl x509 \
    -req \
    -in server.csr \
    -CA ca.crt -CAkey ca.key \
    -CAcreateserial \
    -days 10000 \
    -extensions v3_ext \
    -extfile csr.conf \
    -out server.crt
----

== References

. Cryptosystem, https://en.wikipedia.org/wiki/Cryptosystem
. Public-key cryptography, https://en.wikipedia.org/wiki/Public-key_cryptography
. RSA (cryptosystem), https://en.wikipedia.org/wiki/RSA_(cryptosystem)
. Symmetric-key algorithm, https://en.wikipedia.org/wiki/Symmetric-key_algorithm
. X.509, https://en.wikipedia.org/wiki/X.509
. Certificate signing request, https://en.wikipedia.org/wiki/Certificate_signing_request
. OpenSSL, https://en.wikipedia.org/wiki/OpenSSL
. https://crypto.stackexchange.com/questions/43697/what-is-the-difference-between-pem-csr-key-and-crt
. https://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file
. https://www.shellhacks.com/create-csr-openssl-without-prompt-non-interactive/
