= How to compile and run Java
:page-layout: post
:page-categories: ['java']
:page-tags: ['java', 'maven', 'jvm']
:revdate: 2021-11-01 13:12:53 +0800
:sectnums:
:toc:

== The `javac` Command

*  *Hello.java*
+
[source,java]
----
// Hello.java
public class Hello {
   public static void main(String[] args) {
      System.out.println("Hello Java!");
   }
} 
----

* *Complile with `javac`*
+
[source,console]
----
$ javac Hello.java 
$ java Hello 
Hello Java!
----

** *javac -d and java -cp*
+
[source,console]
----
$ javac Hello.java -d target/classes/
$ java -cp target/classes/ Hello 
Hello Java!
----

== The `java` Command

The *java* command starts a Java application. It does this by starting the Java Virtual Machine (JVM), loading the specified class, and calling that class's _main()_ method. The method must be declared _public_ and _static_, it must not return any value, and it must accept a _String_ array as a parameter. The method declaration has the following form:

[source,java]
public static void main(String[] args)

In source-file mode, the java command can launch a class declared in a source file.

NOTE: You can use the `JDK_JAVA_OPTIONS` launcher environment variable to prepend its content to the actual command line of the java launcher.

By default, the first argument that isn't an option of the java command is the fully qualified name of the class to be called. If `-jar` is specified, then its argument is the name of the JAR file containing class and resource files for the application. The startup class must be indicated by the `Main-Class` manifest header in its manifest file.

Arguments after the class file name or the JAR file name are passed to the _main()_ method.

* *To launch a single source-file program*
+
** *Synopsis*
+
[source,console]
----
java [options] source-file [args ...]
----

** *java Hello.java*
+
[source,console]
----
$ java Hello.java
Hello Java!
----

* *To launch a class file*

** *Synopsis*
+
[source,console]
----
java [options] mainclass [args ...]
----

** *java Hello*
+
[source,console]
----
$ javac Hello.java 
$ java Hello 
Hello Java!
----

* *To launch the main class in a JAR file*
+
Executes a program encapsulated in a JAR file. The _jarfile_ argument is the name of a JAR file with a manifest that contains a line in the form `Main-Class:classname` that defines the class with the `public static void main(String[] args)` method that serves as your application's starting point. When you use `-jar`, the specified JAR file is the source of all user classes, and other class path settings are ignored.
+
** *Synopsis*
+
[source,console]
----
java [options] -jar jarfile [args ...]
----

** *The `jar` command*

*** *Synopsis*
+
[source,console]
----
jar [OPTION ...] [ [--release VERSION] [-C dir] files] ...
----

*** *Create an jar*
+
[source,console]
----
$ jar -cf foo.jar Hello.class 
$ java -cp foo.jar Hello
Hello Java!
----

*** *Create an executable jar*
+
[source,console,highlight='2,12']
----
$ java -jar foo.jar
no main manifest attribute, in foo.jar

$ jar --create --file buz.jar --main-class Hello Hello.class 
$ java -jar buz.jar 
Hello Java!

$ jar xf buz.jar META-INF/
$ cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Created-By: 11.0.12 (Debian)
Main-Class: Hello

----

=== Overview of Java Options

The java command supports a wide range of options in the following categories:

* *Standard Options for Java*: Options guaranteed to be supported by all implementations of the Java Virtual Machine (JVM). They're used for common actions, such as checking the version of the JRE, setting the class path, enabling verbose output, and so on.

* *Extra Options for Java*: General purpose options that are specific to the Java HotSpot Virtual Machine. They aren't guaranteed to be supported by all JVM implementations, and are subject to change. These options start with `-X`.

The advanced options aren't recommended for casual use. These are developer options used for tuning specific areas of the Java HotSpot Virtual Machine operation that often have specific system requirements and may require privileged access to system configuration parameters. 

Boolean options are used to either enable a feature that's disabled by default or disable a feature that's enabled by default. Such options don't require a parameter. *Boolean -XX options* are enabled using the plus sign (`-XX:+OptionName`) and disabled using the minus sign (`-XX:-OptionName`).

For *options that require an argument*, the argument may be separated from the option name by a `space`, a `colon` (:), or an `equal sign` (=), or the argument may `directly follow the option` (the exact syntax differs for each option). If you're expected to `specify the size in bytes`, then you can use no suffix, or use the suffix k or K for kilobytes (KB), m or M for megabytes (MB), or g or G for gigabytes (GB). For example, to set the size to 8 GB, you can specify either 8g, 8192m, 8388608k, or 8589934592 as the argument. If you are expected to `specify the percentage`, then use a number from 0 to 1. For example, specify 0.25 for 25%.

=== Standard Options for Java

== References

* https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html
* https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html
* https://docs.oracle.com/en/java/javase/17/docs/specs/man/jar.html
* https://maven.apache.org/guides/getting-started/
* https://maven.apache.org/pom.html
* https://maven.apache.org/settings.html
* https://maven.apache.org/plugins/maven-help-plugin/usage.html
* https://maven.apache.org/plugins/maven-dependency-plugin/usage.html
* https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
* https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
