= System Architect and Diagrams
:page-layout: post
:page-categories: [architect]
:page-tags: [architect]
:page-date: 2021-11-18 11:09:43 +0800
:page-revdate: 2021-11-18 11:09:43 +0800
:sectnums:
:toc:

== Software architecture

Software architecture^<<software_architecture>>^ refers to the fundamental structures of a software system and the discipline of creating such structures and systems. Each structure comprises software elements, relations among them, and properties of both elements and relations.[1] The architecture of a software system is a metaphor, analogous to the architecture of a building. It functions as a blueprint for the system and the developing project, laying out the tasks necessary to be executed by the design teams.

== 4+1 architectural view model

4+1^<<four-plus-one>>^ is a view model used for "describing the architecture of software-intensive systems, based on the use of multiple, concurrent views". The views are used to describe the system from the viewpoint of different stakeholders, such as end-users, developers, system engineers, and project managers. The four views of the model are logical, development, process and physical view. In addition, selected use cases or scenarios are used to illustrate the architecture serving as the 'plus one' view. 

image::/assets/software-arthitecture/4+1_Architectural_View_Model.svg["Illustration of the 4+1 Architectural View Model",55%,55%]

* *Logical view*: The logical view is concerned with the functionality that the system provides to end-users. UML diagrams are used to represent the logical view, and include class diagrams, and state diagrams.

* *Process view*: The process view deals with the dynamic aspects of the system, explains the system processes and how they communicate, and focuses on the run time behavior of the system. The process view addresses concurrency, distribution, integrator, performance, and scalability, etc. UML diagrams to represent process view include the <<Sequence diagram>>, communication diagram, activity diagram.

* *Development view*: The development view illustrates a system from a programmer's perspective and is concerned with software management. This view is also known as the implementation view. It uses the UML Component diagram to describe system components. UML Diagrams used to represent the development view include the package diagram.

* *Physical view*: The physical view depicts the system from a system engineer's point of view. It is concerned with the topology of software components on the physical layer as well as the physical connections between these components. This view is also known as the deployment view. UML diagrams used to represent the physical view include the deployment diagram.

* *Scenarios*: The description of an architecture is illustrated using a small set of use cases, or scenarios, which become a fifth view. The scenarios describe sequences of interactions between objects and between processes. They are used to identify architectural elements and to illustrate and validate the architecture design. They also serve as a starting point for tests of an architecture prototype. This view is also known as the use case view.

== Unified Modeling Language

The *Unified Modeling Language* (UML)^<<uml>>^ is a general-purpose, developmental, modeling language in the field of software engineering that is intended to provide a standard way to visualize the design of a system. The creation of UML was originally motivated by the desire to standardize the disparate notational systems and approaches to software design. In software engineering, most practitioners do not use UML, but instead produce informal hand drawn diagrams; these diagrams, however, often include elements from UML.

UML 2 has many types of diagrams, which are divided into two categories. Some types represent *structural* information, and the rest represent general types of *behavior*, including a few that represent different aspects of *interactions*. These diagrams can be categorized hierarchically as shown in the following class diagram:

image::/assets/software-arthitecture/UML_diagrams_overview.svg[,75%,75%]

=== Sequence diagram

A *sequence diagram* or *system sequence diagram* (SSD)^<<ssd>>^ shows object interactions arranged in time sequence in the field of software engineering. It depicts the _objects involved_ in the scenario and the _sequence of messages exchanged_ between the objects needed to carry out the functionality of scenario. Sequence diagrams are typically associated with use case realizations in the logical view of the system under development. Sequence diagrams are sometimes called *event diagrams* or *event scenarios*.

For a particular scenario of a use case, the diagrams show the events that external actors generate, their order, and possible inter-system events. All systems are treated as a black box; the diagram places emphasis on events that cross the system boundary from actors to systems. A system sequence diagram should be done for the main success scenario of the use case, and frequent or complex alternative scenarios. 

image::/assets/software-arthitecture/CheckEmail.svg[,55%,55%]

== C~4~ model

*C4 model* ^<<c4_model>>^ is a lean graphical notation technique for modelling the architecture of software systems.

C4 ^<<c4-architecture-model>>^ stands for *context*, *containers*, *components*, and *code* — a set of hierarchical diagrams that you can use to describe your software architecture at different zoom levels, each useful for different audiences. ^<<c4model_com>>^

C4 model documents the architecture of a software system, by showing multiple points of view that explain the *decomposition* of a system into *containers* and *components*, the *relationship* between these elements, and, where appropriate, the relation with its *users*.

The viewpoints are organized according to their hierarchical level:

* Context diagrams (level 1): show the system in scope and its relationship with users and other systems;

* Container diagrams (level 2): decompose a system into interrelated containers. A container represents an application or a data store;

* Component diagrams (level 3): decompose containers into interrelated components, and relate the components to other containers or other systems;

* Code diagrams (level 4): provide additional details about the design of the architectural elements that can be mapped to code. C4 model relies at this level on existing notations such as Unified Modelling Language (UML), Entity Relation Diagrams (ERD) or diagrams generated by Integrated Development Environments (IDE).

For level 1 to 3, the C4 model uses 5 basic diagramming elements: persons, software systems, containers, components and relationships. The technique is not prescriptive for the layout, shape, colour and style of these elements. Instead, the C4 model recommends using simple diagrams based on nested boxes in order to facilitate interactive collaborative drawing. The technique also promotes good modelling practices such as providing a title and legend on every diagram, and clear unambiguous labelling in order to facilitate the understanding by the intended audience.

C4 model facilitates collaborative visual architecting and evolutionary architecture in the context of agile teams where more formal documentation methods and up-front architectural design are not desired.

== Architectural Description Language

By taking a look at other description languages, we can see that ArchiMate^<<archimate-forum>>^ is more powerful and suitable for modeling enterprise systems in comparison to UML^<<uml>>^; there is also BPMN^<<bpmn>>^ which is particularly targeted to business processes, etc. ^<<crafting-architectural-diagrams>>^

[bibliography]
== References

* [[[software_architecture, 1]]] https://en.wikipedia.org/wiki/Software_architecture
* [[[four-plus-one, 2]]] https://en.wikipedia.org/wiki/4%2B1_architectural_view_model
* [[[uml, 3]]] https://en.wikipedia.org/wiki/Unified_Modeling_Language
* [[[ssd, 4]]] https://en.wikipedia.org/wiki/Sequence_diagram
* [[[c4_model, 5]]] https://en.wikipedia.org/wiki/C4_model
* [[[c4model_com, 6]]] https://c4model.com/
* [[[c4-architecture-model, 7]]] https://www.infoq.com/articles/C4-architecture-model/
* [[[crafting-architectural-diagrams, 8]]] https://www.infoq.com/articles/crafting-architectural-diagrams/
* [[[archimate-forum, 9]]] https://www.opengroup.org/archimate-forum
* [[[bpmn, 10]]] https://www.bpmn.org/
