= Computer Network
:page-layout: post
:page-categories: []
:page-tags: []
:revdate: 2021-09-25 20:10:24 +0800
:toc:
:toclevels: 4

:computer: https://en.wikipedia.org/wiki/Computer
:node_networking: https://en.wikipedia.org/wiki/Node_(networking)
:communication_protocol: https://en.wikipedia.org/wiki/Communication_protocol
:digital_signal: https://en.wikipedia.org/wiki/Digital_signal
:interconnection: https://en.wikipedia.org/wiki/Interconnection
:telecommunication_network: https://en.wikipedia.org/wiki/Telecommunication_network
:network_topology: https://en.wikipedia.org/wiki/Network_topology

:personal_computer: https://en.wikipedia.org/wiki/Personal_computer
:server_computing: https://en.wikipedia.org/wiki/Server_(computing)
:networking_hardware: https://en.wikipedia.org/wiki/Networking_hardware
:host_network: https://en.wikipedia.org/wiki/Host_(network)
:network_address: https://en.wikipedia.org/wiki/Network_address
:internet_protocol: https://en.wikipedia.org/wiki/Internet_Protocol

:transmission_medium: https://en.wikipedia.org/wiki/Transmission_medium
:bandwidth_computing: https://en.wikipedia.org/wiki/Bandwidth_(computing)
:communications_protocol: https://en.wikipedia.org/wiki/Communications_protocol
:network_traffic_control: https://en.wikipedia.org/wiki/Network_traffic_control

:application_software: https://en.wikipedia.org/wiki/Application_software
:network_service: https://en.wikipedia.org/wiki/Network_service
:file_server: https://en.wikipedia.org/wiki/File_server

== Computer Network

A *computer network* is a set of {computer}[computers] sharing resources located on or provided by {node_networking}[network nodes]. The computers use common {communication_protocol}[communication protocols] over {digital_singal}[digital] {interconnection}[interconnections] to communicate with each other. These interconnections are made up of {telecommunication_network}[telecommunication network] technologies, based on physically wired, optical, and wireless radio-frequency methods that may be arranged in a variety of {network_topology}[network topologies].

The nodes of a computer network may include {personal_computer}[personal computers], {server_computing}[servers], {networking_hardware}[networking hardware], or other specialised or general-purpose {host_network}[hosts]. They are identified by {network_address}[network addresses], and may have hostnames. Hostnames serve as memorable labels for the nodes, rarely changed after initial assignment. Network addresses serve for locating and identifying the nodes by communication protocols such as the {internet_protocol}[Internet Protocol].

Computer networks may be classified by many criteria, including the {transmission_medium}[transmission medium] used to carry signals, {bandwidth_computing}[bandwidth], {communications_protocol}[communications protocols] to organize network traffic, the network size, the topology, {network_traffic_control}[traffic control] mechanism, and organizational intent.

Computer networks support many {application_software}[applications] and {network_service}[services], such as access to the World Wide Web, digital video, digital audio, shared use of {file_server}[application and storage servers], printers, and fax machines, and use of email and instant messaging applications. 

=== Network Packet

:network_packet: https://en.wikipedia.org/wiki/Network_packet
:packet-switched_network: https://en.wikipedia.org/wiki/Packet-switched_network
:error_detection: https://en.wikipedia.org/wiki/Error_detection
:header_computing: https://en.wikipedia.org/wiki/Header_(computing)
:trailer_computing: https://en.wikipedia.org/wiki/Trailer_(computing)
:payload_computing: https://en.wikipedia.org/wiki/Payload_(computing)
:circuit_switching: https://en.wikipedia.org/wiki/Circuit_switching
:message_queue: https://en.wikipedia.org/wiki/Message_queue
:maximum_transmission_unit: https://en.wikipedia.org/wiki/Maximum_transmission_unit

Most modern computer networks use protocols based on packet-mode transmission. A {network_packet}[network packet] is a formatted unit of data carried by a {packet-switched_network}[packet-switched network].

Packets consist of two types of data: control information and user data (payload). The control information provides data the network needs to deliver the user data, for example, source and destination {network_address}[network addresses], {error_detection}[error detection] codes, and sequencing information. Typically, control information is found in {header_computing}[packet headers] and {trailer_computing}[trailers], with {payload_computing}[payload data] in between.

With packets, the {bandwidth_computing}[bandwidth] of the transmission medium can be better shared among users than if the network were {circuit_switching}[circuit switched]. When one user is not sending packets, the link can be filled with packets from other users, and so the cost can be shared, with relatively little interference, provided the link isn't overused. Often the route a packet needs to take through a network is not immediately available. In that case, the packet is {message_queue}[queued] and waits until a link is free.

The physical link technologies of packet network typically limit the size of packets to a certain {maximum_transmission_unit}[maximum transmission unit] (MTU). A longer message may be fragmented before it is transferred and once the packets arrive, they are reassembled to construct the original message. 

:protocol_data_unit: https://en.wikipedia.org/wiki/Protocol_data_unit
:network_layer: https://en.wikipedia.org/wiki/Network_layer
:data_link_layer: https://en.wikipedia.org/wiki/Data_link_layer
:frame_networking: https://en.wikipedia.org/wiki/Frame_(networking)
:transport_layer: https://en.wikipedia.org/wiki/Transport_layer
:tcp_segment: https://en.wikipedia.org/wiki/TCP_segment
:datagram: https://en.wikipedia.org/wiki/Datagram
:ip_packet_disambiguation: https://en.wikipedia.org/wiki/IP_packet_(disambiguation)
:ethernet_frame: https://en.wikipedia.org/wiki/Ethernet_frame

.Terminology
****
In the seven-layer {osi_model}[OSI model] of computer networking, `packet` strictly refers to a {protocol_data_unit}[protocol data unit] at layer 3, the {network_layer}[network layer]. A data unit at layer 2, the {data_link_layer}[data link layer], is a {frame_networking}[`frame`]. In layer 4, the {transport_layer}[transport layer], the data units are {tcp_segment}[`segments`] and {datagram}[`datagrams`]. Thus, in the example of TCP/IP communication over Ethernet, a {tcp_segment}[TCP segment] is carried in one or more {ip_packet_disambiguation}[IP packets], which are each carried in one or more {ethernet_frame}[Ethernet frames]. 
****

=== Network Topology

:bus_network: https://en.wikipedia.org/wiki/Bus_network
:ethernet: https://en.wikipedia.org/wiki/Ethernet
:10base5: https://en.wikipedia.org/wiki/10BASE5
:10base2: https://en.wikipedia.org/wiki/10BASE2
:data_link_layer: https://en.wikipedia.org/wiki/Data_link_layer
:physical_layer: https://en.wikipedia.org/wiki/Physical_layer
:point-to-point_telecommunications: https://en.wikipedia.org/wiki/Point-to-point_(telecommunications)

:star_network: https://en.wikipedia.org/wiki/Star_network
:wireless_lan: https://en.wikipedia.org/wiki/Wireless_LAN
:wireless_access_point: https://en.wikipedia.org/wiki/Wireless_access_point

:ring_network: https://en.wikipedia.org/wiki/Ring_network
:fiber_distributed_data_interface: https://en.wikipedia.org/wiki/Fiber_Distributed_Data_Interface

:mesh_network: https://en.wikipedia.org/wiki/Mesh_network

:fully_connected_network: https://en.wikipedia.org/wiki/Fully_connected_network

:tree_network: https://en.wikipedia.org/wiki/Tree_network

{network_topology}[Network topology] is the layout, pattern, or organizational hierarchy of the interconnection of network hosts, in contrast to their physical or geographic location. Typically, most diagrams describing networks are arranged by their topology. The network topology can affect throughput, but reliability is often more critical. With many technologies, such as bus or star networks, a single failure can cause the network to fail entirely. In general, the more interconnections there are, the more robust the network is; but the more expensive it is to install.

Common layouts are:

* {bus_network}[Bus network]: all nodes are connected to a common medium along this medium. This was the layout used in the original {ethernet}[Ethernet], called {10base5}[10BASE5] and {10base2}[10BASE2]. This is still a common topology on the {data_link_layer}[data link layer], although modern {physical_layer}[physical layer] variants use {point-to-point_telecommunications}[point-to-point] links instead.

* {start_network}[Star network]: all nodes are connected to a special central node. This is the typical layout found in a {wireless_lan}[Wireless LAN], where each wireless client connects to the central {Wireless_access_point}[Wireless access point].

* {ring_network}[Ring network]: each node is connected to its left and right neighbour node, such that all nodes are connected and that each node can reach each other node by traversing nodes left- or rightwards. The {fiber_distributed_data_interface}[Fiber Distributed Data Interface] (FDDI) made use of such a topology.

* {mesh_network}[Mesh network]: each node is connected to an arbitrary number of neighbours in such a way that there is at least one traversal from any node to any other.

* {fully_connected_network}[Fully connected network]: each node is connected to every other node in the network.

* {tree_network}[Tree network]: nodes are arranged hierarchically.

The physical layout of the nodes in a network may not necessarily reflect the network topology. As an example, with {fiber_distributed_data_interface}[FDDI], the network topology is a ring, but the physical topology is often a star, because all neighboring connections can be routed via a central physical location. Physical layout is not completely irrelevant, however, as common ducting and equipment locations can represent single points of failure due to issues like fires, power failures and flooding. 

=== Overlay network

:overlay_network: https://en.wikipedia.org/wiki/Overlay_network
:peer-to-peer: https://en.wikipedia.org/wiki/Peer-to-peer
:modem: https://en.wikipedia.org/wiki/Modem
:telecommunications_network_data_network: https://en.wikipedia.org/wiki/Telecommunications_network#Data_network
:telephone_network: https://en.wikipedia.org/wiki/Telephone_network
:address_resolution_protocol: https://en.wikipedia.org/wiki/Address_Resolution_Protocol
:routing: https://en.wikipedia.org/wiki/Routing
:distributed_hash_table: https://en.wikipedia.org/wiki/Distributed_hash_table
:associative_array: https://en.wikipedia.org/wiki/Associative_array
:quality_of_service: https://en.wikipedia.org/wiki/Quality_of_service
:streaming_media: https://en.wikipedia.org/wiki/Streaming_media
:ip_multicast: https://en.wikipedia.org/wiki/IP_Multicast
:router_computing: https://en.wikipedia.org/wiki/Router_(computing)
:internet_service_provider: https://en.wikipedia.org/wiki/Internet_service_provider
:multicast: https://en.wikipedia.org/wiki/Multicast

An {overlay_network}[overlay network] is a virtual network that is built on top of another network. Nodes in the overlay network are connected by virtual or logical links. Each link corresponds to a path, perhaps through many physical links, in the underlying network. The topology of the overlay network may (and often does) differ from that of the underlying one. For example, many {peer-to-peer}[peer-to-peer] networks are overlay networks. They are organized as nodes of a virtual system of links that run on top of the Internet.

Overlay networks have been around since the invention of networking when computer systems were connected over telephone lines using {modem}[modems], before any {telecommunications_network_data_network}[data network] existed.

The most striking example of an overlay network is the Internet itself. The Internet itself was initially built as an overlay on the {telephone_network}[telephone network]. Even today, each Internet node can communicate with virtually any other through an underlying mesh of sub-networks of wildly different topologies and technologies. {address_resolution_protocol}[Address resolution] and {routing}[routing] are the means that allow mapping of a fully connected IP overlay network to its underlying network.

Another example of an overlay network is a {distributed_hash_table}[distributed hash table], which maps keys to nodes in the network. In this case, the underlying network is an IP network, and the overlay network is a table (actually a {associative_array}[map]) indexed by keys.

Overlay networks have also been proposed as a way to improve Internet routing, such as through {quality_of_service}[quality of service] guarantees achieve higher-quality {streaming_media}[streaming media]. Previous proposals such as IntServ, DiffServ, and {ip_multicast}[IP Multicast] have not seen wide acceptance largely because they require modification of all {router_computing}[routers] in the network.[citation needed] On the other hand, an overlay network can be incrementally deployed on end-hosts running the overlay protocol software, without cooperation from {internet_service_provider}[Internet service providers]. The overlay network has no control over how packets are routed in the underlying network between two overlay nodes, but it can control, for example, the sequence of overlay nodes that a message traverses before it reaches its destination.

For example, https://en.wikipedia.org/wiki/Akamai_Technologies[Akamai Technologies] manages an overlay network that provides reliable, efficient content delivery (a kind of multicast). Academic research includes end system {multicast}[multicast], resilient routing and quality of service studies, among others. 

=== Network Links

:transmission_medium: https://en.wikipedia.org/wiki/Transmission_medium
:electrical_cable: https://en.wikipedia.org/wiki/Electrical_cable
:optical_fiber: https://en.wikipedia.org/wiki/Optical_fiber
:osi_model: https://en.wikipedia.org/wiki/OSI_model
:local_area_network: https://en.wikipedia.org/wiki/Local_area_network
:ethernet: https://en.wikipedia.org/wiki/Ethernet
:ieee_802_3: https://en.wikipedia.org/wiki/IEEE_802.3
:wireless_lan: https://en.wikipedia.org/wiki/Wireless_LAN
:radio_waves: https://en.wikipedia.org/wiki/Radio_waves
:power_line_communication: https://en.wikipedia.org/wiki/Power_line_communication
:power_cabling: https://en.wikipedia.org/wiki/Power_cabling

The transmission media (often referred to in the literature as the {transmission_medium}[physical medium]) used to link devices to form a computer network include {electrical_cable}[electrical cable], {optical_fiber}[optical fiber], and free space. In the {osi_model}[OSI model], the software to handle the media is defined at layers 1 and 2 — the physical layer and the data link layer.

A widely adopted family that uses copper and fiber media in {local_area_network}[local area network] (LAN) technology are collectively known as {ethernet}[Ethernet]. The media and protocol standards that enable communication between networked devices over Ethernet are defined by {ieee_802_3}[IEEE 802.3]. {wireless_lan}[Wireless LAN] standards use {radio_waves}[radio waves], others use infrared signals as a transmission medium. {power_line_communication}[Power line communication] uses a building's {power_cabling}[power cabling] to transmit data. 

==== Wired

:coaxial_cable: https://en.wikipedia.org/wiki/Coaxial_cable
:itu-t: https://en.wikipedia.org/wiki/ITU-T
:g_hn: https://en.wikipedia.org/wiki/G.hn
:twisted_pair: https://en.wikipedia.org/wiki/Twisted_pair
:crosstalk_electronics: https://en.wikipedia.org/wiki/Crosstalk_(electronics)
:optical_fiber: https://en.wikipedia.org/wiki/Optical_fiber
:optical_amplifier: https://en.wikipedia.org/wiki/Optical_amplifier
:Wavelength-division_multiplexing: https://en.wikipedia.org/wiki/Wavelength-division_multiplexing
:undersea_cables: https://en.wikipedia.org/wiki/Undersea_cables
:single-mode_optical_fiber: https://en.wikipedia.org/wiki/Single-mode_optical_fiber
:multi-mode_optical_fiber: https://en.wikipedia.org/wiki/Multi-mode_optical_fiber

The following classes of wired technologies are used in computer networking.

* {coaxial_cable}[Coaxial cable] is widely used for cable television systems, office buildings, and other work-sites for local area networks. Transmission speed ranges from 200 million bits per second to more than 500 million bits per second.

* {itu-t}[ITU-T] {g_hn}[G.hn] technology uses existing home wiring (coaxial cable, phone lines and power lines) to create a high-speed local area network.

* {twisted_pair}[Twisted pair] cabling is used for wired Ethernet and other standards. It typically consists of 4 pairs of copper cabling that can be utilized for both voice and data transmission. The use of two wires twisted together helps to reduce {crosstalk_electronics}[crosstalk] and electromagnetic induction. The transmission speed ranges from 2 Mbit/s to 10 Gbit/s. Twisted pair cabling comes in two forms: unshielded twisted pair (UTP) and shielded twisted-pair (STP). Each form comes in several category ratings, designed for use in various scenarios.

* An {optical_fiber}[optical fiber] is a glass fiber. It carries pulses of light that represent data via lasers and {optical_amplifier}[optical amplifiers]. Some advantages of optical fibers over metal wires are very low transmission loss and immunity to electrical interference. Using dense {Wavelength-division_multiplexing}[wave division multiplexing], optical fibers can simultaneously carry multiple streams of data on different wavelengths of light, which greatly increases the rate that data can be sent to up to trillions of bits per second. Optic fibers can be used for long runs of cable carrying very high data rates, and are used for {undersea_cables}[undersea cables] to interconnect continents. There are two basic types of fiber optics, {single-mode_optical_fiber}[single-mode optical fiber] (SMF) and {multi-mode_optical_fiber}[multi-mode optical fiber] (MMF). Single-mode fiber has the advantage of being able to sustain a coherent signal for dozens or even a hundred kilometers. Multimode fiber is cheaper to terminate but is limited to a few hundred or even only a few dozens of meters, depending on the data rate and cable grade.

==== Wireless

:microwave: https://en.wikipedia.org/wiki/Microwave
:communications_satellite: https://en.wikipedia.org/wiki/Communications_satellite
:cellular_network: https://en.wikipedia.org/wiki/Cellular_network
:transceiver: https://en.wikipedia.org/wiki/Transceiver
:spread_spectrum: https://en.wikipedia.org/wiki/Spread_spectrum
:ieee_802_11: https://en.wikipedia.org/wiki/IEEE_802.11
:wi-fi: https://en.wikipedia.org/wiki/Wi-Fi
:free-space_optical_communication: https://en.wikipedia.org/wiki/Free-space_optical_communication
:interplanetary_internet: https://en.wikipedia.org/wiki/Interplanetary_Internet
:ip_over_avian_carriers: https://en.wikipedia.org/wiki/IP_over_Avian_Carriers
:request_for_comments: https://en.wikipedia.org/wiki/Request_for_Comments

Network connections can be established wirelessly using radio or other electromagnetic means of communication.

* Terrestrial {microwave}[microwave] – Terrestrial microwave communication uses Earth-based transmitters and receivers resembling satellite dishes. Terrestrial microwaves are in the low gigahertz range, which limits all communications to line-of-sight. Relay stations are spaced approximately 40 miles (64 km) apart.

* {communications_satellite}[Communications satellites] – Satellites also communicate via microwave. The satellites are stationed in space, typically in geosynchronous orbit 35,400 km (22,000 mi) above the equator. These Earth-orbiting systems are capable of receiving and relaying voice, data, and TV signals.

* {cellular_network}[Cellular networks] use several radio communications technologies. The systems divide the region covered into multiple geographic areas. Each area is served by a low-power {transceiver}[transceiver].

* Radio and {spread_spectrum}[spread spectrum] technologies – Wireless LANs use a high-frequency radio technology similar to digital cellular. Wireless LANs use spread spectrum technology to enable communication between multiple devices in a limited area. {ieee_802_11}[IEEE 802.11] defines a common flavor of open-standards wireless radio-wave technology known as {wi-fi}[Wi-Fi].

* {free-space_optical_communication}[Free-space optical communication] uses visible or invisible light for communications. In most cases, line-of-sight propagation is used, which limits the physical positioning of communicating devices.

* Extending the Internet to interplanetary dimensions via radio waves and optical means, the {interplanetary_internet}[Interplanetary Internet].

* {ip_over_avian_carriers}[IP over Avian Carriers] was a humorous April fool's {request_for_comments}[Request for Comments], issued as RFC 1149. It was implemented in real life in 2001.

The last two cases have a large round-trip delay time, which gives slow two-way communication but doesn't prevent sending large amounts of information (they can have high throughput). 

=== Network Nodes

:systems_engineering: https://en.wikipedia.org/wiki/Systems_engineering
:network_interface_controller: https://en.wikipedia.org/wiki/Network_interface_controller
:repeater: https://en.wikipedia.org/wiki/Repeater
:ethernet_hub: https://en.wikipedia.org/wiki/Ethernet_hub
:network_bridge: https://en.wikipedia.org/wiki/Network_bridge
:network_switch: https://en.wikipedia.org/wiki/Network_switch
:router_computing: https://en.wikipedia.org/wiki/Router_(computing)
//:modem: https://en.wikipedia.org/wiki/Modem
:firewall_computing: https://en.wikipedia.org/wiki/Firewall_(computing)

Apart from any physical transmission media, networks are built from additional basic {systems_engineering}[system] building blocks, such as {network_interface_controller}[network interface controllers] (NICs), {repeater}[repeaters], {ethernet_hub}[hubs], {network_bridge}[bridges], {network_switch}[switches], {router_computing}[routers], {modem}[modems], and {firewall_computing}[firewalls]. Any particular piece of equipment will frequently contain multiple building blocks and so may perform multiple functions. 

==== Network interfaces

:computer_hardware: https://en.wikipedia.org/wiki/Computer_hardware
:network_media: https://en.wikipedia.org/wiki/Network_media
:mac_address: https://en.wikipedia.org/wiki/MAC_address
:institute_of_electrical_and_electronics_engineers: https://en.wikipedia.org/wiki/Institute_of_Electrical_and_Electronics_Engineers

A {network_interface_controller}[network interface controller] (NIC) is {computer_hardware}[computer hardware] that connects the computer to the {network_media}[network media] and has the ability to process low-level network information. For example, the NIC may have a connector for accepting a cable, or an aerial for wireless transmission and reception, and the associated circuitry.

In {ethernet}[Ethernet] networks, each network interface controller has a unique {mac_address}[Media Access Control] (MAC) address—usually stored in the controller's permanent memory. To avoid address conflicts between network devices, the {institute_of_electrical_and_electronics_engineers}[Institute of Electrical and Electronics Engineers] (IEEE) maintains and administers MAC address uniqueness. The size of an Ethernet MAC address is six octets. The three most significant octets are reserved to identify NIC manufacturers. These manufacturers, using only their assigned prefixes, uniquely assign the three least-significant octets of every Ethernet interface they produce. 

==== Repeaters and hubs

:electronics: https://en.wikipedia.org/wiki/Electronics
:retransmission_data_networks: https://en.wikipedia.org/wiki/Retransmission_(data_networks)
:propagation_delay: https://en.wikipedia.org/wiki/Propagation_delay
:5-4-3_rule: https://en.wikipedia.org/wiki/5-4-3_rule

A {repeater}[repeater] is an {electronics}[electronic] device that receives a network signal, cleans it of unnecessary noise and regenerates it. The signal is {retransmission_data_networks}[retransmitted] at a higher power level, or to the other side of obstruction so that the signal can cover longer distances without degradation. In most twisted pair Ethernet configurations, repeaters are required for cable that runs longer than 100 meters. With fiber optics, repeaters can be tens or even hundreds of kilometers apart.

Repeaters work on the physical layer of the OSI model but still require a small amount of time to regenerate the signal. This can cause a {propagation_delay}[propagation delay] that affects network performance and may affect proper function. As a result, many network architectures limit the number of repeaters used in a network, e.g., the Ethernet {5-4-3_rule}[5-4-3 rule].

*An Ethernet repeater with multiple ports is known as an {Ethernet_hub}[Ethernet hub].* In addition to reconditioning and distributing network signals, a repeater hub assists with collision detection and fault isolation for the network. Hubs and repeaters in LANs have been largely obsoleted by modern {network_switch}[network switches]. 

==== Bridges and switches

:network_segment: https://en.wikipedia.org/wiki/Network_segment
:frame_networking: https://en.wikipedia.org/wiki/Frame_(networking)
:computer_port_hardware: https://en.wikipedia.org/wiki/Computer_port_(hardware)

{network_bridge}[Network bridges] and {network_switch}[network switches] are distinct from a hub in that they only forward frames to the ports involved in the communication whereas a hub forwards to all ports. *Bridges only have two ports but a switch can be thought of as a multi-port bridge.* Switches normally have numerous ports, facilitating a star topology for devices, and for cascading additional switches.

Bridges and switches operate at the {date_link_layer}[data link layer] (layer 2) of the {osi_model}[OSI model] and {network_bridge}[bridge] traffic between two or more {network_segment}[network segments] to form a single local network. Both are devices that forward {frame_networking}[frames] of data between {computer_port_hardware}[ports] based on the destination MAC address in each frame. They learn the association of physical ports to MAC addresses by examining the source addresses of received frames and only forward the frame when necessary. If an unknown destination MAC is targeted, the device broadcasts the request to all ports except the source, and discovers the location from the reply.

Bridges and switches divide the network's collision domain but maintain a single broadcast domain. Network segmentation through bridging and switching helps break down a large, congested network into an aggregation of smaller, more efficient networks. 

==== Routers

:internetworking: https://en.wikipedia.org/wiki/Internetworking
:routing_table: https://en.wikipedia.org/wiki/Routing_table

A {router_computing}[router] is an {internetworking}[internetworking] device that forwards packets between networks by processing the addressing or routing information included in the packet. The routing information is often processed in conjunction with the {routing_table}[routing table]. A router uses its routing table to determine where to forward packets and does not require broadcasting packets which is inefficient for very big networks. 

==== Modems

:carrier_signal: https://en.wikipedia.org/wiki/Carrier_signal
:modulation: https://en.wikipedia.org/wiki/Modulation
:analog_signal: https://en.wikipedia.org/wiki/Analog_signal
:audio_signal: https://en.wikipedia.org/wiki/Audio_signal
:digital_subscriber_line: https://en.wikipedia.org/wiki/Digital_subscriber_line
:docsis: https://en.wikipedia.org/wiki/DOCSIS

{modem}[Modems] (modulator-demodulator) are used to connect network nodes via wire not originally designed for digital network traffic, or for wireless. To do this one or more {carrier_signal}[carrier signals] are {modulation}[modulated] by the {analog_signal}[digital signal] to produce an analog signal that can be tailored to give the required properties for transmission. Early modems modulated {audio_signal}[audio signals] sent over a standard voice telephone line. Modems are still commonly used for telephone lines, using a {digital_subscriber_line}[digital subscriber line] technology and cable television systems using {docsis}[DOCSIS] technology. 

==== Firewalls

:cyberattack: https://en.wikipedia.org/wiki/Cyberattack

A {firewall_computing}[firewall] is a network device or software for controlling network security and access rules. Firewalls are inserted in connections between secure internal networks and potentially insecure external networks such as the Internet. Firewalls are typically configured to reject access requests from unrecognized sources while allowing actions from recognized ones. The vital role firewalls play in network security grows in parallel with the constant increase in {cyberattack}[cyber attacks]. 

=== Communication protocols

:communication_protocol: https://en.wikipedia.org/wiki/Communication_protocol
:connection-oriented_communication: https://en.wikipedia.org/wiki/Connection-oriented_communication
:connectionless_communication: https://en.wikipedia.org/wiki/Connectionless_communication
:circuit_mode: https://en.wikipedia.org/wiki/Circuit_mode
:packet_switching: https://en.wikipedia.org/wiki/Packet_switching
:protocol_stack: https://en.wikipedia.org/wiki/Protocol_stack
:http: https://en.wikipedia.org/wiki/HTTP
:transmission_control_protocol: https://en.wikipedia.org/wiki/Transmission_control_protocol
:internet_protocol: https://en.wikipedia.org/wiki/Internet_protocol
:internet_protocol_suite: https://en.wikipedia.org/wiki/Internet_Protocol_Suite
:ieee_802_11: https://en.wikipedia.org/wiki/IEEE_802.11
:wireless_router: https://en.wikipedia.org/wiki/Wireless_router

A {communication_protocol}[communication protocol] is a set of rules for exchanging information over a network. Communication protocols have various characteristics. They may be {connection-oriented_communication}[connection-oriented] or {connectionless_communication}[connectionless], they may use {circuit_mode}[circuit mode] or {packet_switching}[packet switching], and they may use hierarchical addressing or flat addressing.

In a {protocol_stack}[protocol stack], often constructed per the {osi_model}[OSI model], communications functions are divided up into protocol layers, where each layer leverages the services of the layer below it until the lowest layer controls the hardware that sends information across the media. The use of protocol layering is ubiquitous across the field of computer networking. An important example of a protocol stack is {http}[HTTP] (the World Wide Web protocol) running over {transmission_control_protocol}[TCP] over {internet_protocol}[IP] (the {internet_protocol_suite}[Internet protocols]) over {ieee_802_11}[IEEE 802.11] (the Wi-Fi protocol). This stack is used between the {wireless_router}[wireless router] and the home user's personal computer when the user is surfing the web.

There are many communication protocols, a few of which are described below. 

==== Common protocols

:ipv4: https://en.wikipedia.org/wiki/IPv4
:ipv6: https://en.wikipedia.org/wiki/IPv6
:internet: https://en.wikipedia.org/wiki/Internet

===== Internet Protocol Suite

The {internet_protocol_suite}[Internet Protocol Suite], also called TCP/IP, is the foundation of all modern networking. It offers connection-less and connection-oriented services over an inherently unreliable network traversed by datagram transmission using Internet protocol (IP). At its core, the protocol suite defines the addressing, identification, and routing specifications for {ipv4}[Internet Protocol Version 4] (IPv4) and for {ipv6}[IPv6], the next generation of the protocol with a much enlarged addressing capability. The Internet Protocol Suite is the defining set of protocols for the {internet}[Internet].

===== IEEE 802

:ieee_802: https://en.wikipedia.org/wiki/IEEE_802
:bridging_networking: https://en.wikipedia.org/wiki/Bridging_(networking)
:spanning_tree_protocol: https://en.wikipedia.org/wiki/Spanning_Tree_Protocol
:virtual_lan: https://en.wikipedia.org/wiki/Virtual_LAN
:network_access_control: https://en.wikipedia.org/wiki/Network_Access_Control

{ieee_802}[IEEE 802] is a family of IEEE standards dealing with local area networks and metropolitan area networks. The complete IEEE 802 protocol suite provides a diverse set of networking capabilities. The protocols have a flat addressing scheme. They operate mostly at layers 1 and 2 of the OSI model.

For example, {bridging_networking}[MAC bridging] (IEEE 802.1D) deals with the routing of Ethernet packets using a {spanning_tree_protocol}[Spanning Tree Protocol]. IEEE 802.1Q describes {virtual_lan}[VLANs], and IEEE 802.1X  defines a port-based {network_access_control}[Network Access Control] protocol, which forms the basis for the authentication mechanisms used in VLANs (but it is also found in WLANs) – it is what the home user sees when the user has to enter a "wireless access key". 

===== Ethernet

{ethernet}[Ethernet], sometimes simply called LAN, is a family of protocols used in wired LANs, described by a set of standards together called IEEE 802.3 published by the {institute_of_electrical_and_electronics_engineers}[Institute of Electrical and Electronics Engineers]. 

===== Wireless LAN

:wireless_lan: https://en.wikipedia.org/wiki/Wireless_LAN

{wireless_lan}[Wireless LAN], also widely known as WLAN or WiFi, is probably the most well-known member of the IEEE 802 protocol family for home users today. It is standardized by IEEE 802.11 and shares many properties with wired Ethernet. 

===== SONET/SDH

:synchronous_optical_networking: https://en.wikipedia.org/wiki/Synchronous_optical_networking
:multiplexing: https://en.wikipedia.org/wiki/Multiplexing
:circuit_switching: https://en.wikipedia.org/wiki/Circuit_switching
:pcm: https://en.wikipedia.org/wiki/PCM
:asynchronous_transfer_mode: https://en.wikipedia.org/wiki/Asynchronous_Transfer_Mode

{synchronous_optical_networking}[Synchronous optical networking] (SONET) and Synchronous Digital Hierarchy (SDH) are standardized {multiplexing}[multiplexing] protocols that transfer multiple digital bit streams over optical fiber using lasers. They were originally designed to transport circuit mode communications from a variety of different sources, primarily to support real-time, uncompressed, {circuit_switching}[circuit-switched] voice encoded in {pcm}[PCM] (Pulse-Code Modulation) format. However, due to its protocol neutrality and transport-oriented features, SONET/SDH also was the obvious choice for transporting {asynchronous_transfer_mode}[Asynchronous Transfer Mode] (ATM) frames. 

===== Asynchronous Transfer Mode

:time-division_multiplexing: https://en.wikipedia.org/wiki/Time-division_multiplexing
:cell_relay: https://en.wikipedia.org/wiki/Cell_relay
:frame_relay: https://en.wikipedia.org/wiki/Frame_Relay
:circuit_switching: https://en.wikipedia.org/wiki/Circuit_switching
:packet_switching: https://en.wikipedia.org/wiki/Packet_switching
:latency_engineering: https://en.wikipedia.org/wiki/Latency_(engineering)
:virtual_circuit: https://en.wikipedia.org/wiki/Virtual_circuit
:next_generation_network: https://en.wikipedia.org/wiki/Next_generation_network
:last_mile: https://en.wikipedia.org/wiki/Last_mile
:internet_service_provider: https://en.wikipedia.org/wiki/Internet_service_provider

{asynchronous_transfer_mode}[Asynchronous Transfer Mode] (ATM) is a switching technique for telecommunication networks. It uses asynchronous {time-division_multiplexing}[time-division multiplexing] and encodes data into small, fixed-sized {cell_relay}[cells]. This differs from other protocols such as the Internet Protocol Suite or Ethernet that use variable sized packets or {frame_relay}[frames]. ATM has similarities with both {circuit_switching}[circuit] and {packet_switching}[packet] switched networking. This makes it a good choice for a network that must handle both traditional high-throughput data traffic, and real-time, {latency_engineering}[low-latency] content such as voice and video. ATM uses a connection-oriented model in which a {virtual_circuit}[virtual circuit] must be established between two endpoints before the actual data exchange begins.

While the role of ATM is diminishing in favor of {next_generation_networks}[next-generation networks], it still plays a role in the {last_mile}[last mile], which is the connection between an {internet_service_provider}[Internet service provider] and the home user. 

===== Cellular standards

:global_system_for_mobile_communications: https://en.wikipedia.org/wiki/Global_System_for_Mobile_Communications
:cdma2000: https://en.wikipedia.org/wiki/CDMA2000

There are a number of different digital cellular standards, including: {global_system_for_mobile_communications}[Global System for Mobile Communications] (GSM), General Packet Radio Service (GPRS), CDMAOne, {cdma2000}[CDMA2000], Evolution-Data Optimized (EV-DO), Enhanced Data Rates for GSM Evolution (EDGE), Universal Mobile Telecommunications System (UMTS), Digital Enhanced Cordless Telecommunications (DECT), Digital AMPS (IS-136/TDMA), and Integrated Digital Enhanced Network (iDEN).

==== Routing

:routing: https://en.wikipedia.org/wiki/Routing
:packet_forwarding: https://en.wikipedia.org/wiki/Packet_forwarding
:network_packet: https://en.wikipedia.org/wiki/Network_packet
:router_computing: https://en.wikipedia.org/wiki/Router_(computing)
:bridging_networking: https://en.wikipedia.org/wiki/Bridging_(networking)
:gateway_telecommunications: https://en.wikipedia.org/wiki/Gateway_(telecommunications)
:firewall_computing: https://en.wikipedia.org/wiki/Firewall_(computing)
:network_switch: https://en.wikipedia.org/wiki/Network_switch
:routing_table: https://en.wikipedia.org/wiki/Routing_table
:multipath_routing: https://en.wikipedia.org/wiki/Multipath_routing
:administrative_distance: https://en.wikipedia.org/wiki/Administrative_distance

{routing}[Routing] is the process of selecting network paths to carry network traffic. Routing is performed for many kinds of networks, including {circuit_switching}[circuit switching] networks and {packet_switching}[packet switched networks].

In packet-switched networks, routing protocols direct {packet_forwarding}[packet forwarding] (the transit of logically addressed {network_packet}[network packets] from their source toward their ultimate destination) through intermediate nodes. Intermediate nodes are typically network hardware devices such as {router_computing}[routers], {bridging_networking}[bridges], {gateway_telecommunications}[gateways], {firewall_computing}[firewalls], or {network_switch}[switches]. General-purpose computers can also forward packets and perform routing, though they are not specialized hardware and may suffer from the limited performance. The routing process usually directs forwarding on the basis of routing tables, which maintain a record of the routes to various network destinations. Thus, constructing routing tables, which are held in the router's memory, is very important for efficient routing.

There are usually multiple routes that can be taken, and to choose between them, different elements can be considered to decide which routes get installed into the routing table, such as (sorted by priority):

* Prefix-Length: where longer subnet masks are preferred (independent if it is within a routing protocol or over a different routing protocol)
* Metric: where a lower metric/cost is preferred (only valid within one and the same routing protocol)
* {administrative_distance}[Administrative distance]: where a lower distance is preferred (only valid between different routing protocols)

Most routing algorithms use only one network path at a time. {multipath_routing}[Multipath routing] techniques enable the use of multiple alternative paths.

Routing, in a more narrow sense of the term, is often contrasted with bridging in its assumption that network addresses are structured and that similar addresses imply proximity within the network. Structured addresses allow a single routing table entry to represent the route to a group of devices. In large networks, structured addressing (routing, in the narrow sense) outperforms unstructured addressing (bridging). Routing has become the dominant form of addressing on the Internet. Bridging is still widely used within localized environments. 

=== Geographic Scale

Networks may be characterized by many properties or features, such as physical capacity, organizational purpose, user authorization, access rights, and others. Another distinct classification method is that of the physical extent or geographic scale.

==== Nanoscale network

:ieee_p1906_1: https://en.wikipedia.org/wiki/IEEE_P1906.1

A {ieee_p1906_1}[nanoscale communication] network has key components implemented at the nanoscale including message carriers and leverages physical principles that differ from macroscale communication mechanisms. Nanoscale communication extends communication to very small sensors and actuators such as those found in biological systems and also tends to operate in environments that would be too harsh for classical communication.

==== Personal area network

:personal_area_network: https://en.wikipedia.org/wiki/Personal_area_network

A {personal_area_network}[personal area network] (PAN) is a computer network used for communication among computers and different information technological devices close to one person. Some examples of devices that are used in a PAN are personal computers, printers, fax machines, telephones, PDAs, scanners, and even video game consoles. A PAN may include wired and wireless devices. The reach of a PAN typically extends to 10 meters. A wired PAN is usually constructed with USB and FireWire connections while technologies such as Bluetooth and infrared communication typically form a wireless PAN.

==== Local area network

:local_area_network: https://en.wikipedia.org/wiki/Local_area_network
:wide_area_network: https://en.wikipedia.org/wiki/Wide_area_network
:bandwidth_computing: https://en.wikipedia.org/wiki/Bandwidth_(computing)
:leased_line: https://en.wikipedia.org/wiki/Leased_line
:router_computing: https://en.wikipedia.org/wiki/Router_(computing)

A {local_area_network}[local area network] (LAN) is a network that connects computers and devices in a limited geographical area such as a home, school, office building, or closely positioned group of buildings. Each computer or device on the network is a node. Wired LANs are most likely based on Ethernet technology. Newer standards such as ITU-T G.hn also provide a way to create a wired LAN using existing wiring, such as coaxial cables, telephone lines, and power lines.

The defining characteristics of a LAN, in contrast to a {wide_area_network}[wide area network] (WAN), include higher {bandwidth_computing}[data transfer rates], limited geographic range, and lack of reliance on {leased_line}[leased lines] to provide connectivity. Current Ethernet or other IEEE 802.3 LAN technologies operate at data transfer rates up to 100 Gbit/s, standardized by IEEE in 2010.[42] Currently, 400 Gbit/s Ethernet is being developed.

A LAN can be connected to a WAN using a {router_computing}[router].

==== Home area network

:home_area_network: https://en.wikipedia.org/wiki/Home_area_network
:digital_subscriber_line: https://en.wikipedia.org/wiki/Digital_subscriber_line

A {home_area_network}[home area network] (HAN) is a residential LAN used for communication between digital devices typically deployed in the home, usually a small number of personal computers and accessories, such as printers and mobile computing devices. An important function is the sharing of Internet access, often a broadband service through a cable TV or {digital_subscriber_line}[digital subscriber line] (DSL) provider.

==== Storage area network

:storage_area_network: https://en.wikipedia.org/wiki/Storage_area_network

A {storage_area_network}[storage area network] (SAN) is a dedicated network that provides access to consolidated, block-level data storage. SANs are primarily used to make storage devices, such as disk arrays, tape libraries, and optical jukeboxes, accessible to servers so that the devices appear like locally attached devices to the operating system. A SAN typically has its own network of storage devices that are generally not accessible through the local area network by other devices. The cost and complexity of SANs dropped in the early 2000s to levels allowing wider adoption across both enterprise and small to medium-sized business environments.

==== Campus area network

:campus_area_network: https://en.wikipedia.org/wiki/Campus_area_network
:category_5_cable: https://en.wikipedia.org/wiki/Category_5_cable

A {campus_area_network}[campus area network] (CAN) is made up of an interconnection of LANs within a limited geographical area. The networking equipment (switches, routers) and transmission media (optical fiber, copper plant, {category_5_cable}[Cat5] cabling, etc.) are almost entirely owned by the campus tenant/owner (an enterprise, university, government, etc.).

For example, a university campus network is likely to link a variety of campus buildings to connect academic colleges or departments, the library, and student residence halls.

==== Backbone network

:backbone_network: https://en.wikipedia.org/wiki/Backbone_network
:network_performance_management: https://en.wikipedia.org/wiki/Network_performance_management
:network_congestion: https://en.wikipedia.org/wiki/Network_congestion
:internet_backbone: https://en.wikipedia.org/wiki/Internet_backbone

A {backbone_network}[backbone network] is part of a computer network infrastructure that provides a path for the exchange of information between different LANs or subnetworks. A backbone can tie together diverse networks within the same building, across different buildings, or over a wide area.

For example, a large company might implement a backbone network to connect departments that are located around the world. The equipment that ties together the departmental networks constitutes the network backbone. When designing a network backbone, {network_performance_management}[network performance] and {network_congestion}[network congestion] are critical factors to take into account. Normally, the backbone network's capacity is greater than that of the individual networks connected to it.

Another example of a backbone network is the {internet_backbone}[Internet backbone], which is a massive, global system of fiber-optic cable and optical networking that carry the bulk of data between wide area networks (WANs), metro, regional, national and transoceanic networks.

==== Metropolitan area network

:metropolitan_area_network: https://en.wikipedia.org/wiki/Metropolitan_area_network

A {metropolitan_area_network}[metropolitan area network] (MAN) is a large computer network that usually spans a city or a large campus.

==== Wide area network

:wide_area_network: https://en.wikipedia.org/wiki/Wide_area_network

A {wide_area_network}[wide area network] (WAN) is a computer network that covers a large geographic area such as a city, country, or spans even intercontinental distances. A WAN uses a communications channel that combines many types of media such as telephone lines, cables, and airwaves. A WAN often makes use of transmission facilities provided by common carriers, such as telephone companies. WAN technologies generally function at the lower three layers of the OSI reference model: the physical layer, the data link layer, and the network layer.

==== Enterprise private network

:enterprise_private_network: https://en.wikipedia.org/wiki/Enterprise_private_network

An {enterprise_private_network}[enterprise private network] is a network that a single organization builds to interconnect its office locations (e.g., production sites, head offices, remote offices, shops) so they can share computer resources.

==== Virtual private network

:virtual_private_network: https://en.wikipedia.org/wiki/Virtual_private_network

A {virtual_private_network}[virtual private network] (VPN) is an overlay network in which some of the links between nodes are carried by open connections or virtual circuits in some larger network (e.g., the Internet) instead of by physical wires. The data link layer protocols of the virtual network are said to be tunneled through the larger network when this is the case. One common application is secure communications through the public Internet, but a VPN need not have explicit security features, such as authentication or content encryption. VPNs, for example, can be used to separate the traffic of different user communities over an underlying network with strong security features.

VPN may have best-effort performance or may have a defined service level agreement (SLA) between the VPN customer and the VPN service provider. Generally, a VPN has a topology more complex than point-to-point.

==== Global area network

:global_area_network: https://en.wikipedia.org/wiki/Global_area_network

A {global_area_network}[global area network] (GAN) is a network used for supporting mobile across an arbitrary number of wireless LANs, satellite coverage areas, etc. The key challenge in mobile communications is handing off user communications from one local coverage area to the next. In IEEE Project 802, this involves a succession of terrestrial wireless LANs.

=== Organizational scope

Networks are typically managed by the organizations that own them. Private enterprise networks may use a combination of intranets and extranets. They may also provide network access to the Internet, which has no single owner and permits virtually unlimited global connectivity. 

:intranet: https://en.wikipedia.org/wiki/Intranet
:extranet: https://en.wikipedia.org/wiki/Extranet

==== Intranet

An {intranet}[intranet] is a set of networks that are under the control of a single administrative entity. The intranet uses the IP protocol and IP-based tools such as web browsers and file transfer applications. The administrative entity limits the use of the intranet to its authorized users. Most commonly, an intranet is the internal LAN of an organization. A large intranet typically has at least one web server to provide users with organizational information. An intranet is also anything behind the router on a local area network.

==== Extranet

An {extranet}[extranet] is a network that is also under the administrative control of a single organization but supports a limited connection to a specific external network. For example, an organization may provide access to some aspects of its intranet to share data with its business partners or customers. These other entities are not necessarily trusted from a security standpoint. Network connection to an extranet is often, but not always, implemented via WAN technology. 

==== Internet

:internetwork: https://en.wikipedia.org/wiki/Internetwork
:internet: https://en.wikipedia.org/wiki/Internet
:internet_protocol_suite: https://en.wikipedia.org/wiki/Internet_Protocol_Suite
:arpanet: https://en.wikipedia.org/wiki/ARPANET
:defense_advanced_research_projects_agency: https://en.wikipedia.org/wiki/Defense_Advanced_Research_Projects_Agency
:united_states_department_of_defense: https://en.wikipedia.org/wiki/United_States_Department_of_Defense
:optical_networking: https://en.wikipedia.org/wiki/Optical_networking
:world_wide_web: https://en.wikipedia.org/wiki/World_Wide_Web
:internet_of_things: https://en.wikipedia.org/wiki/Internet_of_things
:ip_address: https://en.wikipedia.org/wiki/IP_address
:internet_assigned_numbers_authority: https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority
:regional_internet_registry: https://en.wikipedia.org/wiki/Regional_Internet_registry
:routing: https://en.wikipedia.org/wiki/Routing
:border_gateway_protocol: https://en.wikipedia.org/wiki/Border_Gateway_Protocol

An {internetwork}[internetwork] is the connection of multiple different types of computer networks to form a single computer network by layering on top of the different networking software and connecting them together using routers. 

The {internet}[Internet] is the largest example of internetwork. It is a global system of interconnected governmental, academic, corporate, public, and private computer networks. It is based on the networking technologies of the {internet_protocol_suite}[Internet Protocol Suite]. It is the successor of the {arpanet}[Advanced Research Projects Agency Network] (ARPANET) developed by {defense_advanced_research_projects_agency}[DARPA] of the {united_states_department_of_defense}[United States Department of Defense]. The Internet utilizes copper communications and the {optical_networking}[optical networking] backbone to enable the {world_wide_web}[World Wide Web] (WWW), the {internet_of_things}[Internet of Things], video transfer, and a broad range of information services.

Participants on the Internet use a diverse array of methods of several hundred documented, and often standardized, protocols compatible with the Internet Protocol Suite and an addressing system ({ip_address}[IP addresses]) administered by the {internet_assigned_numbers_authority}[Internet Assigned Numbers Authority] and {regional_internet_registry}[address registries]. Service providers and large enterprises exchange information about the {routing}[reachability] of their address spaces through the {border_gateway_protocol}[Border Gateway Protocol] (BGP), forming a redundant worldwide mesh of transmission paths. 

==== Darknet

:darknet: https://en.wikipedia.org/wiki/Darknet
:communications_protocol: https://en.wikipedia.org/wiki/Communications_protocol
:port_computer_networking: https://en.wikipedia.org/wiki/Port_(computer_networking)
:peer-to-peer: https://en.wikipedia.org/wiki/Peer-to-peer
:peer-to-peer_file_sharing: https://en.wikipedia.org/wiki/Peer-to-peer_file_sharing

A {darknet}[darknet] is an overlay network, typically running on the Internet, that is only accessible through specialized software. A darknet is an anonymizing network where connections are made only between trusted peers — sometimes called "friends" (F2F) — using non-standard {communications_protocol}[protocols] and {port_computer_networking}[ports].

Darknets are distinct from other distributed {peer-to-peer}[peer-to-peer] networks as {peer-to-peer_file_sharing}[sharing] is anonymous (that is, IP addresses are not publicly shared), and therefore users can communicate with little fear of governmental or corporate interference.

=== Network Service

:network_service: https://en.wikipedia.org/wiki/Network_service
:distributed_file_system: https://en.wikipedia.org/wiki/Distributed_file_system
:domain_name_system: https://en.wikipedia.org/wiki/Domain_Name_System
:internet_protocol: https://en.wikipedia.org/wiki/Internet_protocol
:mac_address: https://en.wikipedia.org/wiki/MAC_address
:dynamic_host_configuration_protocol: https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol
:protocol_computing: https://en.wikipedia.org/wiki/Protocol_(computing)

{network_service}[Network services] are applications hosted by servers on a computer network, to provide some functionality for members or users of the network, or to help the network itself to operate.

The World Wide Web, E-mail, printing and {distributed_file_system}[network file sharing] are examples of well-known network services. Network services such as DNS ({domain_name_system}[Domain Name System]) give names for {internet_protocol}[IP] and {mac_address}[MAC addresses] (people remember names like “nm.lan” better than numbers like “210.121.67.18”), and {dynamic_host_configuration_protocol}[DHCP] to ensure that the equipment on the network has a valid IP address.

Services are usually based on a {protocol_computing}[service protocol] that defines the format and sequencing of messages between clients and servers of that network service. 

=== Network Performance

==== Bandwidth

:throughput: https://en.wikipedia.org/wiki/Throughput
:goodput: https://en.wikipedia.org/wiki/Goodput
:bandwidth_shaping: https://en.wikipedia.org/wiki/Network_scheduler
:bandwidth_management: https://en.wikipedia.org/wiki/Bandwidth_management
:bandwidth_throttling: https://en.wikipedia.org/wiki/Bandwidth_throttling
:bandwidth_cap: https://en.wikipedia.org/wiki/Bandwidth_cap
:bandwidth_allocation: https://en.wikipedia.org/wiki/Bandwidth_allocation
:bandwidth_allocation_protocol: https://en.wikipedia.org/wiki/Bandwidth_allocation_protocol
:dynamic_bandwidth_allocation: https://en.wikipedia.org/wiki/Dynamic_bandwidth_allocation

Bandwidth in bit/s may refer to consumed bandwidth, corresponding to achieved 
{throughput}[throughput] or {goodput}[goodput], i.e., the average rate of successful data transfer through a communication path. The throughput is affected by technologies such as {bandwidth_shaping}[bandwidth shaping], {bandwidth_management}[bandwidth management], {bandwidth_throttling}[bandwidth throttling], {bandwidth_cap}[bandwidth cap], {bandwidth_allocation}[bandwidth allocation] (for example {bandwidth_allocation}[bandwidth allocation protocol] and {dynamic_bandwidth_allocation}[dynamic bandwidth allocation]), etc. A bit stream's bandwidth is proportional to the average consumed signal bandwidth in hertz (the average spectral bandwidth of the analog signal representing the bit stream) during a studied time interval. 

==== Network delay

:network_delay: https://en.wikipedia.org/wiki/Network_delay
:telecommunications_network: https://en.wikipedia.org/wiki/Telecommunications_network
:latency_engineering: https://en.wikipedia.org/wiki/Latency_(engineering)
:processing_delay: https://en.wikipedia.org/wiki/Processing_delay
:queuing_delay: https://en.wikipedia.org/wiki/Queuing_delay
:transmission_delay: https://en.wikipedia.org/wiki/Transmission_delay
:propagation_delay: https://en.wikipedia.org/wiki/Propagation_delay
:data_link: https://en.wikipedia.org/wiki/Data_link
:network_congestion: https://en.wikipedia.org/wiki/Network_congestion
:ip_network: https://en.wikipedia.org/wiki/IP_network

{network_delay}[Network delay] is a design and performance characteristic of a {telecommunications_network}[telecommunications network]. It specifies the {latency_engineering}[latency] for a bit of data to travel across the network from one communication endpoint to another. It is typically measured in multiples or fractions of a second. Delay may differ slightly, depending on the location of the specific pair of communicating endpoints. Engineers usually report both the maximum and average delay, and they divide the delay into several parts:

* {processing_delay}[Processing delay] – time it takes a router to process the packet header
* {queuing_delay}[Queuing delay] – time the packet spends in routing queues
* {transmission_delay}[Transmission delay] – time it takes to push the packet's bits onto the link
* {propagation_delay}[Propagation delay] – time for a signal to propagate through the media

A certain minimum level of delay is experienced by signals due to the time it takes to transmit a packet serially through a {data_link}[link]. This delay is extended by more variable levels of delay due to {network_congestion}[network congestion]. {ip_network}[IP network] delays can range from a few milliseconds to several hundred milliseconds. 

==== Quality of service

:network_performance: https://en.wikipedia.org/wiki/Network_performance
:quality_of_service: https://en.wikipedia.org/wiki/Quality_of_service
:throughput: https://en.wikipedia.org/wiki/Throughput
:jitter: https://en.wikipedia.org/wiki/Jitter
:bit_error_rate: https://en.wikipedia.org/wiki/Bit_error_rate
:latency_engineering: https://en.wikipedia.org/wiki/Latency_(engineering)
:grade_of_service: https://en.wikipedia.org/wiki/Grade_of_service
:state_diagram: https://en.wikipedia.org/wiki/State_diagram

Depending on the installation requirements, {network_performance}[network performance] is usually measured by the {quality_of_service}[quality of service] of a telecommunications product. The parameters that affect this typically can include {throughput}[throughput], {jitter}[jitter], {bit_error_rate}[bit error rate] and {latency_engineering}[latency].

The following list gives examples of network performance measures for a circuit-switched network and one type of packet-switched network, viz. ATM:

* Circuit-switched networks: In circuit switched networks, network performance is synonymous with the {grade_of_service}[grade of service]. The number of rejected calls is a measure of how well the network is performing under heavy traffic loads. Other types of performance measures can include the level of noise and echo.
* ATM: In an Asynchronous Transfer Mode (ATM) network, performance can be measured by line rate, quality of service (QoS), data throughput, connect time, stability, technology, modulation technique, and modem enhancements.

There are many ways to measure the performance of a network, as each network is different in nature and design. Performance can also be modeled instead of measured. For example, {state_diagram}[state transition diagrams] are often used to model queuing performance in a circuit-switched network. The network planner uses these diagrams to analyze how the network performs in each state, ensuring that the network is optimally designed.

==== Network congestion

:network_congestion: https://en.wikipedia.org/wiki/Network_congestion
:queueing_delay: https://en.wikipedia.org/wiki/queueing_delay
:packet_loss: https://en.wikipedia.org/wiki/Packet_loss
:blocking_probability: https://en.wikipedia.org/wiki/Blocking_probability
:offered_load: https://en.wikipedia.org/wiki/Offered_load
:network_protocol: https://en.wikipedia.org/wiki/Network_protocol
:retransmission_data_networks: https://en.wikipedia.org/wiki/Retransmission_(data_networks)
:congestion_control: https://en.wikipedia.org/wiki/Congestion_control
:congestion_avoidance: https://en.wikipedia.org/wiki/Congestion_avoidance
:network_traffic_control: https://en.wikipedia.org/wiki/Network_traffic_control
:exponential_backoff: https://en.wikipedia.org/wiki/Exponential_backoff
:sliding_window: https://en.wikipedia.org/wiki/Sliding_window
:transmission_control_protocol: https://en.wikipedia.org/wiki/Transmission_control_protocol
:fair_queueing: https://en.wikipedia.org/wiki/Fair_queueing
:router_computing: https://en.wikipedia.org/wiki/Router_(computing)
:local_area_network: https://en.wikipedia.org/wiki/Local_area_network
:rfc2914: https://datatracker.ietf.org/doc/html/rfc2914

{network_congestion}[Network congestion] occurs when a link or node is subjected to a greater data load than it is rated for, resulting in a deterioration of its {quality_of_service}[quality of service]. When networks are congested and queues become too full, packets have to be discarded, and so networks rely on {retransmission_data_networks}[re-transmission]. Typical effects of congestion include {queueing_delay}[queueing delay], {packet_loss}[packet loss] or the {blocking_probability}[blocking] of new connections. A consequence of these latter two is that incremental increases in {offered_load}[offered load] lead either to only a small increase in the network throughput or to a reduction in network throughput.

Network protocols that use aggressive {retransmission_data_networks}[retransmissions] to compensate for packet loss tend to keep systems in a state of network congestion—even after the initial load is reduced to a level that would not normally induce network congestion. Thus, networks using these protocols can exhibit two stable states under the same level of load. The stable state with low throughput is known as _congestive collapse_.

Modern networks use {congestion_control}[congestion control], {congestion_avoidance}[congestion avoidance] and {network_traffic_control}[traffic control] techniques to try to avoid congestion collapse (i.e. endpoints typically slow down or sometimes even stop transmission entirely when the network is congested). These techniques include: {exponential_backoff}[exponential backoff] in protocols such as 802.11's CSMA/CA and the original Ethernet, {sliding_window}[window] reduction in {transmission_control_protocol}[TCP], and {fair_queueing}[fair queueing] in devices such as {router_computing}[routers]. Another method to avoid the negative effects of network congestion is implementing priority schemes so that some packets are transmitted with higher priority than others. Priority schemes do not solve network congestion by themselves, but they help to alleviate the effects of congestion for some services. An example of this is 802.1p. A third method to avoid network congestion is the explicit allocation of network resources to specific flows. One example of this is the use of Contention-Free Transmission Opportunities (CFTXOPs) in the ITU-T G.hn standard, which provides high-speed (up to 1 Gbit/s) {local_area_network}[Local area networking] over existing home wires (power lines, phone lines and coaxial cables).

For the Internet, {rfc2914}[RFC 2914] addresses the subject of congestion control in detail. 

==== Network resilience

:resilience_network: https://en.wikipedia.org/wiki/Resilience_(network)
:service_systems_architecture: https://en.wikipedia.org/wiki/Service_(systems_architecture)
:fault_technology: https://en.wikipedia.org/wiki/Fault_(technology)

{resilience_network}[Network resilience] is "the ability to provide and maintain an acceptable level of {service_systems_architecture}[service] in the face of {fault_technology}[faults] and challenges to normal operation.

=== Security

:security_hacker: https://en.wikipedia.org/wiki/Security_hacker
:computer_virus: https://en.wikipedia.org/wiki/Computer_virus
:computer_worm: https://en.wikipedia.org/wiki/Computer_worm
:denial-of-service_attack: https://en.wikipedia.org/wiki/Denial-of-service_attack

Computer networks are also used by {security_hacker}[security hackers] to deploy {computer_virus}[computer viruses] or {computer_worm}[computer worms] on devices connected to the network, or to prevent these devices from accessing the network via a {denial-of-service_attack}[denial-of-service attack]. 

==== Network security

:network_security: https://en.wikipedia.org/wiki/Network_Security
:network_administrator: https://en.wikipedia.org/wiki/Network_administrator
:unauthorized: https://en.wikipedia.org/wiki/Unauthorized

{network_security}[Network Security] consists of provisions and policies adopted by the {network_administrator}[network administrator] to prevent and monitor {unauthorized}[unauthorized] access, misuse, modification, or denial of the computer network and its network-accessible resources.[53] Network security is the authorization of access to data in a network, which is controlled by the network administrator. Users are assigned an ID and password that allows them access to information and programs within their authority. Network security is used on a variety of computer networks, both public and private, to secure daily transactions and communications among businesses, government agencies, and individuals.

==== Network surveillance

:network_surveillance: https://en.wikipedia.org/wiki/Network_surveillance

{network_surveillance}[Network surveillance] is the monitoring of data being transferred over computer networks such as the Internet. The monitoring is often done surreptitiously and may be done by or at the behest of governments, by corporations, criminal organizations, or individuals. It may or may not be legal and may or may not require authorization from a court or other independent agency.

Computer and network surveillance programs are widespread today, and almost all Internet traffic is or could potentially be monitored for clues to illegal activity.

Surveillance is very useful to governments and law enforcement to maintain social control, recognize and monitor threats, and prevent/investigate criminal activity. With the advent of programs such as the Total Information Awareness program, technologies such as high-speed surveillance computers and biometrics software, and laws such as the Communications Assistance For Law Enforcement Act, governments now possess an unprecedented ability to monitor the activities of citizens.

However, many civil rights and privacy groups—such as Reporters Without Borders, the Electronic Frontier Foundation, and the American Civil Liberties Union—have expressed concern that increasing surveillance of citizens may lead to a mass surveillance society, with limited political and personal freedoms. Fears such as this have led to numerous lawsuits such as Hepting v. AT&T. The hacktivist group Anonymous has hacked into government websites in protest of what it considers "draconian surveillance".

==== End to end encryption

:end-to-end_encryption: https://en.wikipedia.org/wiki/End-to-end_encryption
:digital_communications: https://en.wikipedia.org/wiki/Digital_communications
:encryption: https://en.wikipedia.org/wiki/Encryption
:internet_providers: https://en.wikipedia.org/wiki/Internet_providers
:application_service_provider: https://en.wikipedia.org/wiki/Application_service_provider
:confidentiality: https://en.wikipedia.org/wiki/Confidentiality
:data_integrity: https://en.wikipedia.org/wiki/Data_integrity
:https: https://en.wikipedia.org/wiki/HTTPS
:pretty_good_privacy: https://en.wikipedia.org/wiki/Pretty_Good_Privacy
:off-the-record_messaging: https://en.wikipedia.org/wiki/Off-the-Record_Messaging
:zrtp: https://en.wikipedia.org/wiki/ZRTP
:terrestrial_trunked_radio: https://en.wikipedia.org/wiki/Terrestrial_Trunked_Radio
:backdoor_computing: https://en.wikipedia.org/wiki/Backdoor_(computing)
:encryption_key: https://en.wikipedia.org/wiki/Encryption_key
:exploit_computer_security: https://en.wikipedia.org/wiki/Exploit_(computer_security)
:random_number_generator: https://en.wikipedia.org/wiki/Random_number_generator
:key_escrow: https://en.wikipedia.org/wiki/Key_escrow
:traffic_analysis: https://en.wikipedia.org/wiki/Traffic_analysis

{end-to-end_encryption}[End-to-end encryption] (E2EE) is a {end-to-end_encryption}[digital communications] paradigm of uninterrupted protection of data traveling between two communicating parties. It involves the originating party encrypting data so only the intended recipient can decrypt it, with no dependency on third parties. End-to-end encryption prevents intermediaries, such as Internet providers or application service providers, from discovering or tampering with communications. End-to-end encryption generally protects both confidentiality and integrity.

Examples of end-to-end encryption include HTTPS for web traffic, PGP for email, OTR for instant messaging, ZRTP for telephony, and TETRA for radio.

Typical server-based communications systems do not include end-to-end encryption. These systems can only guarantee the protection of communications between clients and servers, not between the communicating parties themselves. Examples of non-E2EE systems are Google Talk, Yahoo Messenger, Facebook, and Dropbox. Some such systems, for example, LavaBit and SecretInk, have even described themselves as offering "end-to-end" encryption when they do not. Some systems that normally offer end-to-end encryption have turned out to contain a back door that subverts negotiation of the encryption key between the communicating parties, for example Skype or Hushmail.

The end-to-end encryption paradigm does not directly address risks at the endpoints of the communication themselves, such as the technical exploitation of clients, poor quality random number generators, or key escrow. E2EE also does not address traffic analysis, which relates to things such as the identities of the endpoints and the times and quantities of messages that are sent.

==== SSL/TLS

The introduction and rapid growth of e-commerce on the World Wide Web in the mid-1990s made it obvious that some form of authentication and encryption was needed. Netscape took the first shot at a new standard. At the time, the dominant web browser was Netscape Navigator. Netscape created a standard called secure socket layer (SSL). SSL requires a server with a certificate. When a client requests access to an SSL-secured server, the server sends a copy of the certificate to the client. The SSL client checks this certificate (all web browsers come with an exhaustive list of CA root certificates preloaded), and if the certificate checks out, the server is authenticated and the client negotiates a symmetric-key cipher for use in the session. The session is now in a very secure encrypted tunnel between the SSL server and the SSL client.

== References

* https://en.wikipedia.org/wiki/Computer_network
* https://en.wikipedia.org/wiki/Traceroute
* https://en.wikipedia.org/wiki/Layer_four_traceroute
* https://en.wikipedia.org/wiki/MTR_(software)
* https://en.wikipedia.org/wiki/Time_to_live
* https://en.wikipedia.org/wiki/Latency_(engineering)
