= Internet Protocol Suite (TCP/IP)
:page-layout: post
:page-categories: ['tcp/ip']
:page-tags: ['tcp/ip']
:revdate: 2021-10-03 14:40:21 +0800
:sectnums:
:toc:

:transmission_control_protocol: https://en.wikipedia.org/wiki/Transmission_Control_Protocol
:internet_protocol: https://en.wikipedia.org/wiki/Internet_Protocol
:link_layer: https://en.wikipedia.org/wiki/Link_layer
:internet_layer: https://en.wikipedia.org/wiki/Internet_layer
:transport_layer: https://en.wikipedia.org/wiki/Transport_layer
:application_layer: https://en.wikipedia.org/wiki/Application_layer

The *Internet protocol suite*, commonly known as *TCP/IP*, is the set of communications protocols used in the Internet and similar computer networks. The current foundational protocols in the suite are the Transmission Control Protocol (TCP) and the Internet Protocol (IP).

The Internet protocol suite provides *end-to-end* data communication specifying how data should be packetized, addressed, transmitted, routed, and received. This functionality is organized into four abstraction layers, which classify all related protocols according to each protocol's scope of networking. From lowest to highest, the layers are the {link_layer}[*link layer*], containing communication methods for data that remains within a single network segment (link); the {internet_layer}[*internet layer*], providing internetworking between independent networks; the {transport_layer}[*transport layer*], handling host-to-host communication; and the {application_layer}[*application layer*], providing *process-to-process* data exchange for applications.

image::/assets/computer-network/IP_stack_connections.svg[50%,50%,title="Conceptual data flow in a simple network topology of two hosts (A and B) connected by a link between their respective routers. The application on each host executes read and write operations as if the processes were directly connected to each other by some kind of data pipe. After establishment of this pipe, most details of the communication are hidden from each process, as the underlying principles of communication are implemented in the lower protocol layers. In analogy, at the transport layer the communication appears as host-to-host, without knowledge of the application data structures and the connecting routers, while at the internetworking layer, individual network boundaries are traversed at each router."]

image::/assets/computer-network/UDP_encapsulation.svg[50%,50%,title="Encapsulation of application data descending through the layers described in RFC 1122"]

== Link layer

:virtual_private_network: https://en.wikipedia.org/wiki/Virtual_private_network
:tunneling_protocol: https://en.wikipedia.org/wiki/Tunneling_protocol
:device_driver: https://en.wikipedia.org/wiki/Device_driver
:network_card: https://en.wikipedia.org/wiki/Network_card
:firmware: https://en.wikipedia.org/wiki/Firmware
:chipsets: https://en.wikipedia.org/wiki/Chipsets
:physical_layer: https://en.wikipedia.org/wiki/Physical_layer
:transmission_medium: https://en.wikipedia.org/wiki/Transmission_medium
:media_access_control: https://en.wikipedia.org/wiki/Media_access_control

The protocols of the {link_layer}[link layer] operate within the scope of the local network connection to which a host is attached. This regime is called the link in TCP/IP parlance and is the lowest component layer of the suite. *The link includes all hosts accessible without traversing a router*. The size of the link is therefore determined by the networking hardware design. In principle, TCP/IP is designed to be *hardware independent* and may be implemented on top of virtually any link-layer technology. This includes not only hardware implementations, but also virtual link layers such as {virtual_private_network}[virtual private networks] and {tunneling_protocol}[networking tunnels].

The link layer is used to move packets between the Internet layer interfaces of two different hosts on the same link. The processes of transmitting and receiving packets on the link can be controlled in the {device_driver}[device driver] for the {network_card}[network card], as well as in {firmware}[firmware] or by specialized {chipsets}[chipsets]. These perform functions, such as framing, to prepare the Internet layer packets for transmission, and finally transmit the frames to the {physical_layer}[physical layer] and over a {transmission_medium}[transmission medium]. The TCP/IP model includes specifications for translating the network addressing methods used in the Internet Protocol to link-layer addresses, such as {media_access_control}[media access control] (MAC) addresses. All other aspects below that level, however, are implicitly assumed to exist, and are not explicitly defined in the TCP/IP model.

The link layer in the TCP/IP model has corresponding functions in Layer 2 of the OSI model. 

== Internet layer

:internetworking: https://en.wikipedia.org/wiki/Internetworking
:routing: https://en.wikipedia.org/wiki/Routing
:ip_address: https://en.wikipedia.org/wiki/IP_address
:internet_layer: https://en.wikipedia.org/wiki/Internet_layer
:upper_layer_protocol: https://en.wikipedia.org/wiki/Upper_layer_protocol
:list_of_ip_protocol_numbers: https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers
:internet_control_message_protocol: https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol
:internet_group_management_protocol: https://en.wikipedia.org/wiki/Internet_Group_Management_Protocol
:ipv4: https://en.wikipedia.org/wiki/IPv4
:ipv6: https://en.wikipedia.org/wiki/IPv6

{internetworking}[Internetworking] requires sending data from the source network to the destination network. This process is called {routing}[routing] and is supported by host addressing and identification using the hierarchical {ip_address}[IP addressing] system. The {internet_layer}[internet layer] provides an unreliable datagram transmission facility between hosts located on potentially different IP networks by forwarding datagrams to an appropriate next-hop router for further relaying to its destination. The internet layer has the responsibility of sending packets across potentially multiple networks. With this functionality, the internet layer makes possible internetworking, the interworking of different IP networks, and it essentially establishes the Internet.

The internet layer does not distinguish between the various transport layer protocols. IP carries data for a variety of different {upper_layer_protocol}[upper layer protocols]. These protocols are each identified by a unique {list_of_ip_protocol_numbers}[protocol number]: for example, {internet_control_message_protocol}[Internet Control Message Protocol] (ICMP) and {internet_group_management_protocol}[Internet Group Management Protocol] (IGMP) are protocols 1 and 2, respectively.

.IP protocol numbers
[%header, cols='1,2,2,4']
|====
|Hex
|Protocol Number
|Keyword
|Protocol
|0x01 	
|1
|ICMP
|Internet Control Message Protocol

|0x02
|2
|IGMP
|Internet Group Management Protocol

|0x06
|6
|TCP|Transmission Control Protocol

|0x11
|17
|UDP
|User Datagram Protocol

|0x3A
|58
|IPv6-ICMP
|ICMP for IPv6

|====

The Internet Protocol is the principal component of the internet layer, and it defines two addressing systems to identify network hosts and to locate them on the network. The original address system of the ARPANET and its successor, the Internet, is {ipv4}[Internet Protocol version 4] (IPv4). It uses a 32-bit IP address and is therefore capable of identifying approximately four billion hosts. This limitation was eliminated in 1998 by the standardization of {ipv6}[Internet Protocol version 6] (IPv6) which uses 128-bit addresses. IPv6 production implementations emerged in approximately 2006. 

== Transport layer

:transport_layer: https://en.wikipedia.org/wiki/Transport_layer
:connection-oriented: https://en.wikipedia.org/wiki/Connection-oriented
:connectionless: https://en.wikipedia.org/wiki/Connectionless
:error_detection_and_correction: https://en.wikipedia.org/wiki/Error_detection_and_correction
:network_segmentation: https://en.wikipedia.org/wiki/Network_segmentation
:flow_control_data: https://en.wikipedia.org/wiki/Flow_control_(data)
:network_congestion: https://en.wikipedia.org/wiki/Network_congestion
:port_computer_networking: https://en.wikipedia.org/wiki/Port_(computer_networking)
:network_port: https://en.wikipedia.org/wiki/Network_port
:service_discovery: https://en.wikipedia.org/wiki/Service_discovery
:directory_service: https://en.wikipedia.org/wiki/Directory_service
:best-effort_delivery: https://en.wikipedia.org/wiki/Best-effort_delivery
:transmission_control_protocol: https://en.wikipedia.org/wiki/Transmission_Control_Protocol
:reliable_byte_stream: https://en.wikipedia.org/wiki/Reliable_byte_stream
:stream_control_transmission_protocol: https://en.wikipedia.org/wiki/Stream_Control_Transmission_Protocol
:multihoming: https://en.wikipedia.org/wiki/Multihoming
:high-level_data_link_control: https://en.wikipedia.org/wiki/High-Level_Data_Link_Control
:user_datagram_protocol: https://en.wikipedia.org/wiki/User_Datagram_Protocol
:datagram: https://en.wikipedia.org/wiki/Datagram
:error_detection: https://en.wikipedia.org/wiki/Error_detection
:voice_over_ip: https://en.wikipedia.org/wiki/Voice_over_IP
:domain_name_system: https://en.wikipedia.org/wiki/Domain_Name_System
:real-time_transport_protocol: https://en.wikipedia.org/wiki/Real-time_Transport_Protocol
:streaming_media: https://en.wikipedia.org/wiki/Streaming_media
:list_of_tcp_and_udp_port_numbers: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

The {transport_layer}[transport layer] establishes basic data channels that applications use for task-specific data exchange. The layer establishes host-to-host connectivity in the form of end-to-end message transfer services that are independent of the underlying network and independent of the structure of user data and the logistics of exchanging information. Connectivity at the transport layer can be categorized as either {connection-oriented}[connection-oriented], implemented in TCP, or {connectionless}[connectionless], implemented in UDP. The protocols in this layer may provide {error_detection_and_correction}[error control], {network_segmentation}[segmentation], {flow_control_data}[flow control], {network_congestion}[congestion control], and application addressing ({port_computer_networking}[port numbers]).

For the purpose of providing process-specific transmission channels for applications, the layer establishes the concept of the {network_port}[network port]. This is a numbered logical construct allocated specifically for each of the communication channels an application needs. For many types of services, these port numbers have been standardized so that client computers may address specific services of a server computer without the involvement of {service_discovery}[service discovery] or {directory_service}[directory services].

Because IP provides only a {best-effort_delivery}[best-effort delivery], some transport-layer protocols offer reliability.

{transmission_control_protocol}[TCP] is a connection-oriented protocol that addresses numerous reliability issues in providing a {reliable_byte_stream}[reliable byte stream]:

* data arrives in-order
* data has minimal error (i.e., correctness)
* duplicate data is discarded
* lost or discarded packets are resent
* includes traffic congestion control

The newer {stream_control_transmission_protocol}[Stream Control Transmission Protocol] (SCTP) is also a reliable, connection-oriented transport mechanism. It is message-stream-oriented, not byte-stream-oriented like TCP, and provides multiple streams multiplexed over a single connection. It also provides {multihoming}[multihoming] support, in which a connection end can be represented by multiple IP addresses (representing multiple physical interfaces), such that if one fails, the connection is not interrupted. It was developed initially for telephony applications (to transport SS7 over IP).

Reliability can also be achieved by running IP over a reliable data-link protocol such as the {high-level_data_link_control}[High-Level Data Link Control] (HDLC).

The {user_datagram_protocol}[User Datagram Protocol] (UDP) is a connectionless {datagram}[datagram] protocol. Like IP, it is a best-effort, unreliable protocol. Reliability is addressed through {error_detection}[error detection] using a checksum algorithm. UDP is typically used for applications such as streaming media (audio, video, {voice_over_ip}[Voice over IP] etc.) where on-time arrival is more important than reliability, or for simple query/response applications like {domain_name_system}[DNS] lookups, where the overhead of setting up a reliable connection is disproportionately large. {real-time_transport_protocol}[Real-time Transport Protocol] (RTP) is a datagram protocol that is used over UDP and is designed for real-time data such as {streaming_media}[streaming media].

The applications at any given network address are distinguished by their TCP or UDP port. By convention, certain {list_of_tcp_and_udp_port_numbers}[well known ports] are associated with specific applications.

The TCP/IP model's transport or host-to-host layer corresponds roughly to the fourth layer in the OSI model, also called the transport layer. 

== Application layer

:application_layer: https://en.wikipedia.org/wiki/Application_layer
:routing_protocol: https://en.wikipedia.org/wiki/Routing_protocol
:hypertext_transfer_protocol: https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol
:file_transfer_protocol: https://en.wikipedia.org/wiki/File_Transfer_Protocol
:simple_mail_transfer_protocol: https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol
:dynamic_host_configuration_protocol: https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol
:encapsulation_networking: https://en.wikipedia.org/wiki/Encapsulation_(networking)
:lower_layer_protocol: https://en.wikipedia.org/wiki/Lower_layer_protocol
:library_computing: https://en.wikipedia.org/wiki/Library_(computing)
:application_programming_interface: https://en.wikipedia.org/wiki/Application_programming_interface
:internet_assigned_numbers_authority: https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority
:telnet: https://en.wikipedia.org/wiki/Telnet
:ephemeral_port: https://en.wikipedia.org/wiki/Ephemeral_port
:black_box: https://en.wikipedia.org/wiki/Black_box
:firewall_computing: https://en.wikipedia.org/wiki/Firewall_(computing)
:bandwidth_throttling: https://en.wikipedia.org/wiki/Bandwidth_throttling
:deep_packet_inspection: https://en.wikipedia.org/wiki/Deep_packet_inspection
:resource_reservation_protocol: https://en.wikipedia.org/wiki/Resource_Reservation_Protocol

The {application_layer}[application layer] includes the protocols used by most applications for providing user services or exchanging application data over the network connections established by the lower level protocols. This may include some basic network support services such as {routing_protocol}[routing protocols] and host configuration. Examples of application layer protocols include the {hypertext_transfer_protocol}[Hypertext Transfer Protocol] (HTTP), the {file_transfer_protocol}[File Transfer Protocol] (FTP), the {simple_mail_transfer_protocol}[Simple Mail Transfer Protocol] (SMTP), and the {dynamic_host_configuration_protocol}[Dynamic Host Configuration Protocol] (DHCP). Data coded according to application layer protocols are {encapsulation_networking}[encapsulated] into transport layer protocol units (such as TCP streams or UDP datagrams), which in turn use {lower_layer_protocol}[lower layer protocols] to effect actual data transfer.

The TCP/IP model does not consider the specifics of formatting and presenting data and does not define additional layers between the application and transport layers as in the OSI model (presentation and session layers). According to the TCP/IP model, such functions are the realm of {library_computing}[libraries] and {application_programming_interface}[application programming interfaces]. The application layer in the TCP/IP model is often compared to a combination of the fifth (session), sixth (presentation), and seventh (application) layers of the OSI model.

Application layer protocols are often associated with particular client–server applications, and common services have 
well-known port numbers reserved by the 
{internet_assigned_numbers_authority}[Internet Assigned Numbers Authority] (IANA). For example, the HyperText Transfer Protocol uses server port 80 and {telnet}[Telnet] uses server port 23. Clients connecting to a service usually use {ephemeral_port}[ephemeral ports], i.e., port numbers assigned only for the duration of the transaction at random or from a specific range configured in the application.

At the application layer, the TCP/IP model distinguishes between user protocols and support protocols. Support protocols provide services to a system of network infrastructure. User protocols are used for actual user applications. For example, FTP is a user protocol and DNS is a support protocol.

Although the applications are usually aware of key qualities of the transport layer connection such as the endpoint IP addresses and port numbers, application layer protocols generally treat the transport layer (and lower) protocols as 
{black_box}[black boxes] which provide a stable network connection across which to communicate. The transport layer and lower-level layers are unconcerned with the specifics of application layer protocols. Routers and switches do not typically examine the encapsulated traffic, rather they just provide a conduit for it. However, some {firewall_computing}[firewall] and {bandwidth_throttling}[bandwidth throttling] applications use {deep_packet_inspection}[deep packet inspection] to interpret application data. An example is the {resource_reservation_protocol}[Resource Reservation Protocol] (RSVP). It is also sometimes necessary for Applications affected by NAT to consider the application payload. 
