= Computer Network
:page-layout: post
:page-categories: []
:page-tags: []
:revdate: 2021-09-25 20:10:24 +0800
:toc:
:toclevels: 4

:computer: https://en.wikipedia.org/wiki/Computer
:node_networking: https://en.wikipedia.org/wiki/Node_(networking)
:communication_protocol: https://en.wikipedia.org/wiki/Communication_protocol
:digital_signal: https://en.wikipedia.org/wiki/Digital_signal
:interconnection: https://en.wikipedia.org/wiki/Interconnection
:telecommunication_network: https://en.wikipedia.org/wiki/Telecommunication_network
:network_topology: https://en.wikipedia.org/wiki/Network_topology

:personal_computer: https://en.wikipedia.org/wiki/Personal_computer
:server_computing: https://en.wikipedia.org/wiki/Server_(computing)
:networking_hardware: https://en.wikipedia.org/wiki/Networking_hardware
:host_network: https://en.wikipedia.org/wiki/Host_(network)
:network_address: https://en.wikipedia.org/wiki/Network_address
:internet_protocol: https://en.wikipedia.org/wiki/Internet_Protocol

:transmission_medium: https://en.wikipedia.org/wiki/Transmission_medium
:bandwidth_computing: https://en.wikipedia.org/wiki/Bandwidth_(computing)
:communications_protocol: https://en.wikipedia.org/wiki/Communications_protocol
:network_traffic_control: https://en.wikipedia.org/wiki/Network_traffic_control

:application_software: https://en.wikipedia.org/wiki/Application_software
:network_service: https://en.wikipedia.org/wiki/Network_service
:file_server: https://en.wikipedia.org/wiki/File_server

== Computer Network

A *computer network* is a set of {computer}[computers] sharing resources located on or provided by {node_networking}[network nodes]. The computers use common {communication_protocol}[communication protocols] over {digital_singal}[digital] {interconnection}[interconnections] to communicate with each other. These interconnections are made up of {telecommunication_network}[telecommunication network] technologies, based on physically wired, optical, and wireless radio-frequency methods that may be arranged in a variety of {network_topology}[network topologies].

The nodes of a computer network may include {personal_computer}[personal computers], {server_computing}[servers], {networking_hardware}[networking hardware], or other specialised or general-purpose {host_network}[hosts]. They are identified by {network_address}[network addresses], and may have hostnames. Hostnames serve as memorable labels for the nodes, rarely changed after initial assignment. Network addresses serve for locating and identifying the nodes by communication protocols such as the {internet_protocol}[Internet Protocol].

Computer networks may be classified by many criteria, including the {transmission_medium}[transmission medium] used to carry signals, {bandwidth_computing}[bandwidth], {communications_protocol}[communications protocols] to organize network traffic, the network size, the topology, {network_traffic_control}[traffic control] mechanism, and organizational intent.

Computer networks support many {application_software}[applications] and {network_service}[services], such as access to the World Wide Web, digital video, digital audio, shared use of {file_server}[application and storage servers], printers, and fax machines, and use of email and instant messaging applications. 

=== Network Packet

:network_packet: https://en.wikipedia.org/wiki/Network_packet
:packet-switched_network: https://en.wikipedia.org/wiki/Packet-switched_network
:error_detection: https://en.wikipedia.org/wiki/Error_detection
:header_computing: https://en.wikipedia.org/wiki/Header_(computing)
:trailer_computing: https://en.wikipedia.org/wiki/Trailer_(computing)
:payload_computing: https://en.wikipedia.org/wiki/Payload_(computing)
:circuit_switching: https://en.wikipedia.org/wiki/Circuit_switching
:message_queue: https://en.wikipedia.org/wiki/Message_queue
:maximum_transmission_unit: https://en.wikipedia.org/wiki/Maximum_transmission_unit

Most modern computer networks use protocols based on packet-mode transmission. A {network_packet}[network packet] is a formatted unit of data carried by a {packet-switched_network}[packet-switched network].

Packets consist of two types of data: control information and user data (payload). The control information provides data the network needs to deliver the user data, for example, source and destination {network_address}[network addresses], {error_detection}[error detection] codes, and sequencing information. Typically, control information is found in {header_computing}[packet headers] and {trailer_computing}[trailers], with {payload_computing}[payload data] in between.

With packets, the {bandwidth_computing}[bandwidth] of the transmission medium can be better shared among users than if the network were {circuit_switching}[circuit switched]. When one user is not sending packets, the link can be filled with packets from other users, and so the cost can be shared, with relatively little interference, provided the link isn't overused. Often the route a packet needs to take through a network is not immediately available. In that case, the packet is {message_queue}[queued] and waits until a link is free.

The physical link technologies of packet network typically limit the size of packets to a certain {maximum_transmission_unit}[maximum transmission unit] (MTU). A longer message may be fragmented before it is transferred and once the packets arrive, they are reassembled to construct the original message. 

=== Network Topology

:bus_network: https://en.wikipedia.org/wiki/Bus_network
:ethernet: https://en.wikipedia.org/wiki/Ethernet
:10base5: https://en.wikipedia.org/wiki/10BASE5
:10base2: https://en.wikipedia.org/wiki/10BASE2
:data_link_layer: https://en.wikipedia.org/wiki/Data_link_layer
:physical_layer: https://en.wikipedia.org/wiki/Physical_layer
:point-to-point_telecommunications: https://en.wikipedia.org/wiki/Point-to-point_(telecommunications)

:star_network: https://en.wikipedia.org/wiki/Star_network
:wireless_lan: https://en.wikipedia.org/wiki/Wireless_LAN
:wireless_access_point: https://en.wikipedia.org/wiki/Wireless_access_point

:ring_network: https://en.wikipedia.org/wiki/Ring_network
:fiber_distributed_data_interface: https://en.wikipedia.org/wiki/Fiber_Distributed_Data_Interface

:mesh_network: https://en.wikipedia.org/wiki/Mesh_network

:fully_connected_network: https://en.wikipedia.org/wiki/Fully_connected_network

:tree_network: https://en.wikipedia.org/wiki/Tree_network

{network_topology}[Network topology] is the layout, pattern, or organizational hierarchy of the interconnection of network hosts, in contrast to their physical or geographic location. Typically, most diagrams describing networks are arranged by their topology. The network topology can affect throughput, but reliability is often more critical. With many technologies, such as bus or star networks, a single failure can cause the network to fail entirely. In general, the more interconnections there are, the more robust the network is; but the more expensive it is to install.

Common layouts are:

* {bus_netowrk}[Bus network]: all nodes are connected to a common medium along this medium. This was the layout used in the original {ethernet}[Ethernet], called {10base5}[10BASE5] and {10base2}[10BASE2]. This is still a common topology on the {data_link_layer}[data link layer], although modern {physical_layer}[physical layer] variants use {point-to-point_telecommunications}[point-to-point] links instead.

* {start_network}[Star network]: all nodes are connected to a special central node. This is the typical layout found in a {wireless_lan}[Wireless LAN], where each wireless client connects to the central {Wireless_access_point}[Wireless access point].

* {ring_network}[Ring network]: each node is connected to its left and right neighbour node, such that all nodes are connected and that each node can reach each other node by traversing nodes left- or rightwards. The {fiber_distributed_data_interface}[Fiber Distributed Data Interface] (FDDI) made use of such a topology.

* {mesh_network}[Mesh network]: each node is connected to an arbitrary number of neighbours in such a way that there is at least one traversal from any node to any other.

* {fully_connected_network}[Fully connected network]: each node is connected to every other node in the network.

* {tree_network}[Tree network]: nodes are arranged hierarchically.

The physical layout of the nodes in a network may not necessarily reflect the network topology. As an example, with {fiber_distributed_data_interface}[FDDI], the network topology is a ring, but the physical topology is often a star, because all neighboring connections can be routed via a central physical location. Physical layout is not completely irrelevant, however, as common ducting and equipment locations can represent single points of failure due to issues like fires, power failures and flooding. 

=== Overlay network

:overlay_network: https://en.wikipedia.org/wiki/Overlay_network
:peer-to-peer: https://en.wikipedia.org/wiki/Peer-to-peer
:modem: https://en.wikipedia.org/wiki/Modem
:telecommunications_network_data_network: https://en.wikipedia.org/wiki/Telecommunications_network#Data_network
:telephone_network: https://en.wikipedia.org/wiki/Telephone_network
:address_resolution_protocol: https://en.wikipedia.org/wiki/Address_Resolution_Protocol
:routing: https://en.wikipedia.org/wiki/Routing
:distributed_hash_table: https://en.wikipedia.org/wiki/Distributed_hash_table
:associative_array: https://en.wikipedia.org/wiki/Associative_array
:quality_of_service: https://en.wikipedia.org/wiki/Quality_of_service
:streaming_media: https://en.wikipedia.org/wiki/Streaming_media
:ip_multicast: https://en.wikipedia.org/wiki/IP_Multicast
:router_computing: https://en.wikipedia.org/wiki/Router_(computing)
:internet_service_provider: https://en.wikipedia.org/wiki/Internet_service_provider
:multicast: https://en.wikipedia.org/wiki/Multicast

An {overlay_network}[overlay network] is a virtual network that is built on top of another network. Nodes in the overlay network are connected by virtual or logical links. Each link corresponds to a path, perhaps through many physical links, in the underlying network. The topology of the overlay network may (and often does) differ from that of the underlying one. For example, many {peer-to-peer}[peer-to-peer] networks are overlay networks. They are organized as nodes of a virtual system of links that run on top of the Internet.

Overlay networks have been around since the invention of networking when computer systems were connected over telephone lines using {modem}[modems], before any {telecommunications_network_data_network}[data network] existed.

The most striking example of an overlay network is the Internet itself. The Internet itself was initially built as an overlay on the {telephone_network}[telephone network]. Even today, each Internet node can communicate with virtually any other through an underlying mesh of sub-networks of wildly different topologies and technologies. {address_resolution_protocol}[Address resolution] and {routing}[routing] are the means that allow mapping of a fully connected IP overlay network to its underlying network.

Another example of an overlay network is a {distributed_hash_table}[distributed hash table], which maps keys to nodes in the network. In this case, the underlying network is an IP network, and the overlay network is a table (actually a {associative_array}[map]) indexed by keys.

Overlay networks have also been proposed as a way to improve Internet routing, such as through {quality_of_service}[quality of service] guarantees achieve higher-quality {streaming_media}[streaming media]. Previous proposals such as IntServ, DiffServ, and {ip_multicast}[IP Multicast] have not seen wide acceptance largely because they require modification of all {router_computing}[routers] in the network.[citation needed] On the other hand, an overlay network can be incrementally deployed on end-hosts running the overlay protocol software, without cooperation from {internet_service_provider}[Internet service providers]. The overlay network has no control over how packets are routed in the underlying network between two overlay nodes, but it can control, for example, the sequence of overlay nodes that a message traverses before it reaches its destination.

For example, https://en.wikipedia.org/wiki/Akamai_Technologies[Akamai Technologies] manages an overlay network that provides reliable, efficient content delivery (a kind of multicast). Academic research includes end system {multicast}[multicast], resilient routing and quality of service studies, among others. 

=== Network Links

:transmission_medium: https://en.wikipedia.org/wiki/Transmission_medium
:electrical_cable: https://en.wikipedia.org/wiki/Electrical_cable
:optical_fiber: https://en.wikipedia.org/wiki/Optical_fiber
:osi_model: https://en.wikipedia.org/wiki/OSI_model
:local_area_network: https://en.wikipedia.org/wiki/Local_area_network
:ethernet: https://en.wikipedia.org/wiki/Ethernet
:ieee_802_3: https://en.wikipedia.org/wiki/IEEE_802.3
:wireless_lan: https://en.wikipedia.org/wiki/Wireless_LAN
:radio_waves: https://en.wikipedia.org/wiki/Radio_waves
:power_line_communication: https://en.wikipedia.org/wiki/Power_line_communication
:power_cabling: https://en.wikipedia.org/wiki/Power_cabling

The transmission media (often referred to in the literature as the {transmission_medium}[physical medium]) used to link devices to form a computer network include {electrical_cable}[electrical cable], {optical_fiber}[optical fiber], and free space. In the {osi_model}[OSI model], the software to handle the media is defined at layers 1 and 2 — the physical layer and the data link layer.

A widely adopted family that uses copper and fiber media in {local_area_network}[local area network] (LAN) technology are collectively known as {ethernet}[Ethernet]. The media and protocol standards that enable communication between networked devices over Ethernet are defined by {ieee_802_3}[IEEE 802.3]. {wireless_lan}[Wireless LAN] standards use {radio_waves}[radio waves], others use infrared signals as a transmission medium. {power_line_communication}[Power line communication] uses a building's {power_cabling}[power cabling] to transmit data. 

==== Wired

:coaxial_cable: https://en.wikipedia.org/wiki/Coaxial_cable
:itu-t: https://en.wikipedia.org/wiki/ITU-T
:g_hn: https://en.wikipedia.org/wiki/G.hn
:twisted_pair: https://en.wikipedia.org/wiki/Twisted_pair
:crosstalk_electronics: https://en.wikipedia.org/wiki/Crosstalk_(electronics)
:optical_fiber: https://en.wikipedia.org/wiki/Optical_fiber
:optical_amplifier: https://en.wikipedia.org/wiki/Optical_amplifier
:Wavelength-division_multiplexing: https://en.wikipedia.org/wiki/Wavelength-division_multiplexing
:undersea_cables: https://en.wikipedia.org/wiki/Undersea_cables
:single-mode_optical_fiber: https://en.wikipedia.org/wiki/Single-mode_optical_fiber
:multi-mode_optical_fiber: https://en.wikipedia.org/wiki/Multi-mode_optical_fiber

The following classes of wired technologies are used in computer networking.

* {coaxial_cable}[Coaxial cable] is widely used for cable television systems, office buildings, and other work-sites for local area networks. Transmission speed ranges from 200 million bits per second to more than 500 million bits per second.

* {itu-t}[ITU-T] {g_hn}[G.hn] technology uses existing home wiring (coaxial cable, phone lines and power lines) to create a high-speed local area network.

* {twisted_pair}[Twisted pair] cabling is used for wired Ethernet and other standards. It typically consists of 4 pairs of copper cabling that can be utilized for both voice and data transmission. The use of two wires twisted together helps to reduce {crosstalk_electronics}[crosstalk] and electromagnetic induction. The transmission speed ranges from 2 Mbit/s to 10 Gbit/s. Twisted pair cabling comes in two forms: unshielded twisted pair (UTP) and shielded twisted-pair (STP). Each form comes in several category ratings, designed for use in various scenarios.

* An {optical_fiber}[optical fiber] is a glass fiber. It carries pulses of light that represent data via lasers and {optical_amplifier}[optical amplifiers]. Some advantages of optical fibers over metal wires are very low transmission loss and immunity to electrical interference. Using dense {Wavelength-division_multiplexing}[wave division multiplexing], optical fibers can simultaneously carry multiple streams of data on different wavelengths of light, which greatly increases the rate that data can be sent to up to trillions of bits per second. Optic fibers can be used for long runs of cable carrying very high data rates, and are used for {undersea_cables}[undersea cables] to interconnect continents. There are two basic types of fiber optics, {single-mode_optical_fiber}[single-mode optical fiber] (SMF) and {multi-mode_optical_fiber}[multi-mode optical fiber] (MMF). Single-mode fiber has the advantage of being able to sustain a coherent signal for dozens or even a hundred kilometers. Multimode fiber is cheaper to terminate but is limited to a few hundred or even only a few dozens of meters, depending on the data rate and cable grade.

==== Wireless

:microwave: https://en.wikipedia.org/wiki/Microwave
:communications_satellite: https://en.wikipedia.org/wiki/Communications_satellite
:cellular_network: https://en.wikipedia.org/wiki/Cellular_network
:transceiver: https://en.wikipedia.org/wiki/Transceiver
:spread_spectrum: https://en.wikipedia.org/wiki/Spread_spectrum
:ieee_802_11: https://en.wikipedia.org/wiki/IEEE_802.11
:wi-fi: https://en.wikipedia.org/wiki/Wi-Fi
:free-space_optical_communication: https://en.wikipedia.org/wiki/Free-space_optical_communication
:interplanetary_internet: https://en.wikipedia.org/wiki/Interplanetary_Internet
:ip_over_avian_carriers: https://en.wikipedia.org/wiki/IP_over_Avian_Carriers
:request_for_comments: https://en.wikipedia.org/wiki/Request_for_Comments

Network connections can be established wirelessly using radio or other electromagnetic means of communication.

* Terrestrial {microwave}[microwave] – Terrestrial microwave communication uses Earth-based transmitters and receivers resembling satellite dishes. Terrestrial microwaves are in the low gigahertz range, which limits all communications to line-of-sight. Relay stations are spaced approximately 40 miles (64 km) apart.

* {communications_satellite}[Communications satellites] – Satellites also communicate via microwave. The satellites are stationed in space, typically in geosynchronous orbit 35,400 km (22,000 mi) above the equator. These Earth-orbiting systems are capable of receiving and relaying voice, data, and TV signals.

* {cellular_network}[Cellular networks] use several radio communications technologies. The systems divide the region covered into multiple geographic areas. Each area is served by a low-power {transceiver}[transceiver].

* Radio and {spread_spectrum}[spread spectrum] technologies – Wireless LANs use a high-frequency radio technology similar to digital cellular. Wireless LANs use spread spectrum technology to enable communication between multiple devices in a limited area. {ieee_802_11}[IEEE 802.11] defines a common flavor of open-standards wireless radio-wave technology known as {wi-fi}[Wi-Fi].

* {free-space_optical_communication}[Free-space optical communication] uses visible or invisible light for communications. In most cases, line-of-sight propagation is used, which limits the physical positioning of communicating devices.

* Extending the Internet to interplanetary dimensions via radio waves and optical means, the {interplanetary_internet}[Interplanetary Internet].

* {ip_over_avian_carriers}[IP over Avian Carriers] was a humorous April fool's {request_for_comments}[Request for Comments], issued as RFC 1149. It was implemented in real life in 2001.

The last two cases have a large round-trip delay time, which gives slow two-way communication but doesn't prevent sending large amounts of information (they can have high throughput). 

=== Network Nodes

:systems_engineering: https://en.wikipedia.org/wiki/Systems_engineering
:network_interface_controller: https://en.wikipedia.org/wiki/Network_interface_controller
:repeater: https://en.wikipedia.org/wiki/Repeater
:ethernet_hub: https://en.wikipedia.org/wiki/Ethernet_hub
:network_bridge: https://en.wikipedia.org/wiki/Network_bridge
:network_switch: https://en.wikipedia.org/wiki/Network_switch
:router_computing: https://en.wikipedia.org/wiki/Router_(computing)
//:modem: https://en.wikipedia.org/wiki/Modem
:firewall_computing: https://en.wikipedia.org/wiki/Firewall_(computing)

Apart from any physical transmission media, networks are built from additional basic {systems_engineering}[system] building blocks, such as {network_interface_controller}[network interface controllers] (NICs), {repeater}[repeaters], {ethernet_hub}[hubs], {network_bridge}[bridges], {network_switch}[switches], {router_computing}[routers], {modem}[modems], and {firewall_computing}[firewalls]. Any particular piece of equipment will frequently contain multiple building blocks and so may perform multiple functions. 

==== Network interfaces

:computer_hardware: https://en.wikipedia.org/wiki/Computer_hardware
:network_media: https://en.wikipedia.org/wiki/Network_media
:mac_address: https://en.wikipedia.org/wiki/MAC_address
:institute_of_electrical_and_electronics_engineers: https://en.wikipedia.org/wiki/Institute_of_Electrical_and_Electronics_Engineers

A {network_interface_controller}[network interface controller] (NIC) is {computer_hardware}[computer hardware] that connects the computer to the {network_media}[network media] and has the ability to process low-level network information. For example, the NIC may have a connector for accepting a cable, or an aerial for wireless transmission and reception, and the associated circuitry.

In {ethernet}[Ethernet] networks, each network interface controller has a unique {mac_address}[Media Access Control] (MAC) address—usually stored in the controller's permanent memory. To avoid address conflicts between network devices, the {institute_of_electrical_and_electronics_engineers}[Institute of Electrical and Electronics Engineers] (IEEE) maintains and administers MAC address uniqueness. The size of an Ethernet MAC address is six octets. The three most significant octets are reserved to identify NIC manufacturers. These manufacturers, using only their assigned prefixes, uniquely assign the three least-significant octets of every Ethernet interface they produce. 

==== Repeaters and hubs

:electronics: https://en.wikipedia.org/wiki/Electronics
:retransmission_data_networks: https://en.wikipedia.org/wiki/Retransmission_(data_networks)
:propagation_delay: https://en.wikipedia.org/wiki/Propagation_delay
:5-4-3_rule: https://en.wikipedia.org/wiki/5-4-3_rule

A {repeater}[repeater] is an {electronics}[electronic] device that receives a network signal, cleans it of unnecessary noise and regenerates it. The signal is {retransmission_data_networks}[retransmitted] at a higher power level, or to the other side of obstruction so that the signal can cover longer distances without degradation. In most twisted pair Ethernet configurations, repeaters are required for cable that runs longer than 100 meters. With fiber optics, repeaters can be tens or even hundreds of kilometers apart.

Repeaters work on the physical layer of the OSI model but still require a small amount of time to regenerate the signal. This can cause a {propagation_delay}[propagation delay] that affects network performance and may affect proper function. As a result, many network architectures limit the number of repeaters used in a network, e.g., the Ethernet {5-4-3_rule}[5-4-3 rule].

*An Ethernet repeater with multiple ports is known as an {Ethernet_hub}[Ethernet hub].* In addition to reconditioning and distributing network signals, a repeater hub assists with collision detection and fault isolation for the network. Hubs and repeaters in LANs have been largely obsoleted by modern {network_switch}[network switches]. 

==== Bridges and switches

:network_segment: https://en.wikipedia.org/wiki/Network_segment
:frame_networking: https://en.wikipedia.org/wiki/Frame_(networking)
:computer_port_hardware: https://en.wikipedia.org/wiki/Computer_port_(hardware)

{network_bridge}[Network bridges] and {network_switch}[network switches] are distinct from a hub in that they only forward frames to the ports involved in the communication whereas a hub forwards to all ports. *Bridges only have two ports but a switch can be thought of as a multi-port bridge.* Switches normally have numerous ports, facilitating a star topology for devices, and for cascading additional switches.

Bridges and switches operate at the {date_link_layer}[data link layer] (layer 2) of the {osi_model}[OSI model] and {network_bridge}[bridge] traffic between two or more {network_segment}[network segments] to form a single local network. Both are devices that forward {frame_networking}[frames] of data between {computer_port_hardware}[ports] based on the destination MAC address in each frame. They learn the association of physical ports to MAC addresses by examining the source addresses of received frames and only forward the frame when necessary. If an unknown destination MAC is targeted, the device broadcasts the request to all ports except the source, and discovers the location from the reply.

Bridges and switches divide the network's collision domain but maintain a single broadcast domain. Network segmentation through bridging and switching helps break down a large, congested network into an aggregation of smaller, more efficient networks. 

==== Routers

:internetworking: https://en.wikipedia.org/wiki/Internetworking
:routing_table: https://en.wikipedia.org/wiki/Routing_table

A {router_computing}[router] is an {internetworking}[internetworking] device that forwards packets between networks by processing the addressing or routing information included in the packet. The routing information is often processed in conjunction with the {routing_table}[routing table]. A router uses its routing table to determine where to forward packets and does not require broadcasting packets which is inefficient for very big networks. 

==== Modems

:carrier_signal: https://en.wikipedia.org/wiki/Carrier_signal
:modulation: https://en.wikipedia.org/wiki/Modulation
:analog_signal: https://en.wikipedia.org/wiki/Analog_signal
:audio_signal: https://en.wikipedia.org/wiki/Audio_signal
:digital_subscriber_line: https://en.wikipedia.org/wiki/Digital_subscriber_line
:docsis: https://en.wikipedia.org/wiki/DOCSIS

{modem}[Modems] (modulator-demodulator) are used to connect network nodes via wire not originally designed for digital network traffic, or for wireless. To do this one or more {carrier_signal}[carrier signals] are {modulation}[modulated] by the {analog_signal}[digital signal] to produce an analog signal that can be tailored to give the required properties for transmission. Early modems modulated {audio_signal}[audio signals] sent over a standard voice telephone line. Modems are still commonly used for telephone lines, using a {digital_subscriber_line}[digital subscriber line] technology and cable television systems using {docsis}[DOCSIS] technology. 

==== Firewalls

:cyberattack: https://en.wikipedia.org/wiki/Cyberattack

A {firewall_computing}[firewall] is a network device or software for controlling network security and access rules. Firewalls are inserted in connections between secure internal networks and potentially insecure external networks such as the Internet. Firewalls are typically configured to reject access requests from unrecognized sources while allowing actions from recognized ones. The vital role firewalls play in network security grows in parallel with the constant increase in {cyberattack}[cyber attacks]. 

=== Communication protocols

:communication_protocol: https://en.wikipedia.org/wiki/Communication_protocol
:connection-oriented_communication: https://en.wikipedia.org/wiki/Connection-oriented_communication
:connectionless_communication: https://en.wikipedia.org/wiki/Connectionless_communication
:circuit_mode: https://en.wikipedia.org/wiki/Circuit_mode
:packet_switching: https://en.wikipedia.org/wiki/Packet_switching
:protocol_stack: https://en.wikipedia.org/wiki/Protocol_stack
:http: https://en.wikipedia.org/wiki/HTTP
:transmission_control_protocol: https://en.wikipedia.org/wiki/Transmission_control_protocol
:internet_protocol: https://en.wikipedia.org/wiki/Internet_protocol
:internet_protocol_suite: https://en.wikipedia.org/wiki/Internet_Protocol_Suite
:ieee_802_11: https://en.wikipedia.org/wiki/IEEE_802.11
:wireless_router: https://en.wikipedia.org/wiki/Wireless_router

A {communication_protocol}[communication protocol] is a set of rules for exchanging information over a network. Communication protocols have various characteristics. They may be {connection-oriented_communication}[connection-oriented] or {connectionless_communication}[connectionless], they may use {circuit_mode}[circuit mode] or {packet_switching}[packet switching], and they may use hierarchical addressing or flat addressing.

In a {protocol_stack}[protocol stack], often constructed per the {osi_model}[OSI model], communications functions are divided up into protocol layers, where each layer leverages the services of the layer below it until the lowest layer controls the hardware that sends information across the media. The use of protocol layering is ubiquitous across the field of computer networking. An important example of a protocol stack is {http}[HTTP] (the World Wide Web protocol) running over {transmission_control_protocol}[TCP] over {internet_protocol}[IP] (the {internet_protocol_suite}[Internet protocols]) over {ieee_802_11}[IEEE 802.11] (the Wi-Fi protocol). This stack is used between the {wireless_router}[wireless router] and the home user's personal computer when the user is surfing the web.

There are many communication protocols, a few of which are described below. 

==== Common protocols

:ipv4: https://en.wikipedia.org/wiki/IPv4
:ipv6: https://en.wikipedia.org/wiki/IPv6
:internet: https://en.wikipedia.org/wiki/Internet

The {internet_protocol_suite}[Internet Protocol Suite], also called TCP/IP, is the foundation of all modern networking. It offers connection-less and connection-oriented services over an inherently unreliable network traversed by datagram transmission using Internet protocol (IP). At its core, the protocol suite defines the addressing, identification, and routing specifications for {ipv4}[Internet Protocol Version 4] (IPv4) and for {ipv6}[IPv6], the next generation of the protocol with a much enlarged addressing capability. The Internet Protocol Suite is the defining set of protocols for the {internet}[Internet].

== References

* https://en.wikipedia.org/wiki/Computer_network
* https://en.wikipedia.org/wiki/Traceroute
* https://en.wikipedia.org/wiki/Layer_four_traceroute
* https://en.wikipedia.org/wiki/MTR_(software)
* https://en.wikipedia.org/wiki/Time_to_live
* https://en.wikipedia.org/wiki/Latency_(engineering)
