= What is OAuth2
:page-layout: post
:page-categories: ['oauth2']
:page-tags: ['oauth2', 'openid', 'jwt']
:page-date: 2022-05-21 09:28:55 +0800
:page-revdate: 2022-05-21 09:28:55 +0800
:toc:
:sectnums:
:toclevels: 5

== What is OAuth2

The OAuth 2.0 authorization framework enables a *third-party* application to obtain *limited access* to an HTTP service, either *on behalf of a resource owner* by orchestrating an approval interaction between the resource owner and the HTTP service, or by allowing the third-party application to obtain access on its own behalf.

The steps to grant permission, or *_consent_*, are often referred to as *_authorization_* or even *_delegated authorization_*. You authorize one application to access your data, or use features in another application on your behalf, without giving them your password. 

* OAuth is about how to *get a token* and how to *use a token*.
* OAuth is a *delegation* framework that provides authorization across systems.
* OAuth replaces the password-sharing antipattern with a delegation protocol that’s simultaneously more secure and more usable.
* OAuth is focused on solving a small set of problems and solving them well, which makes it a suitable component within larger security systems.

=== Roles

OAuth defines four roles:

* *resource owner*
+
An entity capable of granting access to a protected resource.
      When the resource owner is a person, it is referred to as an
      end-user.

* *resource server*
+
The server hosting the protected resources, capable of accepting and responding to protected resource requests using access tokens.

* *client*
+
An application making protected resource requests on behalf of the resource owner and with its authorization.  The term "client" does not imply any particular implementation characteristics (e.g., whether the application executes on a server, a desktop, or other
devices).

* *authorization server*
+
The server issuing access tokens to the client after successfully authenticating the resource owner and obtaining authorization.

=== Protocol Flow

.Abstract Protocol Flow
[source,text]
----
+--------+                               +---------------+
|        |--(1)- Authorization Request ->|   Resource    |
|        |                               |     Owner     |
|        |<-(2)-- Authorization Grant ---|               |
|        |                               +---------------+
|        |
|        |                               +---------------+
|        |--(3)-- Authorization Grant -->| Authorization |
| Client |                               |     Server    |
|        |<-(4)----- Access Token -------|               |
|        |                               +---------------+
|        |
|        |                               +---------------+
|        |--(5)----- Access Token ------>|    Resource   |
|        |                               |     Server    |
|        |<-(6)--- Protected Resource ---|               |
+--------+                               +---------------+
----

<1> The client requests authorization from the resource owner. The authorization request can be made directly to the resource owner (as shown), or preferably indirectly via the authorization server as an intermediary.

<2> The client receives an authorization grant, which is a credential representing the resource owner's authorization,expressed using one of four grant types defined in this specification or using an extension grant type. The authorization grant type depends on the method used by the client to request authorization and the types supported by the authorization server.

<3> The client requests an access token by authenticating with the authorization server and presenting the authorization grant.

<4> The authorization server authenticates the client and validates the authorization grant, and if valid, issues an access token.

<5> The client requests the protected resource from the resource server and authenticates by presenting the access token.

<6> The resource server validates the access token, and if valid, serves the request.

=== Obtaining Authorization

To request an access token, the client obtains authorization from the
   resource owner.  The authorization is expressed in the form of an
   authorization grant, which the client uses to request the access
   token.  OAuth defines four grant types: *authorization code*, implicit,
   *resource owner password credentials*, and *client credentials*.  It also
   provides an extension mechanism for defining additional grant types.

=== OpenID Connect

OpenID Connect 1.0 is a simple identity layer on top of the OAuth 2.0 protocol. It allows Clients to verify the identity of the End-User based on the authentication performed by an Authorization Server, as well as to obtain basic profile information about the End-User in an interoperable and REST-like manner.

The OpenID Connect flow looks the same as OAuth. The only differences are, in the initial request, a specific scope of *openid* is used, and in the final exchange the *client* receives both an *access token* and an *id token*.

== What is JSON Web Token?

JSON Web Token (JWT) is an open standard (https://tools.ietf.org/html/rfc7519[RFC 7519]) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. This information can be verified and trusted because it is digitally signed. JWTs can be signed using a secret (with the *HMAC* algorithm) or a public/private key pair using *RSA* or *ECDSA*.

== References

* https://aaronparecki.com/oauth-2-simplified/
* https://tools.ietf.org/html/rfc6749[The OAuth 2.0 Authorization Framework, https://tools.ietf.org/html/rfc6749]
* https://www.oauth.com
* https://developer.okta.com/blog/2019/10/21/illustrated-guide-to-oauth-and-oidc
* https://openid.net/connect/
* https://jwt.io/
* https://stackoverflow.com/questions/6916805/why-does-a-base64-encoded-string-have-an-sign-at-the-end
* https://superuser.com/questions/1225134/why-does-the-base64-of-a-string-contain-n
