= What is OpenTelemetry
:page-layout: post
:page-categories: ['opentelemetry']
:page-tags: ['opentelemetry', 'dotnet']
:page-date: 2023-07-11 15:12:56 +0800
:page-revdate: 2023-07-11 15:12:56 +0800
:toc: preamble
:toclevels: 4
:sectnums:
:sectnumlevels: 4

:what-is-observability: https://opentelemetry.io/docs/concepts/observability-primer/#what-is-observability
:signals-traces: https://opentelemetry.io/docs/concepts/signals/traces/
:signals-metrics: https://opentelemetry.io/docs/concepts/signals/metrics/
:signals-logs: https://opentelemetry.io/docs/concepts/signals/logs/
:ecosystem-vendors: https://opentelemetry.io/ecosystem/vendors/

As modern application environments are polyglot, distributed, and increasingly complex, observing your application to identify and react to failures has become challenging. In early 2019, two popular instrumentation projects, https://opentracing.io/[OpenTracing] and OpenCensus, merged to create https://opentelemetry.io/[OpenTelemetry], a new standard for observability telemetry. <<opentelemetry-net-reaches-v1-0>>

OpenTelemetry is a collection of APIs, SDKs, and tools. Use it to instrument, generate, collect, and export telemetry data (metrics, logs, and traces) to help you analyze your software’s performance and behavior. <<otel>>

OpenTelemetry is generally available across https://opentelemetry.io/docs/instrumentation/[several languages] and is suitable for use.

OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source {what-is-observability}[Observability] framework for instrumenting, generating, collecting, and exporting telemetry data such as {signals-traces}[traces], {signals-metrics}[metrics], {signals-logs}[logs]. As an industry-standard, it is {ecosystem-vendors}[natively supported by a number of vendors]. <<otel-docs>>

image::https://opentelemetry.io/img/otel-diagram.svg[,55%,55%]

== What is Observability?

Observability lets us understand a system from the outside, by letting us ask questions about that system without knowing its inner workings. Furthermore, it allows us to easily troubleshoot and handle novel problems (i.e. “unknown unknowns”), and helps us answer the question, “Why is this happening?” <<otel-observability-primer>>

In order to be able to ask those questions of a system, the application must be properly instrumented. That is, the application code must emit signals such as {signals-traces}[traces], {signals-metrics}[metrics], {signals-logs}[logs]. An application is properly instrumented when developers don’t need to add more instrumentation to troubleshoot an issue, because they have all of the information they need.

OpenTelemetry is the mechanism by which application code is instrumented, to help make a system observable.

=== Reliability & Metrics

*Telemetry* refers to data emitted from a system, about its behavior. The data can come in the form of {signals-traces}[traces], {signals-metrics}[metrics], {signals-logs}[logs].

*Reliability* answers the question: “Is the service doing what users expect it to be doing?” A system could be up 100% of the time, but if, when a user clicks “Add to Cart” to add a black pair of pants to their shopping cart, and instead, the system doesn’t always add black pants, then the system would be said to be *un*reliable.

*Metrics* are aggregations over a period of time of numeric data about your infrastructure or application. Examples include: system error rate, CPU utilization, request rate for a given service. For more on metrics and how they pertain to OTel, see {signals-metrics}[Metrics].

*SLI*, or Service Level Indicator, represents a measurement of a service’s behavior. A good SLI measures your service from the perspective of your users. An example SLI can be the speed at which a web page loads.

*SLO*, or Service Level Objective, is the means by which reliability is communicated to an organization/other teams. This is accomplished by attaching one or more SLIs to business value.

=== Understanding Distributed Tracing

To understand Distributed Tracing, let’s start with some basics.

==== Logs

A *log* is a timestamped message emitted by services or other components. Unlike link:#distributed-traces[traces], however, they are not necessarily associated with any particular user request or transaction. They are found almost everywhere in software, and have been heavily relied on in the past by both developers and operators alike to help them understand system behavior.

Sample log:

[source,text]
----
I, [2021-02-23T13:26:23.505892 #22473]  INFO -- : [6459ffe1-ea53-4044-aaa3-bf902868f730] Started GET "/" for ::1 at 2021-02-23 13:26:23 -0800
----

Unfortunately, logs aren’t extremely useful for tracking code execution, as they typically lack contextual information, such as where they were called from.

They become far more useful when they are included as part of a link:#spans[span], or when they are correlated with a trace and a span.

For more on logs and how they pertain to OTel, see {signals-logs}[Logs].

==== Spans

A *span* represents a unit of work or operation. It tracks specific operations that a request makes, painting a picture of what happened during the time in which that operation was executed.

A span contains name, time-related data, {signals-traces}/#span-events[structured log messages], and {signals-traces}#attributes[other metadata (that is, Attributes)] to provide information about the operation it tracks.

===== Span attributes

The following table contains examples of span attributes:

[%header,cols="1,7"]
|===
|Key
|Value

|net.transport
|IP.TCP

|net.peer.ip
|10.244.0.1

|net.peer.port
|10243

|net.host.name
|localhost

|http.method
|GET

|http.target
|/cart

|http.server_name
|frontend

|http.route
|/cart

|http.scheme
|http

|http.host
|localhost

|http.flavor
|1.1

|http.status_code
|200

|http.user_agent
|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

|===

For more on spans and how they pertain to OTel, see {signals-traces}#spans[Spans].

==== Distributed Traces

A *distributed trace*, more commonly known as a *trace*, records the paths taken by requests (made by an application or end-user) as they propagate through multi-service architectures, like microservice and serverless applications.

Without tracing, it is challenging to pinpoint the cause of performance problems in a distributed system.

It improves the visibility of our application or system’s health and lets us debug behavior that is difficult to reproduce locally. Tracing is essential for distributed systems, which commonly have nondeterministic problems or are too complicated to reproduce locally.

Tracing makes debugging and understanding distributed systems less daunting by breaking down what happens within a request as it flows through a distributed system.

A trace is made of one or more spans. The first span represents the root span. Each root span represents a request from start to finish. The spans underneath the parent provide a more in-depth context of what occurs during a request (or what steps make up a request).

Many Observability back-ends visualize traces as waterfall diagrams that may look something like this:

image::https://opentelemetry.io/img/waterfall-trace.svg[Waterfall,55%,55%]

Waterfall diagrams show the parent-child relationship between a root span and its child spans. When a span encapsulates another span, this also represents a nested relationship.

For more on traces and how they pertain to OTel, see {signals-traces}[Traces].

== .NET observability with OpenTelemetry

When you run an application, you want to know how well the app is performing and to detect potential problems before they become larger. Commonly developers accomplish this by making the app emit telemetry data such as logs or metrics, then monitor and analyze that data. <<otel-dotnet>>

=== What is observability

Observability in the context of a distributed system is the ability to monitor and analyze telemetry about the state of each component, to be able to observe changes in performance, and to diagnose why those changes occur. Unlike debugging, which is invasive and can affect the operation of the application, observability is intended to be transparent to the primary operation and have a small enough performance impact that it can be used continuously.

Observability is commonly done using a combination of:

* Logs, which record individual operations, such as an incoming request, a failure in a specific component, or an order being placed.
* Metrics, which are measuring counters and gauges such as number of completed requests, active requests, widgets that have been sold; or a histogram of the request latency.
* Distributed tracing, which tracks requests and activities across components in a distributed system so that you can see where time is spent and track down specific failures.

Together, logs, metrics, and distributed tracing are known as the _3 pillars of observability_.

Each pillar might include telemetry data from:

* The .NET runtime, such as the garbage collector or JIT compiler.
* Libraries, such as from Kestrel (the ASP.NET web server) and `HttpClient`.
* Application-specific telemetry that's emitted by your code.

=== Observability approaches in .NET

There are a few different ways to achieve observability in .NET applications:

:dotnet-eventpipe: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventpipe
:dotnet-monitor: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-monitor
:dotnet-host-startup-hook: https://github.com/dotnet/runtime/blob/main/docs/design/features/host-startup-hook.md
:opentelemetry-dotnet-instrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/README.md

* Explicitly in code, by referencing and using a library such as OpenTelemetry.
+
If you have access to the source code and can rebuild the app, then this is the most powerful and configurable mechanism.

* Out-of-process using {dotnet-eventpipe}[EventPipe].
+
Tools such as {dotnet-monitor}[dotnet-monitor] can listen to logs and metrics and then process them without affecting any code.

* {dotnet-host-startup-hook}[Using a startup hook], assemblies can be injected into the process that can then collect instrumentation.
+
An example of this approach is {opentelemetry-dotnet-instrumentation}[OpenTelemetry .NET Automatic Instrumentation].

=== What is OpenTelemetry

https://opentelemetry.io/[OpenTelemetry] (OTel) is a cross-platform, open standard for collecting and emitting telemetry data. OpenTelemetry includes:

* https://opentelemetry.io/docs/concepts/instrumentation/manual/[APIs] for libraries to use to record telemetry data as code is running.
* https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md[APIs] that app developers use to configure what portion of the recorded data will be sent across the network, where it will be sent to, and how it may be filtered, buffered, enriched, and transformed.
* https://github.com/open-telemetry/semantic-conventions[Semantic conventions] provide guidance on naming and content of telemetry data. It is important for the apps that produce telemetry data and the tools that receive the data to agree on what different kinds of data means and what sorts of data are useful so that the tools can provide effective analysis.
* An interface for https://opentelemetry.io/docs/concepts/components/#exporters[exporters]. Exporters are plugins that allow telemetry data to be transmitted in specific formats to different telemetry backends.
* https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/README.md[OTLP wire protocol] is a vendor neutral network protocol option for transmitting telemetry data. Some tools and vendors support this protocol in addition to pre-existing proprietary protocols they may have.

Using OTel enables the use of a wide variety of APM systems including open-source systems such as https://prometheus.io/[Prometheus] and https://grafana.com/oss/grafana/[Grafana], https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview?tabs=net[Azure Monitor] - Microsoft's APM product in Azure, or from the many https://opentelemetry.io/ecosystem/vendors/[APM vendors] that partner with OpenTelemetry.

There are OpenTelemetry implementations for most languages and platforms, including .NET.

=== OpenTelemetry packages

OpenTelemetry in .NET is implemented as a series of NuGet packages that form a couple of categories:

* Core API
* Instrumentation - these packages collect instrumentation from the runtime and common libraries.
* Exporters - these interface with APM systems such as Prometheus, Jaeger, and OTLP.

The following table describes the main packages.

[%header,cols="1,3"]
|===
|Package Name
|Description

|OpenTelemetry
|Main library that provides the core OTEL functionality

|OpenTelemetry.Instrumentation.AspNetCore
|Instrumentation for ASP.NET Core and Kestrel

|OpenTelemetry.Instrumentation.GrpcNetClient
|Instrumentation for gRPC Client for tracking outbound gRPC calls

|OpenTelemetry.Instrumentation.Http
|Instrumentation for HttpClient and HttpWebRequest to track outbound HTTP calls

|OpenTelemetry.Instrumentation.SqlClient
|Instrumentation for SqlClient used to trace database operations

|OpenTelemetry.Exporter.Console
|Exporter for the console, commonly used to diagnose what telemetry is being exported

|OpenTelemetry.Exporter.OpenTelemetryProtocol
|Exporter using the OTLP protocol

|OpenTelemetry.Exporter.Prometheus.AspNetCore
|Exporter for Prometheus implemented using an ASP.NET Core endpoint

|OpenTelemetry.Exporter.Zipkin
|Exporter for Zipkin tracing
|===

=== Example: Use Prometheus, Grafana and Jaeger
// todo

// This example uses Prometheus for metrics collection, Grafana for creating a dashboard, and Jaeger to show distributed tracing.



[bibliography]
== References

* [[[opentelemetry-net-reaches-v1-0,1]]] https://devblogs.microsoft.com/dotnet/opentelemetry-net-reaches-v1-0/
* [[[otel,2]]] https://opentelemetry.io/
* [[[otel-docs,3]]] https://opentelemetry.io/docs/
* [[[otel-observability-primer,4]]] https://opentelemetry.io/docs/concepts/observability-primer/
* [[[otel-dotnet,5]]] https://learn.microsoft.com/en-us/dotnet/core/diagnostics/observability-with-otel
