= Intro to SQL Server Database
:page-layout: post
:page-categories: ['database']
:page-tags: ['database', 'sqlserver']
:page-date: 2023-04-06 10:14:18 +0800
:page-revdate: 2023-04-06 10:14:18 +0800
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

== Deploy and connect to SQL Server Linux containers

:docker-hub-microsoft-mssql-server: https://hub.docker.com/_/microsoft-mssql-server
:sqldb-troubleshooting: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-troubleshooting?view=sql-server-ver16

In this quickstart, you'll use Docker to pull and run the SQL Server 2022 (16.x) Linux container image, {docker-hub-microsoft-mssql-server}[mssql-server-linux]. Then you can connect with *sqlcmd* to create your first database and run queries.

=== Pull and run the SQL Server Linux container image

. Pull the SQL Server 2022 (16.x) Linux container image from the Microsoft Container Registry.
+
[source,bash]
----
sudo docker pull mcr.microsoft.com/mssql/server:2022-latest
----

. To run the Linux container image with Docker, you can use the following command from a bash shell or elevated PowerShell command prompt.
+
NOTE: The `SA_PASSWORD` environment variable is deprecated. Please use `MSSQL_SA_PASSWORD` instead.
+
[source,shell]
----
sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>" \
   -p 1433:1433 --name sql1 --hostname sql1 \
   -d \
   mcr.microsoft.com/mssql/server:2022-latest
----
+
Your password should follow the SQL Server default password policy, otherwise the container can't set up SQL Server and will stop working. By default, the password must be at least eight characters long and contain characters from three of the following four sets: uppercase letters, lowercase letters, base-10 digits, and symbols. 
+
By default, this quickstart creates a container with the Developer edition of SQL Server. The process for running production editions in containers is slightly different.
+

. To view your Docker containers, use the `docker ps` command.
+
[source,shell]
----
docker ps
----
+
You should see output similar to the following:
+
[source,console]
----
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS        PORTS                                       NAMES
274554ac9f0d   mcr.microsoft.com/mssql/server:2022-latest   "/opt/mssql/bin/perm…"   42 seconds ago   Up 1 second   0.0.0.0:1433->1433/tcp, :::1433->1433/tcp   sql1
----

. If the `STATUS` column shows a status of `Up`, then SQL Server is running in the container and listening on the port specified in the `PORTS` column. If the `STATUS` column for your SQL Server container shows `Exited`, see the {sqldb-troubleshooting}[Troubleshooting section of the configuration guide]. 

=== Connect to SQL Server

The following steps use the SQL Server command-line tool, sqlcmd, inside the container to connect to SQL Server.

. Use the `docker exec -it` command to start an interactive bash shell inside your running container. In the following example `sql1` is name specified by the `--name` parameter when you created the container.
+
[source,shell]
----
sudo docker exec -it sql1 "bash"
----

. Once inside the container, connect locally with *sqlcmd*, using its full path.
+
[source,shell]
----
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "<YourStrong@Passw0rd>"
----
+
TIP: You can omit the password on the command-line to be prompted to enter it. Here's an example:
+
[source,shell]
----
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA
----

. If successful, you should get to a *sqlcmd* command prompt: `1>`.

=== Create and query data

The following sections walk you through using *sqlcmd* and Transact-SQL to create a new database, add data, and run a query.

==== Create a new database

The following steps create a new database named `TestDB`.

. From the sqlcmd command prompt, paste the following Transact-SQL command to create a test database:
+
[source,sql]
----
CREATE DATABASE TestDB;
----

. On the next line, write a query to return the name of all of the databases on your server:
+
[source,sql]
----
SELECT Name from sys.databases;
----

. The previous two commands weren't run immediately. Type `GO` on a new line to run the previous commands:
+
[source,sql]
----
GO
----

==== Insert data

Next create a new table, Inventory, and insert two new rows.

. From the _sqlcmd_ command prompt, switch context to the new _TestDB_ database:
+
[source,sql]
----
USE TestDB;
----

. Create new table named `Inventory`:
+
[source,sql]
----
CREATE TABLE Inventory (id INT, name NVARCHAR(50), quantity INT);
----

. Insert data into the new table:
+
[source,sql]
----
INSERT INTO Inventory VALUES (1, 'banana', 150); INSERT INTO Inventory VALUES (2, 'orange', 154);
----

. Type `GO` to run the previous commands:
+
[source,sql]
----
GO
----

==== Select data

Now, run a query to return data from the `Inventory` table.

. From the _sqlcmd_ command prompt, enter a query that returns rows from the `Inventory` table where the quantity is greater than 152:
+
[source,sql]
----
SELECT * FROM Inventory WHERE quantity > 152;
----

. Run the command:
+
[source,sql]
----
GO
----

. Exit the sqlcmd command prompt
+
To end your sqlcmd session, type `QUIT`:
+
[source,sql]
----
QUIT
----

. To exit the interactive command-prompt in your container, type `exit`. Your container continues to run after you exit the interactive bash shell.

== Databases

A _database_ in _SQL Server_ is made up of a collection of _tables_ that stores a specific set of structured data. A tableontains a collection of _rows_, also referred to as _records_ or _tuples_, and _columns_, also referred to as _attributes_. Each column in the table is designed to store a certain type of information, for example, dates, names, dollar amounts, and numbers.

=== Basic Information about Databases

:sqldb-tables: https://learn.microsoft.com/en-us/sql/relational-databases/tables/tables?view=sql-server-ver16
:sqldb-files-filegroups: https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-files-and-filegroups?view=sql-server-ver16
:sqldb-tsql: https://learn.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-ver16
:sqldb-authn: https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/principals-database-engine?view=sql-server-ver16
:ssms: https://learn.microsoft.com/en-us/sql/ssms/sql-server-management-studio-ssms?view=sql-server-ver16

A computer can have one or more than one instance of _SQL Server_ installed. Each instance of SQL Server can contain one or many _databases_. Within a database, there are one or many object ownership groups called _schemas_. Within each schema there are database objects such as _tables_, _views_, and _stored procedures_. Some objects such as certificates and asymmetric keys are contained within the database, but are not contained within a schema. For more information about creating tables, see {sqldb-tables}[Tables].

SQL Server databases are stored in the file system in _files_. Files can be grouped into _filegroups_. For more information about files and filegroups, see {sqldb-file-filegroups}[Database Files and Filegroups].

When people gain access to an instance of SQL Server they are identified as a _login_. When people gain access to a database they are identified as a _database user_. A database user can be based on a login. If _contained databases_ are enabled, a database user can be created that is not based on a login. For more information about users, see `CREATE USER` ({sqldb-tsql}[Transact-SQL]).

A user that has access to a database can be given _permission_ to access the objects in the database. Though permissions can be granted to _individual users_, we recommend creating _database roles_, adding the database users to the roles, and then grant access permission to the roles. Granting permissions to roles instead of users makes it easier to keep permissions consistent and understandable as the number of users grow and continually change. For more information about roles permissions, see `CREATE ROLE` ({sqldb-tsql}[Transact-SQL]) and {sqldb-authn}[Principals (Database Engine)].

=== Working with Databases

Most people who work with databases use the _SQL Server Management Studio_ tool. The Management Studio tool has a graphical user interface for creating databases and the objects in the databases. Management Studio also has a query editor for interacting with databases by writing Transact-SQL statements. Management Studio can be installed from the SQL Server installation disk, or downloaded from MSDN. For more information about SQL Server Management Studio tool, see {ssms}[SQL Server Management Studio (SSMS)].

=== System Databases

SQL Server includes the following system databases.

:master-database: https://learn.microsoft.com/en-us/sql/relational-databases/databases/master-database?view=sql-server-ver16
:msdb-database: https://learn.microsoft.com/en-us/sql/relational-databases/databases/msdb-database?view=sql-server-ver16
:model-database: https://learn.microsoft.com/en-us/sql/relational-databases/databases/model-database?view=sql-server-ver16
:resource-database: https://learn.microsoft.com/en-us/sql/relational-databases/databases/resource-database?view=sql-server-ver16
:tempdb-database: https://learn.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver16

[%header,cols="1,5"]
|===
|System database
|Description

|{master-database}[master Database]
|Records all the system-level information for an instance of SQL Server.

|{msdb-database}[msdb Database]
|Is used by SQL Server Agent for scheduling alerts and jobs.

|{model-database}[model Database]
|Is used as the template for all databases created on the instance of SQL Server. Modifications made to the model database, such as database size, collation, recovery model, and other database options, are applied to any databases created afterward.

|{resource-database}[Resource Database]
|Is a read-only database that contains system objects that are included with SQL Server. System objects are physically persisted in the Resource database, but they logically appear in the sys schema of every database.

|{tempdb-database}[tempdb Database]
|Is a workspace for holding temporary objects or intermediate result sets.
|===

NOTE: For Azure SQL Database single databases and elastic pools, only _master_ Database and _tempdb_ Database apply.

==== master Database

The _master database_ records all the system-level information for a SQL Server system. This includes instance-wide metadata such as logon accounts, endpoints, linked servers, and system configuration settings.

In SQL Server, system objects are no longer stored in the _master_ database; instead, they are stored in the _Resource database_.

Also, _master_ is the database that records the existence of all other databases and the location of those database files and records the initialization information for SQL Server. Therefore, SQL Server cannot start if the master database is unavailable.

=== Contained Databases

A _contained database_ is a database that is isolated from other databases and from the instance of SQL Server that hosts the database. SQL Server helps user to isolate their database from the instance in 4 ways.

* Much of the metadata that describes a database is maintained in the database. (In addition to, or instead of, maintaining metadata in the master database.)

* All metadata are defined using the same collation.

* User authentication can be performed by the database, reducing the databases dependency on the logins of the instance of SQL Server.

* The SQL Server environment (DMV's, XEvents, etc.) reports and can act upon containment information.


=== Database Files and Filegroups

At a minimum, every SQL Server database has two operating system files: a _data file_ and a _log file_. Data files contain data and objects such as tables, indexes, stored procedures, and views. Log files contain the information that is required to recover all transactions in the database. Data files can be grouped together in filegroups for allocation and administration purposes.

==== Database Files

SQL Server databases have three types of files, as shown in the following table.

[%header,cols="1,5"]
|===
|File
|Description

|Primary
|Contains startup information for the database and points to the other files in the database. Every database has one primary data file. The recommended file name extension for primary data files is _.mdf_.

|Secondary
|Optional user-defined data files. Data can be spread across multiple disks by putting each file on a different disk drive. The recommended file name extension for secondary data files is _.ndf_.

|Transaction Log
|The log holds information used to recover the database. There must be at least one log file for each database. The recommended file name extension for transaction logs is _.ldf_.
|===

For example, a simple database named *Sales* has one primary file that contains all data and objects and a log file that contains the transaction log information. A more complex database named *Orders* can be created that includes one primary file and five secondary files. The data and objects within the database spread across all six files, and the four log files contain the transaction log information.

By default, the data and transaction logs are put on the same drive and path to handle single-disk systems. This choice may not be optimal for production environments. We recommend that you _put data and log files on separate disks_.

==== Logical and Physical File Names

:sqldb-file-locations: https://learn.microsoft.com/en-us/sql/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server?view=sql-server-ver16

SQL Server files have two file name types:

*logical_file_name*: The _logical_file_name_ is the name used to refer to the physical file in all Transact-SQL statements. The logical file name must comply with the rules for SQL Server identifiers and must be unique among logical file names in the database.

*os_file_name*: The _os_file_name_ is the name of the physical file including the directory path. It must follow the rules for the operating system file names.

When multiple instances of SQL Server are running on a single computer, each instance receives a different default directory to hold the files for the databases created in the instance. For more information, see {sqldb-file-locations}[File Locations for Default and Named Instances of SQL Server].

== Database Engine Permissions and Principals

_Permissions_ in the Database Engine are managed at the _server level_ through logins and server roles, and at the _database level_ through database users and database roles.

The model for SQL Database exposes the same system within each database, but the server level permissions aren't available. This article reviews some basic security concepts and then describes a typical implementation of the permissions.

=== Security principals

_Security principal_ is the official name of the identities that use SQL Server and that can be assigned permission to take actions. They are usually people or groups of people, but can be other entities that pretend to be people.

The security principals can be created and managed using the Transact-SQL listed, or by using SQL Server Management Studio.

==== Logins

:choose-an-authentication-mode: https://learn.microsoft.com/en-us/sql/relational-databases/security/choose-an-authentication-mode?view=sql-server-ver16

_Logins_ are individual user accounts for logging on to the SQL Server Database Engine. SQL Server and SQL Database support logins based on _Windows authentication_ and logins based on _SQL Server authentication_.

For information about the two types of logins, see {choose-an-authentication-mode}[Choose an Authentication Mode].

==== Fixed server roles

:alter-server-role-transact-sql: https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-server-role-transact-sql?view=sql-server-ver16

In SQL Server, _fixed server roles_ are a set of pre-configured roles that provide convenient group of server-level permissions. Logins can be added to the roles using the `ALTER SERVER ROLE ... ADD MEMBER` statement.

For more information, see {alter-server-role-transact-sql}[ALTER SERVER ROLE (Transact-SQL)].

SQL Database doesn't support the fixed server roles, but has two roles in the `master` database (`dbmanager` and `loginmanager`) that act like server roles.

==== User-defined server roles

In SQL Server, you can create your own server roles and assign server-level permissions to them. Logins can be added to the server roles using the `ALTER SERVER ROLE ... ADD MEMBER` statement.

For more information, see {alter-server-role-transact-sql}[ALTER SERVER ROLE (Transact-SQL)].

SQL Database doesn't support the user-defined server roles.

==== Database users

:contained-database-users-making-your-database-portable: https://learn.microsoft.com/en-us/sql/relational-databases/security/contained-database-users-making-your-database-portable?view=sql-server-ver16
:create-user-transact-sql: https://learn.microsoft.com/en-us/sql/t-sql/statements/create-user-transact-sql?view=sql-server-ver16

Logins are granted access to a database by creating a _database user_ in a database and mapping that database user to sign in. Typically the database user name is the same as the login name, though it doesn't have to be the same.

Each database user maps to a single login. A login can be mapped to only one user in a database, but can be mapped as a database user in several different databases.

Database users can also be created that don't have a corresponding login. These users are called _contained database users_. Microsoft encourages the use of contained database users because it makes it easier to move your database to a different server. Like a login, a contained database user can use either Windows authentication or SQL Server authentication. For more information, see {contained-database-users-making-your-database-portable}[Contained Database Users - Making Your Database Portable].

There are 12 types of users with slight differences in how they authenticate, and who they represent. To see a list of users, see {create-user-transact-sql}[CREATE USER (Transact-SQL)].

==== Fixed database roles

:alter-role-transact-sql: https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-role-transact-sql?view=sql-server-ver16

_Fixed database roles_ are a set of pre-configured roles that provide convenient group of database-level permissions. Database users and user-defined database roles can be added to the fixed database roles using the `ALTER ROLE ... ADD MEMBER` statement.

For more information, see {alter-role-transact-sql}[ALTER ROLE (Transact-SQL)].

==== User-defined database roles

Users with the `CREATE ROLE` permission can create new _user-defined database roles_ to represent groups of users with common permissions. Typically permissions are granted or denied to the entire role, simplifying permissions management and monitoring. Database users can be added to the database roles by using the `ALTER ROLE ... ADD MEMBER` statement.

For more information, see {alter-role-transact-sql}[ALTER ROLE (Transact-SQL)].

==== Other principals

:create-a-database-user: https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/create-a-database-user?view=sql-server-ver16

Additional security principals not discussed here include application roles, and logins and users based on certificates or asymmetric keys.

For a graphic showing the relationships between Windows users, Windows groups, logins, and database users, see {create-a-database-user}[Create a Database User].

=== Assign permissions

:permissions-database-engine: https://learn.microsoft.com/en-us/sql/relational-databases/security/permissions-database-engine?view=sql-server-ver16

Most permission statements have the format:

[source,sql]
----
AUTHORIZATION PERMISSION ON SECURABLE::NAME TO PRINCIPAL;
----

* `AUTHORIZATION` must be `GRANT`, `REVOKE` or `DENY`.

* The `PERMISSION` establishes what action is allowed or prohibited. The exact number of permissions differs between SQL Server and SQL Database. The permissions are listed in the article {permissions-database-engine}[Permissions (Database Engine)] and in the chart referenced below.

* `ON SECURABLE::NAME` is the type of securable (server, server object, database, or database object) and its name. Some permissions don't require `ON SECURABLE::NAME` because it is unambiguous or inappropriate in the context. For example, the `CREATE TABLE` permission doesn't require the `ON SECURABLE::NAME` clause (`GRANT CREATE TABLE TO Mary`; allows Mary to create tables).

* `PRINCIPAL` is the security principal (login, user, or role) which receives or loses the permission. Grant permissions to roles whenever possible.

The following example grant statement, grants the `UPDATE` permission on the `Parts` table or view that is contained in the `Production` schema to the role named `PartsTeam`:

[source,sql]
----
GRANT UPDATE ON OBJECT::Production.Parts TO PartsTeam;
----

The following example grant statement grants the UPDATE permission on the Production schema, and by extension on any table or view contained within this schema to the role named ProductionTeam, which is a more effective and salable approach to assigning permissions than on individual object-level:
SQL

[source,sql]
----
GRANT UPDATE ON SCHEMA::Production TO ProductionTeam;
----

Permissions are granted to security principals (logins, users, and roles) by using the `GRANT` statement. Permissions are explicitly denied by using the `DENY` command. A previously granted or denied permission is removed by using the `REVOKE` statement. Permissions are cumulative, with the user receiving all the permissions granted to the user, login, and any group memberships; however any permission denial overrides all grants.

[TIP]
====
A common mistake is to attempt to remove a `GRANT` by using `DENY` instead of `REVOKE`. This can cause problems when a user receives permissions from multiple sources; which is quite common. The following example demonstrates the principal.
====

The Sales group receives `SELECT` permissions on the OrderStatus table through the statement `GRANT SELECT ON OBJECT::OrderStatus TO Sales;`. User Jae is a member of the Sales role. Jae has also been granted `SELECT` permission to the `OrderStatus` table under their own user name through the statement `GRANT SELECT ON OBJECT::OrderStatus TO Jae`;. Presume the administer wishes to remove the `GRANT` to the Sales role.

* If the administrator correctly executes `REVOKE SELECT ON OBJECT::OrderStatus TO Sales`;, then Jae will retain `SELECT` access to the OrderStatus table through their individual `GRANT` statement.

* If the administrator incorrectly executes `DENY SELECT ON OBJECT::OrderStatus TO Sales;` then Jae, as a member of the Sales role, will be denied the `SELECT` permission because the `DENY` to Sales overrides their individual `GRANT`.

:permissions-or-securables-page: https://learn.microsoft.com/en-us/sql/relational-databases/security/permissions-or-securables-page?view=sql-server-ver16

[NOTE]
====
Permissions can be configured using Management Studio. Find the securable in Object Explorer, right-click the securable, and then select *Properties*. Select the *Permissions* page.

For help on using the permission page, see {permissions-or-securables-page}[Permissions or Securables Page].
====

=== Permission hierarchy

Permissions have a parent/child hierarchy. That is, if you grant _SELECT_ permission on a database, that permission includes _SELECT_ permission on all (child) schemas in the database. If you grant _SELECT_ permission on a schema, it includes _SELECT_ permission on all the (child) tables and views in the schema. The permissions are transitive; that is, if you grant _SELECT_ permission on a database, it includes _SELECT_ permission on all (child) schemas, and all (grandchild) tables and views.

Permissions also have covering permissions. The _CONTROL_ permission on an object, normally gives you all other permissions on the object.

Because both the parent/child hierarchy and the covering hierarchy can act on the same permission, the permission system can get complicated. For example, let's take a table (Region), in a schema (Customers), in a database (SalesDB).

* `CONTROL` permission on table Region includes all the other permissions on the table Region, including `ALTER`, `SELECT`, `INSERT`, `UPDATE`, `DELETE`, and some other permissions.

* `SELECT` on the Customers schema that owns the Region table includes the `SELECT` permission on the Region table.

So `SELECT` permission on the Region table can be achieved through any of these six statements:

[source,sql]
----
GRANT SELECT ON OBJECT::Region TO Jae;

GRANT CONTROL ON OBJECT::Region TO Jae;

GRANT SELECT ON SCHEMA::Customers TO Jae;

GRANT CONTROL ON SCHEMA::Customers TO Jae;

GRANT SELECT ON DATABASE::SalesDB TO Jae;

GRANT CONTROL ON DATABASE::SalesDB TO Jae;
----

=== Monitor permissions

:security-catalog-views-transact-sql: https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/security-catalog-views-transact-sql?view=sql-server-ver16

The following views return security information.

* The logins and user-defined server roles on a server can be examined by using the `sys.server_principals` view. This view isn't available in SQL Database.

* The users and user-defined roles in a database can be examined by using the `sys.database_principals` view.

* The permissions granted to logins and user-defined fixed server roles can be examined by using the `sys.server_permissions` view. This view isn't available in SQL Database.

* The permissions granted to users and user-defined fixed database roles can be examined by using the `sys.database_permissions` view.

* Database role membership can be examined by using the `sys.database_role_members` view.

* Server role membership can be examined by using the `sys.server_role_members` view. This view isn't available in SQL Database.

* For additional security related views, see {security-catalog-views-transact-sql}[Security Catalog Views (Transact-SQL)].

=== Principals (Database Engine)

_Principals_ are entities that can request SQL Server resources. Like other components of the SQL Server authorization model, principals can be arranged in a hierarchy. The scope of influence of a principal depends on the scope of the definition of the principal: Windows, server, database; and whether the principal is indivisible or a collection. A _Windows Login_ is an example of an indivisible principal, and a _Windows Group_ is an example of a principal that is a collection. Every principal has a _security identifier (SID)_.

==== SQL Server-level principals

* SQL Server authentication Login
* Windows authentication login for a Windows user
* Windows authentication login for a Windows group
* Azure Active Directory authentication login for a AD user
* Azure Active Directory authentication login for a AD group
* Server Role

==== Database-level principals

* Database User (There are 12 types of users. For more information, see CREATE USER.)
* Database Role
* Application Role

==== sa Login

The SQL Server `sa` login is a server-level principal. By default, it is created when an instance is installed.

Beginning in SQL Server 2005 (9.x), the default database of sa is master. This is a change of behavior from earlier versions of SQL Server.

The `sa` login is a member of the `sysadmin` fixed server-level role.

The `sa` login has all permissions on the server and cannot be limited.

The `sa` login cannot be dropped, but it can be disabled so that no one can use it.

==== dbo User and dbo Schema

The `dbo` user is a special user principal in each database.

All SQL Server administrators, members of the `sysadmin` fixed server role, `sa` login, and owners of the database, enter databases as the `dbo` user.

The `dbo` user has all permissions in the database and cannot be limited or dropped.

`dbo` stands for database owner, but the `dbo` user account is not the same as the `db_owner` fixed database role, and the `db_owner` fixed database role is not the same as the user account that is recorded as the owner of the database.

The `dbo` user owns the `dbo` schema. The `dbo` schema is the default schema for all users, unless some other schema is specified. The `dbo` schema cannot be dropped.

==== public Server Role and Database Role

Every login belongs to the `public` fixed server role, and every database user belongs to the `public` database role.

When a login or user has not been granted or denied specific permissions on a securable, the login or user inherits the permissions granted to public on that securable.

The `public` fixed server role and the `public` fixed database role cannot be dropped. However you can revoke permissions from the `public` roles.

There are many permissions that are assigned to the `public` roles by default. Most of these permissions are needed for routine operations in the database; the type of things that everyone should be able to do.

Be careful when revoking permissions from the public login or user, as it will affect all logins/users. Generally you should not deny permissions to public, because the deny statement overrides any grant statements you might make to individuals.

== SQL Server Utilities Statements - GO

SQL Server provides commands that are not Transact-SQL statements, but are recognized by the *sqlcmd* and *osql* utilities and SQL Server Management Studio Code Editor. These commands can be used to facilitate the readability and execution of batches and scripts.

`GO` signals the end of a batch of Transact-SQL statements to the SQL Server utilities.

*Syntax*

[source,sql]
----
GO [count]  
----

*Arguments*

_count_

Is a positive integer. The batch preceding GO will execute the specified number of times.

*Remarks*

`GO` is not a Transact-SQL statement; it is a command recognized by the *sqlcmd* and *osql* utilities and SQL Server Management Studio Code editor.

SQL Server utilities interpret `GO` as a signal that they should send the current batch of Transact-SQL statements to an instance of SQL Server. The current batch of statements is composed of all statements entered since the last `GO`, or since the start of the ad hoc session or script if this is the first `GO`.

A Transact-SQL statement cannot occupy the same line as a `GO` command. However, the line can contain comments.

Users must follow the rules for batches. For example, any execution of a stored procedure after the first statement in a batch must include the `EXECUTE` keyword. The scope of local (user-defined) variables is limited to a batch, and cannot be referenced after a `GO` command.

[source,sql]
----
USE AdventureWorks2012;  
GO  
DECLARE @MyMsg VARCHAR(50)  
SELECT @MyMsg = 'Hello, World.'  
GO -- @MyMsg is not valid after this GO ends the batch.  
  
-- Yields an error because @MyMsg not declared in this batch.  
PRINT @MyMsg  
GO
  
SELECT @@VERSION;  
-- Yields an error: Must be EXEC sp_who if not first statement in   
-- batch.  
sp_who  
GO  
----

SQL Server applications can send multiple Transact-SQL statements to an instance of SQL Server for execution as a batch. The statements in the batch are then compiled into a single _execution plan_. Programmers executing ad hoc statements in the SQL Server utilities, or building scripts of Transact-SQL statements to run through the SQL Server utilities, use `GO` to signal the end of a batch.

Applications based on the ODBC or OLE DB APIs receive a syntax error if they try to execute a `GO` command. The SQL Server utilities never send a `GO` command to the server.

Do not use a semicolon as a statement terminator after `GO`.

[source,sql]
----
-- Yields an error because ; is not permitted after GO  
SELECT @@VERSION;  
GO; 
----

== References

* https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver16&pivots=cs1-bash
* https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&preserve-view=true&pivots=cs1-bash
* https://learn.microsoft.com/en-us/sql/relational-databases/databases/databases?view=sql-server-ver16
* https://learn.microsoft.com/en-us/sql/relational-databases/databases/contained-databases?view=sql-server-ver16
* https://learn.microsoft.com/en-us/sql/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server?view=sql-server-ver16
* https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/getting-started-with-database-engine-permissions?view=sql-server-ver16
* https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/principals-database-engine?view=sql-server-ver16
* https://learn.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-ver16
* https://learn.microsoft.com/en-us/sql/t-sql/tutorial-writing-transact-sql-statements?view=sql-server-ver16
* https://learn.microsoft.com/en-us/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?view=sql-server-ver16
