= TCP/IP: TCP Congestion Control
:page-layout: post
:page-categories: ['networking']
:page-tags: ['networking', 'tcp']
:page-date: 2023-02-07 15:13:37 +0800
:page-revdate: 2023-02-07 15:13:37 +0800
:toc: preamble
:toclevels: 4
:sectnums:
:sectnumlevels: 4

When a router is forced to discard data because it cannot handle the arriving traffic rate, is called *congestion*. A router is said to be _congested_ when it is in this state, and even a single connection can drive one or more routers into congestion.

Left unaddressed, congestion can cause the performance of a network to be reduced so badly that it becomes unusable. In the very worst cases, it is said to be in a state of _congestion collapse_.

To either avoid or at least react effectively to mitigate this situation, each TCP implements *congestion control procedures*.

Congestion control is a set of behaviors determined by algorithms that each TCP implements in an attempt to prevent the network from being overwhelmed by too large an aggregate offered traffic load.

The basic approach is to have TCP slow down when it has reason to believe the network is about to be congested (or is already so congested that routers are discarding packets).

The challenge is to determine exactly when and how TCP should slow down, and when it can speed up again.

