= Python Learning Notes
:page-layout: post
:page-categories: ['python']
:page-tags: ['python']
:page-date: 2024-05-17 10:29:20 +0800
:page-revdate: 2024-05-17 10:29:20 +0800
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

== Running Python

* Using the interactive interpreter (shell)
+
```console
$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
+
```py
>>> 2+2
4
>>> quit()
```

* Using python files
+
```console
$ echo 'print(2+2)' > test.py
$ python3 test.py
4
```

* Using python files with shebang
+
[TIP]
====
In computing, a https://en.wikipedia.org/wiki/Shebang_(Unix)[*shebang*] is the character sequence consisting of the characters number sign and exclamation mark (`#!`) at the beginning of a script. It is also called sharp-exclamation, sha-bang, *hashbang*, pound-bang, or hash-pling.

[.text-right]
-- From Wikipedia, the free encyclopedia
====
+
```console
$ cat <<EOF > test.py
> #!/usr/bin/env python3
> print(2+2)
> EOF
$ chmod +x test.py
$ ./test.py
4
```

== Indentations, comments, and multi-line expressions

* Python uses whitespace indentation (the recommended style, called PEP-8, is to use four spaces), rather than curly brackets or keywords, to delimit blocks.
+
--
** Don't use tabs, or mix tabs and spaces; it messes up the indent count.

** When designing the language that became Python, Guido van Rossum decided that the indentation itself was enough to define a program’s structure, and avoided typing all those parentheses and curly braces. Python is unusual in this use of white space to define program structure.
--
+
```py
disaster = True
if disaster:
    print("Woe!")
else:
    print("Whee!")
```

* A comment is marked by using the `#` (names: _hash_, _sharp_, _pound_, or or the sinister-sounding _octothorpe_) character; everything from that point on to the end of the current line is part of the comment.
+
```py
# 60 sec/min * 60 min/hr * 24 hr/day
seconds_per_day = 86400
```
+
```py
seconds_per_day = 86400 # 60 sec/min * 60 min/hr * 24 hr/day
```
+
```py
# Python does NOT
# have a multiline comment.
print("No comment: quotes make the # harmless.")
```

* Python allows to write expressions that span multiple lines within certain delimiters.

** In older versions of Python (pre-3.0), the backslash character (`\`) at the end of a line was used to indicate that the line continued on the next line, which  is no longer required in modern Python (versions 3.0 and above).
+
```py
# Example in older Python (not recommended)
long_expression = (1 + 2 + 3 + 4 + 5 + \
                  6 + 7 + 8 + 9 + 10)
```

** In modern Python, avoid using the continuation character (`\`) for line continuation, and utilize parentheses (`()`), brackets (`[]`), or braces (`[]`) for readability and structure in multi-line expressions.
+
```py
# Parentheses for complex calculations
long_calculation = (a * b +
                    c) * (d /
                          e - f)

# Brackets for multi-line lists or data structures
data = [
    "item1",
    "item2 with a longer description",
    "item3"
]

# Braces for multi-line dictionaries
person_info = {
    "name": "Alice",
    "age": 30,
    "hobbies": ["reading", "hiking"]
}
```

== Types, values, variables, and names

Python is a dynamically, strongly typed and garbage-collected programming language.

* In a dynamically typed language, the data type of a variable is NOT explicitly declared at the time of definition, and is determined at runtime.
+
```py
age = 30  # age is an integer (no need to declare the data type explicitly)
age = "thirty"  # age is now a string
```

* In a statically typed language, the data type of a variable MUST be declared at compile time and the compiler ensures type compatibility throughout the code.
+
```java
// In Java, declare the type of a variable before assigning a value.
int age = 30;  // age is declared as an integer
age = "thirty";  // error: incompatible types: String cannot be converted to int
```

* In a strongly typed language, the data type of a variable MUST be declared at the time of definition, and the compiler or interpreter enforces type safety.

* In Python, everything is ultimately an object, even data types like integers and strings, that has associated methods and attributes. During runtime, Python checks if the methods or attributes involved are compatible with the object's type.
+
```py
# Like dynamic languages, Python infers types based on assigned values.
name = "Alice"  # name is a string
name + 10  # This would cause a TypeError in Python (mixing string and number)
```
+
[TIP]
====
In computer programming, https://en.wikipedia.org/wiki/Duck_typing[duck typing] is an application of the duck test—"If it walks like a duck and it quacks like a duck, then it must be a duck"—to determine whether an object can be used for a particular purpose.

[.text-right]
-- From Wikipedia, the free encyclopedia
====

```py
bool # True, False

int # 47, 25000, 25_000, 0b0100_0000, 0o100, 0x40

float # 3.14, 2.7e5

complex # 3j, 5 + 9j

# In Python 3, strings are Unicode character sequences, not byte arrays.
str # 'alas', "alack", '''a verse attack'''

list # ['Winken', 'Blinken', 'Nod']
tuple # (2, 4, 8)

bytes # b'ab\xff'
bytearray # bytearray(...)

set # set([3, 5, 7])
frozenset # frozenset(['Elsa', 'Otto'])

dict # {'game': 'bingo', 'dog': 'dingo', 'drummer': 'Ringo'}
```

* In Python, variables are NOT places, just names, and a name is a _reference_ to an object rather than the object itself, which is a chunk of data that contains at least a _type_, a unique _id_, a _value_, and a _reference count_.
+
```py
>>> type(5.20)
<class 'float'>
>>> id(5.20)
140683748269744
>>> x = y = z = 0  # More than one variable name can be assigned a value at the same time
>>> sys.getrefcount(x)
1000000591
>>> del y
>>> sys.getrefcount(x)
1000000590
>>> del z
>>> sys.getrefcount(x)
1000000589
```

* A _class_ is the definition of an object, and "class" and "type" mean pretty much the same thing.
+
```py
>>> type(7)
<class 'int'>
>>> type(7) == int
True
>>> isinstance(7, int)
True
```

* Strings, tuples and lists are common built-in sequences, which are zero-based indexing and ordered collections that can store elements of any data types, except strings, which are sequences of characters themselves.
+
```py
# iteration
for item in ['meow', 'bark', 'moo']:
    print(item)
```
+
```py
# enumeration
for index, item in enumerate(['meow', 'bark', 'moo']):
    print(f'Index: {index}, Item: {item}')
```
+
```py
# comparisons
('meow', 'bark', 'moo') == ('meow', 'bark', 'moo')  # True
('meow', 'bark', 'moo') >= ('meow', 'bark')  # True
('meow', 'bark', 'moo') > ('meow', 'bark')  # True
```
+
```py
# `+`, `*`
('cat',) + ('dog', 'cattle')  # ('cat', 'dog', 'cattle')
('bark',) * 3  # ('bark', 'bark', 'bark')
```
+
```py
# unpacking
cat, dog, cattle = ('meow', 'bark', 'moo')
```
+
```py
# testing with `in`
'c' in 'cat'  # True
'meow' in ['cat', 'cattle', 'dog']  # False
```
+
```py
# indexing, and slicing a shallow copy subsequence:
hi = 'hello world!'
hi[-13], hi[12]  # IndexError: string index out of range

#   [:] extracts the entire sequence from start to end.
#   [ start :] specifies from the start offset to the end.
#   [: end ] specifies from the beginning to the end offset minus 1.
#   [ start : end ] indicates from the start offset to the end offset minus 1.
#   [ start : end : step ] extracts from the start offset to the end offset minus 1, skipping characters by step.
hi[:], hi[0:5], hi[:5], hi[:5:], hi[0:5:], hi[0:5:1]  # ('hello world!', 'hello', 'hello', 'hello', 'hello', 'hello')
len(hi), hi[-1], hi[-12], hi[11], hi[0]  # (12, '!', 'h', '!', 'h')
```

* In Python, truthiness and falsiness are used to check a value in a Boolean context:

** Truthy: Values that evaluate to `True`, which includes most non-zero numbers, non-empty strings, lists, dictionaries, and many objects.

** Falsy: Values that evaluate to `False`, which include `False`, zero numbers (`0`, `0.0`), empty strings (`""`), lists (`[]`), and tuples (`()`), and `None`.

* In Python, the logical operators `and`, `or`, `not` are used to combine Boolean values (`True`/`False`) or expressions that evaluate to Boolean values.
+
```py
letter = 'o'
if letter == 'a' or letter == 'e' or letter == 'i' or letter == 'o' or letter == 'u':
    print(letter, 'is a vowel')
else:
    print(letter, 'is not a vowel')
```

* `int()`, `float()`, `bin()`, `oct()`, `hex()`, `chr()`, and `ord()`
+
```py
int(True), int(False)  # (1, 0)
int(98.6), int(1.0e4)  # (98, 10_000)
int('99'), int('-23'), int('+12'), int('1_000_000')  # (99, -23, 12, 1_000_000)

int('10', 2), 'binary', int('10', 8), 'octal', int('10', 16), 'hexadecimal', int('10', 22), 'chesterdigital' 
# (2, 'binary', 8, 'octal', 16, 'hexadecimal', 22, 'chesterdigital') 

float(True), float(False)  # (1.0, 0.0)
float('98.6'), float('-1.5'), float('1.0e4')  # (98.6, -1.5, 10_000.0)

bin(65), oct(65), hex(65)  # ('0b1000001', '0o101', '0x41')

chr(65), ord('A')  # ('A', 65)

# Python also promotes booleans to integers or floats:
False + 0, True + 0, False + 0., True + 0.  # (0, 1, 0.0, 1.0)
```

== Strings

* UTF-8 is the standard text encoding in Python, Linux, and HTML.
+
Ken Thompson and Rob Pike, whose names will be familiar to Unix developers, designed the UTF-8 dynamic encoding scheme one night on a placemat in a New Jersey diner. It uses one to four bytes per Unicode character:
+
--
* One byte for ASCII
* Two bytes for most Latin-derived (but not Cyrillic) languages
* Three bytes for the rest of the basic multilingual plane
* Four bytes for the rest, including some Asian languages and symbols
--
+
```py
cafe = 'café'

# len() function on string counts Unicode characters, not bytes:
len(cafe)  # 4

cafe_bytes = cafe.encode()  # b'caf\xc3\xa9'

# len() returns the number of bytes:
len(cafe_bytes)  # 5

cafe_text = cafe_bytes.decode()  # 'café'
```

* Strings are created by enclosing characters in matching single, double, or triple quotes:
+
```py
'Snap'
"Crackle"
"'Nay!' said the naysayer. 'Neigh?' said the horse."
'The rare double quote in captivity: ".'
'''Boom!'''
"""Eek!"""
```

* Triple quotes are very useful to create multiline strings, like this classic poem from Edward Lear:
+
```py
poem = '''There was a Young Lady of Norway,
    Who casually sat in a doorway;
    When the door squeezed her flat,
    She exclaimed, "What of that?"
    This courageous Young Lady of Norway.'''
print(poem)
```
+
```console
There was a Young Lady of Norway,
    Who casually sat in a doorway;
    When the door squeezed her flat,
    She exclaimed, "What of that?"
    This courageous Young Lady of Norway.
```
+
```py
# the line ending characters, and leading or trailing spaces are preserved as below:
'There was a Young Lady of Norway,\n    Who casually sat in a doorway;\n    When the door squeezed her flat,\n    She exclaimed, "What of that?"\n    This courageous Young Lady of Norway.'
```

* Escape with `\`, combine by using `+`, duplicate with `*`
+
```py
hi = 'Na ' 'Na ' 'Na ' 'Na ' \ # literal strings (not string variables) just one after the other
    + 'Hey ' * 4 \
    + '\\' + '\t' + 'Goodbye.'
print(hi)  # Na Na Na Na Hey Hey Hey Hey \	Goodbye.
```

* Python has a few special types of strings, indicated by a letter before the first quote.

** `f` or `F` starts an _f-string_, used for formatting.
+
```py
thing = 'wereduck'
place = 'werepond'
print(f'The {thing} is in the {place}')  # 'The wereduck is in the werepond'
```

** `r` or `R` starts a raw string, used to prevent escape sequences in the string.
+
```py
info = r'Type a \n to get a new line'  # info = 'Type a \\n to get a new line'
```
+
```py
# raw string does not undo any real (not `\n`) newlines:
poem = r'''Boys and girls, come out to play.
The moon doth shine as bright as day.'''  # 'Boys and girls, come out to play.\nThe moon doth shine as bright as day.'
print(poem)
```
+
```console
Boys and girls, come out to play.
The moon doth shine as bright as day.
```

** `fr` (or `FR`, `Fr`, or `fR`), the combination, that starts a raw f-string.
+
```py
hello = 'Hello'
world = '世界'
print(fr'{hello}, {world}!')  # Hello, 世界!
```

** `u` starts a Unicode string, which is the same as a plain string.
+
TIP: Python 3 strings are Unicode character sequences, not byte arrays.
+
```py
hi = u'Hello, 世界!'  # same as: hi = 'Hello, 世界!'
```

** `b` starts a value of type bytes.
+
```py
ip = [20, 205, 243, 166]
bytes(ip)  # b'\x14\xcd\xf3\xa6'
```

* Python has three ways of formatting strings.
+
```py
actor = 'Richard Gere'
cat = 'Chester'
weight = 28
```
+
```py
# old style (supported in Python 2 and 3): format_string % data
"My wife's favorite actor is %s" % actor  # "My wife's favorite actor is Richard Gere"
"Our cat %s weighs %d pounds" % (cat, weight)  # 'Our cat Chester weighs 28 pounds'
```
+
```py
# new style (Python 2.6 and up): format_string.format(data)
"Our cat {} weighs {} pounds".format(cat, weight)  # 'Our cat Chester weighs 28 pounds'
```
+
```py
# f-strings (Python 3.6 and up): f, F
f"Our cat {cat} weighs {weight} pounds"  # 'Our cat Chester weighs 28 pounds'
```

== If, while, and for

* In Python (version 3.8 and above), the walrus operator (`:=`, formally known as the assignment expression operator) combines assignment and expression evaluation in a single line.
+
```py
tweet_limit = 280
tweet_string = "Blah" * 50
if diff := tweet_limit - len(tweet_string) >= 0:  # walrus operator
    print("A fitting tweet")
else:
    print("Went over by", abs(diff))
```

* Compare with `if`, `elif`, and `else`:
+
```py
color = "mauve"
if color == "red":
    print("It's a tomato")
elif color == "green":
    print("It's a green pepper")
else:
    print("I've never heard of the color", color)
```

* Repeat with `while`, and `break`, `continue`, and `else`:
+
```py
while True:
    value = input("Integer, please [q to quit]: ")
    if value == 'q':  # quit
        break
    number = int(value)
    if number % 2 == 0:  # an even number
        continue
    print(number, "squared is", number*number)
```
+
```py
numbers = [1, 3, 5]
position = 0
while position < len(numbers):
    number = numbers[position]
    if number % 2 == 0:
        print('Found even number', number)
        break
    position += 1
else:  # break not called
    print('No even number found')
```

* Iterate with `for` and `in`, and `break`, `continue` and `else`:
+
```py
word = 'thud'
for letter in word:
    if letter == 'u':
        continue
    print(letter)
```
+
```py
word = 'thud'
for letter in word:
    if letter == 'x':
        print("Eek! An 'x'!")
        break
    print(letter)
else:
    print("No 'x' in there.")
```
+
```py
for num in range(0, 10, 2):
    print(num)  # 0 2 ... 8
```
+
```py
for nums in zip(range(0, 10, 2), range(1, 10, 2)):
    print(nums)  # (0, 1) (2, 3) .. (8, 9)
```

== Tuples and lists

* *Tuples* are built-in immutable sequences.
+
```py
# to make a tuple with one or more elements, follow each element with a comma (`,`):
'cat',  # ('cat',)
'cat', 'dog', 'cattle'  # ('cat', 'dog', 'cattle')

# to make an empty tuple, using `()`, or `tuple()`:
()  # ()
tuple()  # ()

# the comma is required to make a tuple
('cat')  # 'cat'

# the parentheses is not required, but could make the tuple more visible
('cat',)  # ('cat',)
('cat', 'dog', 'cattle')  # ('cat', 'dog', 'cattle')

# for cases in which commas might also have another use, the parentheses is needed
type('cat',)  # <class 'str'>
type(('cat',))  # <class 'tuple'>

# tuple()
tuple('cat')  # ('c', 'a', 't')

# zip()
for x in zip([1, 2, 8], [1, 4, 9], ('cat', 'dog', 'cattle', 'chicken')):
     print(x)
# (1, 1, 'cat')
# (2, 4, 'dog')
# (8, 9, 'cattle')
```

* *Lists* are built-in mutable sequences.
+
```py
# create with `[]` or `list()`
[]  # []
['meow', 'bark', 'moo']  # ['meow', 'bark', 'moo']
[('cat', 'meow'), 'bark', 'moo']  # [('cat', 'meow'), 'bark', 'moo']
list()  # []
list('cat')  # ['c', 'a', 't']

# append(), insert()
wow = ['meow']  # ['meow']
wow.append('moo')  # ['meow', 'moo']
wow.insert(1, 'bark')  # ['meow', 'bark', 'moo']

# del, remove(), pop(), clear()
farm = ['cat', 'dog', 'cattle', 'chicken', 'duck']

del farm[-1]
# ['cat', 'dog', 'cattle', 'chicken']

farm.remove('dog')
# ['cat', 'cattle', 'chicken']

farm.pop()  # 'chicken'
# ['cat', 'cattle']

farm.pop(-1)  # 'cattle'
# ['cat']

farm.clear()
# []

# sort() and sorted()
farm = ['cat', 'dog', 'cattle']

# a sorted copy
sorted(farm)  # ['cat', 'cattle', 'dog']
print(farm)  # ['cat', 'dog', 'cattle']

# sorting in-place 
farm.sort()
print(farm)  # ['cat', 'cattle', 'dog']

# copy() and deepcopy()
a = [['cat', 'meow'], ['dog', 'bark']]
b = a.copy()
c = a[:]
d = list(c)

import copy
e = copy.deepcopy(a)

a[0][1] = 'moo'
a  # [['cat', 'moo'], ['dog', 'bark']]
b  # [['cat', 'moo'], ['dog', 'bark']]
c  # [['cat', 'moo'], ['dog', 'bark']]
d  # [['cat', 'moo'], ['dog', 'bark']]

e  #[['cat', 'meow'], ['dog', 'bark']]

# list comprehension
even_numbers = [2 * num for num in range(5)]  # [expression for item in iterable]
# [0, 2, 4, 6, 8]
odd_numbers = [num for num in range(10) if num % 2 == 1]  # [expression for item in iterable if condition]
# [1, 3, 5, 7, 9]
```








[bibliography]
== References

* [[[IntroducingPython,1]]] Bill Lubanovic _Introducing Python: Modern Computing in Simple Packages_. second edition, O’Reilly Media, Inc., November 2019
* [[[wiki-Python,2]]]https://en.wikipedia.org/wiki/Python_(programming_language)
* [[[gemini,3]]] https://gemini.google.com
