= Python Learning Notes
:page-layout: post
:page-categories: ['python']
:page-tags: ['python']
:page-date: 2024-05-17 10:29:20 +0800
:page-revdate: 2024-05-17 10:29:20 +0800
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

Python is a dynamic and strongly typed programming language.

* In a dynamically typed language, the data type of a variable is NOT explicitly declared at the time of definition, and is determined at runtime.
+
```py
age = 30  # age is an integer (no need to declare the data type explicitly)
age = "thirty"  # age is now a string
```
+
In a statically typed language, the data type of a variable MUST be declared at compile time and the compiler ensures type compatibility throughout the code.
+
```java
// In Java, declare the type of a variable before assigning a value.
int age = 30;  // age is declared as an integer
age = "thirty";  // error: incompatible types: String cannot be converted to int
```

* In a strongly typed language, the data type of a variable MUST be declared at the time of definition, and the compiler or interpreter enforces type safety.

* In Python, everything is ultimately an object, even data types like integers and strings, that has associated methods and attributes. During runtime, Python checks if the methods or attributes involved are compatible with the object's type.
+
```py
# Like dynamic languages, Python infers types based on assigned values.
name = "Alice"  # name is a string
name + 10  # This would cause a TypeError in Python (mixing string and number)
```
+
[TIP]
====
In computer programming, https://en.wikipedia.org/wiki/Duck_typing[duck typing] is an application of the duck test—"If it walks like a duck and it quacks like a duck, then it must be a duck"—to determine whether an object can be used for a particular purpose.

[.text-right]
-- From Wikipedia, the free encyclopedia
====

== Running Python

* Using the interactive interpreter (shell)

```console
$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 2+2
4
>>> quit()
```

* Using python files

```console
$ echo 'print(2+2)' > test.py
$ python3 test.py
4
```

* Using python files with shebang
+
[TIP]
====
In computing, a https://en.wikipedia.org/wiki/Shebang_(Unix)[*shebang*] is the character sequence consisting of the characters number sign and exclamation mark (`#!`) at the beginning of a script. It is also called sharp-exclamation, sha-bang, *hashbang*, pound-bang, or hash-pling.

[.text-right]
-- From Wikipedia, the free encyclopedia
====
+
```console
$ cat <<EOF > test.py
> #!/usr/bin/env python3
> print(2+2)
> EOF
$ chmod +x test.py
$ ./test.py
4
```

== Types, Values, Variables, and Names

```py
# Python’s basic data types

bool # True, False

int # 47, 25000, 25_000 Chapter 3
float # 3.14, 2.7e5 Chapter 3
complex # 3j, 5 + 9j Chapter 22

str # 'alas', "alack", '''a verse attack''' Chapter 5

list # ['Winken', 'Blinken', 'Nod'] Chapter 7
tuple # (2, 4, 8) Chapter 7

bytes # b'ab\xff'
bytearray # bytearray(...)

set # set([3, 5, 7])
frozenset # frozenset(['Elsa', 'Otto'])

dict # {'game': 'bingo', 'dog': 'dingo', 'drummer': 'Ringo'}
```

* In Python, variables are NOT places, just names, and a name is a _reference_ to an object rather than the object itself.
+
```py
a = 3.14
print(a) // 3.14
b = a
print(b) // 3.14
```

* Python wraps each data value—booleans, integers, floats, strings, even large data structures, functions, and programs—in memory as an _object_, that is a chunk of data that contains at least a _type_, a unique _id_, a _value_, and a _reference count_.
+
```console
>>> type(7)
<class 'int'>
>>> id(7)
10861384
>>> import sys
>>> sys.getrefcount(7)
1000000027
```

* A _class_ is the definition of an object, and "class" and "type" mean pretty much the same thing.
+
```console
>>> type(7)
<class 'int'>
>>> type(7) == int
True
>>> isinstance(7, int)
True
>>> int
<class 'int'>
>>> type(int)
<class 'type'>
>>> type(type)
<class 'type'>
>>> help(int)
```













[bibliography]
== References

* [[[IntroducingPython,1]]] Bill Lubanovic _Introducing Python: Modern Computing in Simple Packages_. second edition, O’Reilly Media, Inc., November 2019
