= What is Helm
:page-layout: post
:page-categories: ['kubernetes']
:page-tags: ['kubernetes', 'helm']
:page-date: 2024-03-09 12:41:33 +0800
:page-revdate: 2024-03-09 12:41:33 +0800
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

https://helm.sh/[Helm] is a package manager for Kubernetes that uses a packaging format called https://helm.sh/docs/topics/charts/[charts], and is implemented into two distinct parts: Helm Client and Helm Library. <<helm-sh-architecture>>

A _chart_ is a bundle of information to create an instance of a Kubernetes application and a repository is the place where charts can be collected and shared.

A _release_ is a running instance of a chart, combined with a specific _config_ that contains configuration information that can be merged into a packaged chart to create a releasable object.

== Installing Helm

The Helm can be installed from the official binary releases and the community package managers. <<helm-sh-install>>

Every release of Helm provides binary https://github.com/helm/helm/releases[releases] for a variety of OSes. These binary versions can be manually downloaded and installed.

. Download a desired https://helm.sh/docs/topics/version_skew/[version that supported between Helm and Kubernetes].
. Unpack it (`tar -zxvf helm-v3.0.0-linux-amd64.tar.gz`)
. Find the helm binary in the unpacked directory, and move it to its desired destination (`mv linux-amd64/helm /usr/local/bin/helm`)

For example, to install a version `3.14.x` Helm that supports Kubernetes between `1.29.x` and `1.26.x`:

```console
$ curl -sLO https://get.helm.sh/helm-v3.14.2-linux-amd64.tar.gz
$ tar xf helm-v3.14.2-linux-amd64.tar.gz
$ sudo cp linux-amd64/helm /usr/local/bin/
```

The following script is used to install Helm from Apt (Debian/Ubuntu):

```sh
curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
sudo apt-get install apt-transport-https --yes
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update
sudo apt-get install helm
```

It's recommended to run the following command to generate the completion scripts for the specified shell (e.g., Bash):

```sh
helm completion bash | sudo tee /etc/bash_completion.d/helm > /dev/null
source /etc/bash_completion # reload the completion scripts
```

== Initialize a Helm Chart Repository

Once the Helm is ready, a chart repository can be added using `helm repo add` command. Check https://artifacthub.io/packages/search?kind=0[Artifact Hub] for available Helm chart repositories. <<helm-sh-quickstart>>

For example, to install the `bitnami` repo:

```sh
helm repo add bitnami https://charts.bitnami.com/bitnami
```

Once installed, it is able to list the available charts:

```console
$ helm search repo bitnami
NAME                                        	CHART VERSION	APP VERSION  	DESCRIPTION
bitnami/airflow                             	17.2.1       	2.8.2        	Apache Airflow is a tool to express and execute...
bitnami/apache                              	10.9.1       	2.4.58       	Apache HTTP Server is an open-source HTTP serve...
bitnami/apisix                              	2.10.0       	3.8.0        	Apache APISIX is high-performance, real-time AP...
...
```

== Install an Example Chart

To install a chart, you can run the `helm install` command. Helm has several ways to find and install a chart, but the easiest is to use the bitnami charts. <<helm-sh-quickstart>>

. Make sure getting the latest list of charts.
+
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
```

. Install `bitnami/mysql` chart.
+
```console
$ helm install bitnami/mysql --generate-name
NAME: mysql-1709977095
LAST DEPLOYED: Sat Mar  9 17:38:19 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
...
```

. List the deployed releases.
+
```console
$ helm list
NAME            	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION
mysql-1709977095	default  	1       	2024-03-09 17:38:19.258433628 +0800 CST	deployed	mysql-9.23.0	8.0.36
```

. Uninstall a release.
+
```console
$ helm uninstall mysql-1709977095
release "mysql-1709977095" uninstalled
```

[bibliography]
== References

* [[[helm-sh-architecture,1]]] https://helm.sh/docs/topics/architecture/
* [[[helm-sh-install,2]]] https://helm.sh/docs/intro/install/
* [[[helm-sh-quickstart,3]]] https://helm.sh/docs/intro/quickstart/
