= Python Learning Notes
:page-layout: post
:page-categories: ['python']
:page-tags: ['python']
:page-date: 2024-05-17 10:29:20 +0800
:page-revdate: 2024-05-17 10:29:20 +0800
:toc: preamble
:toclevels: 4
:sectnums:
:sectnumlevels: 4

Python is a dynamically, strongly typed and garbage-collected programming language.

* In a dynamically typed language, the data type of a variable is NOT explicitly declared at the time of definition, and is determined at runtime.
+
```py
age = 30  # age is an integer (no need to declare the data type explicitly)
age = "thirty"  # age is now a string
```
+
In a statically typed language, the data type of a variable MUST be declared at compile time and the compiler ensures type compatibility throughout the code.
+
```java
// In Java, declare the type of a variable before assigning a value.
int age = 30;  // age is declared as an integer
age = "thirty";  // error: incompatible types: String cannot be converted to int
```

* In a strongly typed language, the data type of a variable MUST be declared at the time of definition, and the compiler or interpreter enforces type safety.

* In Python, everything is ultimately an object, even data types like integers and strings, that has associated methods and attributes. During runtime, Python checks if the methods or attributes involved are compatible with the object's type.
+
```py
# Like dynamic languages, Python infers types based on assigned values.
name = "Alice"  # name is a string
name + 10  # This would cause a TypeError in Python (mixing string and number)
```
+
[TIP]
====
In computer programming, https://en.wikipedia.org/wiki/Duck_typing[duck typing] is an application of the duck test—"If it walks like a duck and it quacks like a duck, then it must be a duck"—to determine whether an object can be used for a particular purpose.

[.text-right]
-- From Wikipedia, the free encyclopedia
====

== Running Python

* Using the interactive interpreter (shell)
+
```console
$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
+
```py
>>> 2+2
4
>>> quit()
```

* Using python files
+
```console
$ echo 'print(2+2)' > test.py
$ python3 test.py
4
```

* Using python files with shebang
+
[TIP]
====
In computing, a https://en.wikipedia.org/wiki/Shebang_(Unix)[*shebang*] is the character sequence consisting of the characters number sign and exclamation mark (`#!`) at the beginning of a script. It is also called sharp-exclamation, sha-bang, *hashbang*, pound-bang, or hash-pling.

[.text-right]
-- From Wikipedia, the free encyclopedia
====
+
```console
$ cat <<EOF > test.py
> #!/usr/bin/env python3
> print(2+2)
> EOF
$ chmod +x test.py
$ ./test.py
4
```

== Indentations, comments, and multi-line expressions

* Python uses whitespace indentation (the recommended style, called PEP-8, is to use four spaces), rather than curly brackets or keywords, to delimit blocks.
+
--
** Don't use tabs, or mix tabs and spaces; it messes up the indent count.

** When designing the language that became Python, Guido van Rossum decided that the indentation itself was enough to define a program’s structure, and avoided typing all those parentheses and curly braces. Python is unusual in this use of white space to define program structure.
--
+
```py
disaster = True
if disaster:
    print("Woe!")
else:
    print("Whee!")
```

* A comment is marked by using the `#` (names: _hash_, _sharp_, _pound_, or or the sinister-sounding _octothorpe_) character; everything from that point on to the end of the current line is part of the comment.
+
```py
# 60 sec/min * 60 min/hr * 24 hr/day
seconds_per_day = 86400
```
+
```py
seconds_per_day = 86400 # 60 sec/min * 60 min/hr * 24 hr/day
```
+
```py
# Python does NOT
# have a multiline comment.
print("No comment: quotes make the # harmless.")
```

* Python allows to write expressions that span multiple lines within certain delimiters.

** In older versions of Python (pre-3.0), the backslash character (`\`) at the end of a line was used to indicate that the line continued on the next line, which  is no longer required in modern Python (versions 3.0 and above).
+
```py
# Example in older Python (not recommended)
long_expression = (1 + 2 + 3 + 4 + 5 + \
                  6 + 7 + 8 + 9 + 10)
```

** In modern Python, avoid using the continuation character (`\`) for line continuation, and utilize parentheses (`()`), brackets (`[]`), or braces (`[]`) for readability and structure in multi-line expressions.
+
```py
# Parentheses for complex calculations
long_calculation = (a * b +
                    c) * (d /
                          e - f)

# Brackets for multi-line lists or data structures
data = [
    "item1",
    "item2 with a longer description",
    "item3"
]

# Braces for multi-line dictionaries
person_info = {
    "name": "Alice",
    "age": 30,
    "hobbies": ["reading", "hiking"]
}
```

== Types, values, variables, and names

* Python’s basic data types
+
```py

bool # True, False

int # 47, 25000, 25_000, 0b0100_0000, 0o100, 0x40

float # 3.14, 2.7e5

complex # 3j, 5 + 9j

str # 'alas', "alack", '''a verse attack'''

list # ['Winken', 'Blinken', 'Nod']
tuple # (2, 4, 8)

bytes # b'ab\xff'
bytearray # bytearray(...)

set # set([3, 5, 7])
frozenset # frozenset(['Elsa', 'Otto'])

dict # {'game': 'bingo', 'dog': 'dingo', 'drummer': 'Ringo'}
```

* In Python, variables are NOT places, just names, and a name is a _reference_ to an object rather than the object itself.
+
```py
a = 3.14
print(a) // 3.14
b = a
print(b) // 3.14
```

* Python wraps each data value—booleans, integers, floats, strings, even large data structures, functions, and programs—in memory as an _object_, that is a chunk of data that contains at least a _type_, a unique _id_, a _value_, and a _reference count_.
+
```py
>>> type(5.20)
<class 'float'>
>>> id(5.20)
140683748269744
>>> x = y = z = 0
>>> sys.getrefcount(x)
1000000591
>>> del y
>>> sys.getrefcount(x)
1000000590
>>> del z
>>> sys.getrefcount(x)
1000000589
```

* A _class_ is the definition of an object, and "class" and "type" mean pretty much the same thing.
+
```py
>>> type(7)
<class 'int'>
>>> type(7) == int
True
>>> isinstance(7, int)
True
>>> int
<class 'int'>
>>> type(int)
<class 'type'>
>>> type(type)
<class 'type'>
>>> help(int)
```

* More than one variable name can be assigned a value at the same time
+
```py
two = deux = zwei = 2
```

* Non-zero numbers are considered `True`:
+
```py
>>> bool(True)
True
>>> bool(1)
True
>>> bool(45)
True
>>> bool(-45)
True
```

* Zero-valued ones are considered `False`:
+
```py
>>> bool(False)
False
>>> bool(0)
False
>>> bool(0.0)
False
```

* Python also promotes booleans to integers or floats:
+
```py
>>> False + 0
0
>>> False + 0.
0.0
>>> True + 0
1
>>> True + 0.
1.0
```

* Type converstions: `int()`, `float()`, `bin()`, `oct()`, `hex()`, `chr()`, and `ord()`
+
```py
>>> int(True)
1
>>> int(False)
0

>>> int(98.6)
98
>>> int(1.0e4)
10000

>>> int('99')
99
>>> int('-23')
-23
>>> int('+12')
12
>>> int('1_000_000')
1000000

>>> int('10', 2) # binary
2
>>> int('10', 8) # octal
8
>>> int('10', 16) # hexadecimal
16
>>> int('10', 22) # chesterdigital
22

>>> float(True)
1.0
>>> float(False)
0.0

>>> float('98.6')
98.6
>>> float('-1.5')
-1.5
>>> float('1.0e4')
10000.0

>>> value = 65
>>> bin(value)
'0b1000001'
>>> oct(value)
'0o101'
>>> hex(value)
'0x41'

>>> chr(65)
'A'
>>> ord('A')
65
```

== If, while, and for

* In Python, truthiness and falsiness are used to check a value in a Boolean context:

** Truthy: Values that evaluate to `True`, which includes most non-zero numbers, non-empty strings, lists, dictionaries, and many objects.

** Falsy: Values that evaluate to `False`, which include `False`, zero numbers (`0`, `0.0`), empty strings (`""`), empty lists (`[]`), empty tuples (`()`), and `None`.

* In Python, the logical operators `and`, `or`, `not` are used to combine Boolean values (True/False) or expressions that evaluate to Boolean values.
+
```py
letter = 'o'
if letter == 'a' or letter == 'e' or letter == 'i' or letter == 'o' or letter == 'u':
    print(letter, 'is a vowel')
else:
    print(letter, 'is not a vowel')
```

* In Python (version 3.8 and above), the walrus operator (`:=`, formally known as the assignment expression operator) combines assignment and expression evaluation in a single line.
+
```py
tweet_limit = 280
tweet_string = "Blah" * 50
if diff := tweet_limit - len(tweet_string) >= 0:  # walrus operator
    print("A fitting tweet")
else:
    print("Went over by", abs(diff))
```

* Compare with `if`, `elif`, and `else`:
+
```py
color = "mauve"
if color == "red":
    print("It's a tomato")
elif color == "green":
    print("It's a green pepper")
else:
    print("I've never heard of the color", color)
```

* Repeat with `while`, and `break`, `continue`, and `else`:
+
```py
while True:
    value = input("Integer, please [q to quit]: ")
    if value == 'q':  # quit
        break
    number = int(value)
    if number % 2 == 0:  # an even number
        continue
    print(number, "squared is", number*number)
```
+
```py
numbers = [1, 3, 5]
position = 0
while position < len(numbers):
    number = numbers[position]
    if number % 2 == 0:
        print('Found even number', number)
        break
    position += 1
else:  # break not called
    print('No even number found')
```

* Iterate with `for` and `in`, and `break`, `continue` and `else`:
+
```py
word = 'thud'
for letter in word:
    if letter == 'u':
        continue
    print(letter)
```
+
```py
word = 'thud'
for letter in word:
    if letter == 'x':
        print("Eek! An 'x'!")
        break
    print(letter)
else:
    print("No 'x' in there.")
```
+
```py
for num in range(0, 10, 2):
    print(num)  # 0 2 ... 8
```
+
```py
for nums in zip(range(0, 10, 2), range(1, 10, 2)):
    print(nums)  # (0, 1) (2, 3) .. (8, 9)
```

== Tuples and lists

*Tuples* are immutable sequence structures, and can contain zero or more elements within any Python object.

* To make an empty tuple, using `()`:
+
```py
>>> empty_tuple = ()
>>> empty_tuple
()
```

* To make a tuple with one or more elements, follow each element with a comma (`,`):
+
```py
>>> one_marx = 'Groucho',
>>> one_marx
('Groucho',)
>>> marx_tuple = 'Groucho', 'Chico', 'Harpo'
>>> marx_tuple
('Groucho', 'Chico', 'Harpo')
```
+
```py
# the comma is required to make a tuple
>>> one_marx = ('Groucho')
>>> one_marx
'Groucho'
>>> type(one_marx)
<class 'str'>
```
+
```py
# the parentheses is not required, but could make the tuple more visible
>>> one_marx = ('Groucho',)
>>> one_marx
('Groucho',)
>>> marx_tuple = ('Groucho', 'Chico', 'Harpo')
>>> marx_tuple
('Groucho', 'Chico', 'Harpo')
```
+
```py
# for cases in which commas might also have another use, the parentheses is needed
>>> type('Groucho',)
<class 'str'>
>>> type(('Groucho',))
<class 'tuple'>
```

* Using _tuple unpacking_ to assign multiple variables at once:
+
```py
>>> marx_tuple = ('Groucho', 'Chico', 'Harpo')
>>> a, b, c = marx_tuple
>>> a
'Groucho'
>>> b
'Chico'
>>> c
'Harpo'
```
+
```py
# tuples to exchange values in one statement without using a temporary variable
>>> password = 'swordfish'
>>> icecream = 'tuttifrutti'
>>> password, icecream = icecream, password
>>> password
'tuttifrutti'
>>> icecream
'swordfish'
```

* `tuple()`, `zip()`, `+`, and `*`
+
```py
>>> marx_list = ['Groucho', 'Chico', 'Harpo']
>>> tuple(marx_list)
('Groucho', 'Chico', 'Harpo')
```
+
```py
>>> for x in zip(range(len(marx_list)), marx_list):
...     print(x)
...
(0, 'Groucho')
(1, 'Chico')
(2, 'Harpo')
```
+
```py
>>> ('Groucho',) + ('Chico', 'Harpo')
('Groucho', 'Chico', 'Harpo')
```
+
```py
>>> ('yada',) * 3
('yada', 'yada', 'yada')
```

* Compare, and iterate with for and in
+
```py
# works much like list comparisons:
>>> a = (7, 2)
>>> b = (7, 2, 9)
>>> a == b
False
>>> a <= b
True
>>> a < b
True
```
+
```py
# like iteration of other types:
>>> words = ('fresh', 'out', 'of', 'ideas')
>>> for word in words:
...     print(word)
...
fresh
out
of
ideas
```


[bibliography]
== References

* [[[IntroducingPython,1]]] Bill Lubanovic _Introducing Python: Modern Computing in Simple Packages_. second edition, O’Reilly Media, Inc., November 2019
* [[[wiki-Python,2]]]https://en.wikipedia.org/wiki/Python_(programming_language)
