= Sonatype Nexus Repository OSS
:page-layout: post
:page-categories: ['devops']
:page-tags: ['devops']
:page-date: 2024-01-31 09:07:37 +0800
:page-revdate: 2024-01-31 09:07:37 +0800
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

== Installing with Docker

. Open a terminal, and create a _.env_ file, and set the project name with `sonatype-nexus`.
+
```sh
echo -n COMPOSE_PROJECT_NAME=sonatype-nexus > .env
```

. Creata a bridge network named `sonatype-nexus`.
+
```sh
docker network create -d bridge sonatype-nexus
```

. Create a _compose.yml_ file.
+
```yml
version: "2.4"
services:
  nexus:
    container_name: sonatype-nexus
    user: nexus:nexus
    image: sonatype/nexus3:3.64.0
    restart: "on-failure:3"
    volumes:
      - data:/nexus-data:rw
    networks:
      nexus:
volumes:
  data:
    name: nexus-data
networks:
  nexus:
    external: true
    name: sonatype-nexus
```

. Create a _compose.override.yml_ file.
+
```yml
version: "2.4"
services:
  nexus:
    ports:
      - "8081:8081"
      - "8082:8082" # Using for Docker Registry
    # environment:
    #   NEXUS_CONTEXT: nexus # NEXUS_CONTEXT, defaults to /
    #   INSTALL4J_ADD_VM_PARAMS, passed to the Install4J startup script. Defaults to -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs.
```

. Start the _sonatype-nexus_ container.
+
```sh
docker compose up -d
```

. Go to a browser with http://localhost:8081, click on the *Sign in* button on the top right, and fill the login fields, and then complete required setup tasks.
+
[TIP]
====
Your *admin* user password is located in _/nexus-data/admin.password_ on the server.

```console
$ docker inspect nexus-data
[
    {
        "CreatedAt": "2024-01-31T09:49:55+08:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "sonatype-nexus",
            "com.docker.compose.version": "2.21.0",
            "com.docker.compose.volume": "data"
        },
        "Mountpoint": "/var/lib/docker/volumes/nexus-data/_data",
        "Name": "nexus-data",
        "Options": null,
        "Scope": "local"
    }
]
$ sudo cat /var/lib/docker/volumes/nexus-data/_data/admin.password
06b838f5-34c3-47dc-a539-3646fce14f60
```
====

== Setup a Docker Registry

A hosted repository using the Docker repository format is typically called a private Docker registry. It can be used to upload your own container images as well as third-party images. It is common practice to create two separate hosted repositories for these purposes. <<hosted-repository-for-docker>>

. Go the Nexus dashboard, and select the gear icon at the top bar, or enter http://localhost:8081/#admin/repository.

. Select the *Repositories* on the left menu to the *Manage repositories* panel, or enter http://localhost:8081/#admin/repository/repositories.

. Click the *Create repository* button, and select the *docker (hosted)* recipe, then fill the form.
+
--
* *Name*: _docker-registry_
* *Http:*: _8082_
--

. Click the *Create repository* button at the bottom.

. Test the _docker-registry_.
+
```sh
docker login -u admin -p [YOUR ADMIN PASSWORD OF NEXUS] http://localhost:8082
```
+
[TIP]
====
If an insecure registry isn’t marked as insecure, docker pull, docker push, and docker search result in error messages, prompting the user to either secure or pass the `--insecure-registry` flag to the Docker daemon.

Local registries, whose IP address falls in the 127.0.0.0/8 range, are automatically marked as insecure as of Docker 1.3.2. It isn’t recommended to rely on this, as it may change in the future.
====
+
```console
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
9ad63333ebc9: Pull complete
Digest: sha256:6d9ac9237a84afe1516540f40a0fafdc86859b2141954b4d643af7066d598b74
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
$ docker tag busybox:latest localhost:8082/busybox
$ docker push localhost:8082/busybox
Using default tag: latest
The push refers to repository [localhost:8082/busybox]
2e112031b4b9: Pushed
latest: digest: sha256:d319b0e3e1745e504544e931cde012fc5470eba649acc8a7b3607402942e5db7 size: 527
$ docker pull localhost:8082/busybox
Using default tag: latest
latest: Pulling from busybox
Digest: sha256:d319b0e3e1745e504544e931cde012fc5470eba649acc8a7b3607402942e5db7
Status: Image is up to date for localhost:8082/busybox:latest
localhost:8082/busybox:latest
```

== Push a Nuget package to NuGet Hosted Repositories

A hosted repository for NuGet can be used to upload your own packages as well as third-party packages. The repository manager includes a hosted NuGet repository named _nuget-hosted_ by default. <<nuget-hosted-repo>>

. Go the Nexus dashboard, sign in, and click the user name at the top right, or enter http://localhost:8081/#user/account.

. On the left panel, select the *NuGet API Key*.

. Click the *Access API Key*, authentication with your credential, and then click *Copy to Clipboard*. 

. Click the gear icon at the top panel, select the *Realms* on the left panel under the *Security*.

. Select the *NuGet API-Key Realm* on the left *Available* tab panel, and transfer it to the right *Active* tab panel.

. Click the *Save* button at the bottom right.

. Test it.
+
```console
$ dotnet new classlib -o HelloLib
The template "Class Library" was created successfully.
. . .
$ dotnet pack HelloLib/
$ dotnet nuget push HelloLib/bin/Release/HelloLib.1.0.0.nupkg -k [REPLACE WITH YOUR API KEY] -s http://localhost:8081/repository/nuget-hosted/index.json
warn : You are running the 'push' operation with an 'HTTP' source, 'http://localhost:8081/repository/nuget-hosted/index.json'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
Pushing HelloLib.1.0.0.nupkg to 'http://localhost:8081/repository/nuget-hosted'...
warn : You are running the 'push' operation with an 'HTTP' source, 'http://localhost:8081/repository/nuget-hosted/'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
  PUT http://localhost:8081/repository/nuget-hosted/
  Created http://localhost:8081/repository/nuget-hosted/ 40ms
Your package was pushed.
```
+
[TIP]
====
You can also add the NuGet source to a project Nuget.config.

```sh
dotnet new nugetconfig
dotnet nuget add source -n nexus http://localhost:8081/repository/nuget-hosted/index.json
```
====

[bibliography]
== References

* [[[installation-methods,1]]] https://help.sonatype.com/en/installation-methods.html
* [[[docker-nexus3,2]]] https://hub.docker.com/r/sonatype/nexus3/
* [[[hosted-repository-for-docker,3]]] https://help.sonatype.com/en/hosted-repository-for-docker--private-registry-for-docker-.html
* [[[nuget-hosted-repo,4]]] https://help.sonatype.com/en/nuget-hosted-repositories.html
