= Service Mesh
:page-layout: post
:page-categories: ['kubernetes']
:page-tags: ['kubernetes', 'istio', 'envoy']
:page-date: 2024-02-29 14:15:22 +0800
:page-revdate: 2024-02-29 14:15:22 +0800
:toc: preamble
:toclevels: 4
:sectnums:
:sectnumlevels: 4

https://istio.io/[Istio] addresses the challenges developers and operators face with a distributed or microservices architecture. <<istio-service-mesh>>

.By adding a proxy "sidecar" along with every application deployed, Istio lets you program application-aware traffic management, incredible observability, and robust security capabilities into your network.
image::https://istio.io/latest/img/service-mesh.svg[Service mesh,45%,45%]

== What is a Service Mesh

Modern applications are typically architected as distributed collections of microservices, with each collection of microservices performing some discrete business function. <<istio-service-mesh>>

A _service mesh_ is a dedicated infrastructure layer that you can add to your applications. It allows you to transparently add capabilities like _observability_, _traffic management_, and _security_, without adding them to your own code.

The term “service mesh” describes both the type of software you use to implement this pattern, and the security or network domain that is created when you use that software.

== What's Istio?

Istio is an open source service mesh that layers transparently onto existing distributed applications.

Istio’s powerful features provide a uniform and more efficient way to secure, connect, and monitor services. Istio is the path to load balancing, service-to-service authentication, and monitoring – with few or no service code changes. Its powerful control plane brings vital features, including:

* Secure service-to-service communication in a cluster with TLS encryption, strong identity-based authentication and authorization
* Automatic load balancing for HTTP, gRPC, WebSocket, and TCP traffic
* Fine-grained control of traffic behavior with rich routing rules, retries, failovers, and fault injection
* A pluggable policy layer and configuration API supporting access controls, rate limits and quotas
* Automatic metrics, logs, and traces for all traffic within a cluster, including cluster ingress and egress

Istio’s control plane runs on Kubernetes, and you can add applications deployed in that cluster to your mesh, extend the mesh to other clusters, or even connect VMs or other endpoints running outside of Kubernetes.

=== Architecture

An Istio service mesh is logically split into a data plane and a control plane. <<istio-architecture>>

* The _data plane_ is composed of a set of intelligent proxies (https://www.envoyproxy.io/[Envoy]) deployed as sidecars. These proxies mediate and control all network communication between microservices. They also collect and report telemetry on all mesh traffic.

* The _control plane_ manages and configures the proxies to route traffic.
+
image::https://istio.io/latest/docs/ops/deployment/architecture/arch.svg[The overall architecture of an Istio-based application.,55%,55%]

*Envoy*

Istio uses an extended version of the https://www.envoyproxy.io/[Envoy] proxy. Envoy is a high-performance proxy developed in C++ to mediate all inbound and outbound traffic for all services in the service mesh. Envoy proxies are the only Istio components that interact with data plane traffic.

*Istiod*

Istiod provides service discovery, configuration and certificate management.

=== Install Istio

. Go the the https://github.com/istio/istio/releases[Istio release] page to download the installation file for your OS, or download and extract the latest release automatically (Linux or macOS): <<istio-getting-started>>
+
```sh
curl -L https://istio.io/downloadIstio | sh -
```

. Move to the Istio package directory. For example, if the package is `istio-1.20.3`:
+
```sh
cd istio-1.20.3
```
+
The installation directory contains:
+
--
* Sample applications in `samples/`
* The `istioctl` client binary in the `bin/` directory.
--

. Add the `istioctl` client to your path (Linux or macOS):
+
```sh
export PATH=$PWD/bin:$PATH
```

. For this installation, we use the `demo` https://istio.io/latest/docs/setup/additional-setup/config-profiles/[configuration profile]. It’s selected to have a good set of defaults for testing, but there are other profiles for production or performance testing.
+
```console
$ istioctl install --set profile=demo -y
✔ Istio core installed
✔ Istiod installed
✔ Egress gateways installed
✔ Ingress gateways installed
✔ Installation complete
Made this installation the default for injection and validation.
```

. Add a namespace label to instruct Istio to automatically inject Envoy sidecar proxies when you deploy your application later:
+
```console
$ kubectl label namespace default istio-injection=enabled
namespace/default labeled
```

*Uninstall*

. The Istio uninstall deletes the RBAC permissions and all resources hierarchically under the `istio-system` namespace. It is safe to ignore errors for non-existent resources because they may have been deleted hierarchically.
+
```sh
istioctl uninstall -y --purge
```
+
The `istio-system` namespace is not removed by default. If no longer needed, use the following command to remove it:
+
```sh
kubectl delete namespace istio-system
```
+
The label to instruct Istio to automatically inject Envoy sidecar proxies is not removed by default. If no longer needed, use the following command to remove it:
+
```sh
kubectl label namespace default istio-injection-
```


[bibliography]
== References

* [[[istio-service-mesh,1]]] https://istio.io/latest/about/service-mesh/
* [[[istio-architecture,2]]] https://istio.io/latest/docs/ops/deployment/architecture/
* [[[istio-getting-started,3]]] https://istio.io/latest/docs/setup/getting-started/
