= Proxies in Docker & containerd
:page-layout: post
:page-categories: ['networking']
:page-tags: ['networking', 'proxy', 'http_proxy', 'https_prox', 'curl', 'docker', 'containerd']
:page-date: 2024-06-15 10:36:13 +0800
:page-revdate: 2024-06-15 10:36:13 +0800
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

== Unveiling the Proxy Duo: http_proxy & https_proxy

Ever tried downloading a file online but encountered a restrictive firewall (security barrier) blocking your way?

Fear not! This guide unveils the magic behind `http_proxy` and `https_proxy`, the environment variables that act as passports for your tools to navigate these gatekeepers.

* `http_proxy` and `https_proxy`: The Gate-Openers
+
--
Imagine `curl`, a popular tool for downloading files from the internet, needs to access a website. But a firewall stands between them, potentially for security reasons. This is where `http_proxy` and `https_proxy` come in:

* `http_proxy`: specifies the address and port of a proxy server specifically for handling *regular, unencrypted HTTP traffic*.
+
Think of it as a translator, converting your request into a format the proxy understands before forwarding it to the website.

* `https_proxy`: caters to *HTTPS traffic*, which is encrypted for security.
+
When set, `curl` establishes a secure tunnel with the proxy server using TLS/SSL before sending any data. It's like whispering your request through a hidden passage.
--

* Why Separate Passports?
+
--
You might wonder why there are two separate variables. It offers flexibility:

* You might only need a proxy for regular HTTP traffic (downloads), not secure HTTPS connections (online banking).

* Different proxy servers could be used for HTTP and HTTPS depending on your needs.
--
+
In most cases, *setting both variables to the same value (pointing to the same proxy server)* is the common practice for proxying all traffic.

* Let's see how this works with `curl`!
+
--
Imagine you want to download a file using `curl` but a firewall with a proxy server is in place. Here's how you would use the environment variables:

```sh
# Set the proxy server address and port (replace with your actual details)
export https_proxy=http://your_proxy_server:port

# Now, use curl to download the file
curl https://example.com/file.txt
```

By setting `https_proxy`, `curl` knows to route its request through the specified proxy server, allowing you to download the file despite the firewall and proxy combination.
--

* Remember:
+
--
** While `curl` itself is generally case-insensitive for these variables, using lowercase (`http_proxy` and `https_proxy`) is recommended for consistency.

** Ensure your proxy server supports the types of connections used by tools like `curl` (usually TCP).
--

With this understanding of `http_proxy` and `https_proxy`, you can navigate proxy servers and access the resources you need!
