= Internet Address Architecture
:page-layout: post
:page-categories: ['networking']
:page-tags: ['networking']
:page-date: 2022-11-11 08:33:09 +0800
:page-revdate: 2022-11-11 08:33:09 +0800

Every device connected to the Internet has at least one IP address. Devices used in private networks based on the TCP/IP protocols also require IP addresses. In either case, the forwarding procedures implemented by IP routers use IP addresses to identify where traffic is going. IP addresses also indicate where traffic has come from.

IP addresses are similar in some ways to telephone numbers, but whereas telephone numbers are often known and used directly by end users, IP addresses are often shielded from a user's view by the Internet’s DNS, which allows most users to use names instead of numbers. Users are confronted with manipulating IP addresses when they are required to set up networks themselves or when the DNS has failed for some reason.

== Expressing IP Address

The vast majority of Internet users who are familiar with IP addresses understand the most popular type: *IPv4* addresses. Such addresses are often represented in so-called dotted-quad or dotted-decimal notation.

.Example IPv4 addresses written in dotted-quad and binary notation
[%header,cols="1,1",width=75%]
|===
|Dotted-Quad Representation
|Binary Representation

|0.0.0.0
|00000000 00000000 00000000 00000000

|1.2.3.4
|00000001 00000010 00000011 00000100

|10.0.0.255
|00001010 00000000 00000000 11111111

|165.195.130.107
|10100101 11000011 10000010 01101011

|255.255.255.255
|11111111 11111111 11111111 11111111

|===

In *IPv6*, addresses are 128 bits in length, four times larger than IPv4 addresses, and generally speaking are less familiar to most users. The conventional notation adopted for IPv6 addresses is a series of four hexadecimal ("hex," or base-16) numbers called _blocks_ or _fields_ separated by colons.

Although not as familiar to users as decimal numbers, hexadecimal numbers make the task of converting to binary somewhat simpler. In addition, a number of agreed-upon simplifications have been standardized for expressing IPv6 addresses [RFC4291]:

. Leading zeros of a block need not be written.
+
For example, the address `5f05:2000:80ad:5800:0058:0800:2023:1d71` can been written as `5f05:2000:80ad:5800:58:800:2023:1d71`.

. Blocks of all zeros can be omitted and replaced by the notation `::`.
+
For example, the IPv6 address `0:0:0:0:0:0:0:1` can be written more compactly as `::1`. Similarly, the address `2001:0db8:0:0:0:0:0:2` can be written more compactly
as `2001:db8::2`.
+
To avoid ambiguities, the `::` notation may be used only once in an IPv6 address.

. Embedded IPv4 addresses represented in the IPv6 format can use a form of hybrid notation in which the block immediately preceding the IPv4 portion of the address has the value ffff and the remaining part of the address is formatted using dotted-quad.
+
For example, the IPv6 address `::ffff:10.0.0.1` represents the IPv4 address `10.0.0.1`. This is called an _IPv4-mapped IPv6 address_.

. A conventional notation is adopted in which the low-order 32 bits of the IPv6 address can be written using dotted-quad notation.
+
The IPv6 address `::0102:f001` is therefore equivalent to the address `::1.2.240.1`. This is called an _IPv4-compatible IPv6 address_.
+
Note that IPv4-compatible addresses are not the same as IPv4-mapped addresses; they are compatible only in the sense that they can be written down or manipulated by software in a way similar to IPv4 addresses.

.Examples of IPv6 addresses and their binary representations
[%header,cols="1,1",width=75%]
|===
|Hex Notation
|Binary Representation

|5f05:2000:80ad:5800:58:800:2023:1d71
|0101111100000101 0010000000000000
1000000010101101 0101100000000000
0000000001011000 0000100000000000
0010000000100011 0001110101110001

|::1
|0000000000000000 0000000000000000
0000000000000000 0000000000000000
0000000000000000 0000000000000000
0000000000000000 0000000000000001

|::1.2.240.1 or ::102:f001
|0000000000000000 0000000000000000
0000000000000000 0000000000000000
0000000000000000 0000000000000000
0000000100000010 1111000000000001

|===

In some circumstances (e.g., when expressing a URL containing an address) the colon delimiter in an IPv6 address may be confused with another separator
such as the colon used between an IP address and a port number. In such circumstances, bracket characters, `[` and `]`, are used to surround the IPv6 address.

For example, the URL `http://[2001:0db8:85a3:08d3:1319:8a2e:0370:7344]:443/` refers to port number `443` on IPv6 host `2001:0db8:85a3:08d3:1319:8a2e:0370:7344` using the HTTP/TCP/IPv6 protocols.

== Basic IP Address Structure

Because of the large number of addresses (especially for IPv6), it is convenient to divide the address space into chunks. IP addresses are grouped by type and size.

Most of the IPv4 address chunks are eventually subdivided down to a single address and used to identify a single network interface of a computer attached to the Internet or to some private intranet. These addresses are called *unicast* addresses.

Beyond *unicast addresses*, other types of addresses include *broadcast*, *multicast*, and *anycast*, which may refer to more than one interface, plus some special-purpose addresses.

=== Classful Addressing

When the Internet’s address structure was originally defined, every unicast IP address had a _network_ portion, to identify the network on which the interface using the IP address was to be found, and a _host_ portion, used to identify the particular host on the network given in the network portion. Thus, some number of contiguous bits in the address became known as the _net number_, and remaining bits were known as the _host number_. At the time, most hosts had only a single network interface, so the terms _interface address_ and _host address_ were used somewhat interchangeably.
